//! RPC schema introspection metadata types.
//!
//! These types represent metadata extracted from Cap'n Proto schema annotations
//! (`$scope`/`$capability`, `$mcpDescription`, `$cliHidden`, `$paramDescription`).
//! They are the shared source of truth used by both the `generate_rpc_service!`
//! codegen macro and the runtime `ServiceFactory` inventory.

/// Schema metadata for a single RPC method parameter.
///
/// Extracted from Cap'n Proto struct field definitions and `$paramDescription` annotations.
#[derive(Debug, Clone)]
pub struct ParamMeta {
    pub name: &'static str,
    pub type_name: &'static str,
    pub required: bool,
    pub description: &'static str,
    /// Default value hint (empty = no default). For Bool fields this is "false".
    pub default_value: &'static str,
}

/// Schema metadata for a single RPC method.
///
/// Extracted from Cap'n Proto union variants and schema annotations
/// (`$scope`/`$capability`, `$mcpDescription`, `$cliHidden`).
#[derive(Debug, Clone)]
pub struct MethodMeta {
    pub name: &'static str,
    pub params: &'static [ParamMeta],
    pub description: &'static str,
    /// Required authorization scope action from `$scope`/`$capability` — one of the
    /// `ScopeAction` enumerants (S3, #547). Mandatory: empty only for a method that
    /// declared `$scopeExempt`. Maps 1:1 onto `hyprstream::auth::Operation`.
    pub scope: &'static str,
    pub is_streaming: bool,
    pub is_scoped: bool,
    pub scope_field: &'static str,
    /// Whether to hide from auto-generated interfaces (from `$cliHidden`).
    pub hidden: bool,
    /// VFS usage example from `$docExample` annotation. Empty = no example.
    pub doc_example: &'static str,
}

/// The 9P/VFS node kind a generated method projects to (epic #539).
///
/// Mirrors the `VfsNodeKind` capnp enum. `File`/`Dir`/`Query` are read-only
/// (side-effect-free 9P reads); `Ctl` is a write-a-verb control file; `Stream`
/// is a `/stream`-style pipe.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum VfsNodeKind {
    /// Readable (maybe writable) leaf; `read` renders the method's response.
    File,
    /// Directory; `readdir` lists child entries (e.g. a `list` method).
    Dir,
    /// Write-a-verb control file; a `write` invokes the method.
    Ctl,
    /// `/stream`-style pipe (data/info/ctl) for a streaming method.
    Stream,
    /// Synthetic query file: write a spec, read the result.
    Query,
}

impl VfsNodeKind {
    /// Whether a `read` of this node must be side-effect-free (9P read invariant).
    /// `File`/`Dir`/`Query` are read surfaces; `Ctl`/`Stream` mutate/produce.
    pub fn is_read_only(self) -> bool {
        matches!(self, Self::File | Self::Dir | Self::Query)
    }
}

/// A single node in a service's generated 9P/VFS projection (epic #539, T2).
///
/// Built by codegen from each method's `MethodMeta` + `$vfs*` annotations. The
/// runtime mount engine (T3) consumes these to serve `/srv/{service}` — `path`
/// is mount-relative (fid-0 rooted, never absolute); `{braces}` in `path` are
/// segments that bind the method's scalar argument.
#[derive(Copy, Clone, Debug)]
pub struct VfsNode {
    /// The method this node projects (snake_case), used to dispatch on access.
    pub method: &'static str,
    /// Mount-relative path; `{name}` segments bind a scalar arg from the walk.
    pub path: &'static str,
    /// The projected node kind (inferred from scope+shape, or `$vfsKind`).
    pub kind: VfsNodeKind,
    /// Authorization scope action (from `MethodMeta::scope`).
    pub scope: &'static str,
    /// `$vfsBulk`: `read` returns raw mmap bytes, bypassing capnp (DMA path).
    pub bulk: bool,
}

/// Function type for a service's VFS node table.
///
/// Returns `(service_name, nodes)`.
pub type VfsNodesFn = fn() -> (&'static str, &'static [VfsNode]);

/// Function type for service schema metadata.
///
/// Returns `(service_name, methods)`.
pub type SchemaMetadataFn = fn() -> (&'static str, &'static [MethodMeta]);

/// Function type for scoped service schema metadata.
///
/// Returns `(service_name, scope_name, methods)`.
pub type ScopedSchemaMetadataFn = fn() -> (&'static str, &'static str, &'static [MethodMeta]);

/// Tree node describing a scoped client and its nested children.
/// Generated by the proc macro, consumed by CLI/MCP for dynamic dispatch.
#[derive(Copy, Clone, Debug)]
pub struct ScopedClientTreeNode {
    pub scope_name: &'static str,
    pub scope_field: &'static str,
    pub metadata_fn: ScopedSchemaMetadataFn,
    pub nested: &'static [ScopedClientTreeNode],
}
