[build]
# Enable parallel compilation
jobs = 12
# Use sccache for faster builds
rustc-wrapper = "sccache"
# Enable incremental compilation
incremental = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "opt-level=3",
    "-C", "target-feature=+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2",
    "-C", "codegen-units=1"
]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"