//! Generates the `capnp.ts` shared runtime.
//!
//! This is a self-contained Cap'n Proto single-segment message builder/reader
//! for TypeScript. No external dependencies required.

/// Generate the capnp.ts runtime file content.
pub fn generate_capnp_runtime() -> String {
    r##"// Generated by hyprstream-ts-codegen — DO NOT EDIT
//
// Cap'n Proto single-segment message builder/reader for TypeScript.
// Implements the Cap'n Proto wire format without external dependencies.
//
// Message frame: [4B: segment_count-1] [4B: segment0_size_words] [segment0_bytes...]
// Struct pointer: [offset_words:30 | 0b00:2] [data_words:16 | ptr_words:16]
// List pointer:   [offset_words:30 | 0b01:2] [element_size:3 | element_count:29]
// Text/Data:      List(UInt8) with NUL terminator for Text

const WORD_SIZE = 8;

// Module-level singletons — avoid per-call allocation
const encoder = new TextEncoder();
const decoder = new TextDecoder();

/**
 * Single-segment Cap'n Proto message builder / arena.
 *
 * JS-heap backed — grows on demand via Uint8Array reallocation.
 */
export class CapnpArena {
  private buf: DataView;
  private raw: Uint8Array;
  /** Total allocated size in bytes */
  private capacity: number;
  /** Next free byte offset (for appending pointer targets) */
  private allocOffset: number;
  /** Byte offset where the root struct's data section starts */
  private readonly rootDataOffset: number;
  /** Byte offset where the root struct's pointer section starts */
  private readonly rootPtrOffset: number;
  private readonly dataWords: number;
  private readonly ptrWords: number;

  constructor(
    dataWords: number,
    ptrWords: number,
  ) {
    this.dataWords = dataWords;
    this.ptrWords = ptrWords;

    const structSize = (dataWords + ptrWords) * WORD_SIZE;
    const HEADER = 16;

    this.capacity = HEADER + structSize + 1024;
    this.raw = new Uint8Array(this.capacity);
    this.buf = new DataView(this.raw.buffer, this.raw.byteOffset, this.raw.byteLength);

    this.rootDataOffset = HEADER;
    this.rootPtrOffset  = HEADER + dataWords * WORD_SIZE;
    this.allocOffset    = HEADER + structSize;
  }

  /** The raw backing buffer (for diagnostics / direct access). */
  backingBuffer(): Uint8Array { return this.raw; }

  /** Ensure capacity for `needed` more bytes, growing if necessary. */
  private ensureCapacity(needed: number): void {
    if (this.allocOffset + needed <= this.capacity) return;
    const newCap = Math.max(this.capacity * 2, this.allocOffset + needed + 256);
    const newBuf = new Uint8Array(newCap);
    newBuf.set(this.raw);
    this.raw = newBuf;
    this.buf = new DataView(this.raw.buffer, this.raw.byteOffset, this.raw.byteLength);
    this.capacity = newCap;
  }

  /** Word-align the allocation offset. */
  private alignAlloc(): void {
    const rem = this.allocOffset % WORD_SIZE;
    if (rem !== 0) {
      this.allocOffset += WORD_SIZE - rem;
    }
  }

  // --- Data section setters ---

  setBool(byteOffset: number, bitIndex: number, value: boolean): void {
    const off = this.rootDataOffset + byteOffset;
    if (value) {
      this.raw[off] |= 1 << bitIndex;
    } else {
      this.raw[off] &= ~(1 << bitIndex);
    }
  }

  setUint8(byteOffset: number, value: number): void {
    this.buf.setUint8(this.rootDataOffset + byteOffset, value);
  }

  setUint16(byteOffset: number, value: number): void {
    this.buf.setUint16(this.rootDataOffset + byteOffset, value, true);
  }

  setUint32(byteOffset: number, value: number): void {
    this.buf.setUint32(this.rootDataOffset + byteOffset, value, true);
  }

  setUint64(byteOffset: number, value: bigint): void {
    this.buf.setBigUint64(this.rootDataOffset + byteOffset, value, true);
  }

  setInt8(byteOffset: number, value: number): void {
    this.buf.setInt8(this.rootDataOffset + byteOffset, value);
  }

  setInt16(byteOffset: number, value: number): void {
    this.buf.setInt16(this.rootDataOffset + byteOffset, value, true);
  }

  setInt32(byteOffset: number, value: number): void {
    this.buf.setInt32(this.rootDataOffset + byteOffset, value, true);
  }

  setInt64(byteOffset: number, value: bigint): void {
    this.buf.setBigInt64(this.rootDataOffset + byteOffset, value, true);
  }

  setFloat32(byteOffset: number, value: number): void {
    this.buf.setFloat32(this.rootDataOffset + byteOffset, value, true);
  }

  setFloat64(byteOffset: number, value: number): void {
    this.buf.setFloat64(this.rootDataOffset + byteOffset, value, true);
  }

  // --- Pointer section setters ---

  /**
   * Set a Text pointer at the given pointer index.
   * Encodes as a list of bytes with NUL terminator.
   */
  setText(ptrIndex: number, value: string): void {
    const encoded = encoder.encode(value);
    const byteLen = encoded.length + 1; // +1 for NUL
    const wordLen = Math.ceil(byteLen / WORD_SIZE);

    this.alignAlloc();
    this.ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.allocOffset;

    // Copy string bytes + NUL
    this.raw.set(encoded, targetOffset);
    this.raw[targetOffset + encoded.length] = 0; // NUL

    // Write list pointer: element_size=2 (byte), count=byteLen
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    // List pointer: B=1, C=offset, D=element_size(2=byte), E=count
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((byteLen << 3) | 2) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    this.allocOffset = targetOffset + wordLen * WORD_SIZE;
  }

  /**
   * Set a Data pointer at the given pointer index.
   * Encodes as a list of bytes (no NUL terminator).
   */
  setData(ptrIndex: number, value: Uint8Array): void {
    const byteLen = value.length;
    const wordLen = Math.ceil(byteLen / WORD_SIZE) || 0;

    if (byteLen === 0) return; // null pointer = zero bytes = already zero

    this.alignAlloc();
    this.ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.allocOffset;
    this.raw.set(value, targetOffset);

    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((byteLen << 3) | 2) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    this.allocOffset = targetOffset + wordLen * WORD_SIZE;
  }

  /**
   * Set a Text list pointer at the given pointer index.
   * Encodes as a composite list of struct pointers.
   */
  setTextList(ptrIndex: number, values: string[]): void {
    if (values.length === 0) return;

    this.alignAlloc();

    // For List(Text), each element is a pointer (1 pointer word per element)
    // Composite list: tag word + N * (0 data + 1 pointer) words
    const tagOffset = this.allocOffset;
    const elementCount = values.length;
    // Each element is a struct with 0 data words and 1 pointer word
    const elementWords = 1; // 0 data + 1 pointer = 1 word per element
    const totalWords = 1 + elementCount * elementWords; // 1 tag + N elements

    this.ensureCapacity(totalWords * WORD_SIZE + values.reduce((a, v) => a + v.length + 9, 0));

    // Write tag word (struct pointer describing element shape)
    // Struct pointer: offset = elementCount, data_words = 0, ptr_words = 1
    const tagLo = ((elementCount << 2) | 0) >>> 0;
    const tagHi = ((0 << 0) | (1 << 16)) >>> 0;
    this.buf.setUint32(tagOffset, tagLo, true);
    this.buf.setUint32(tagOffset + 4, tagHi, true);

    this.allocOffset = tagOffset + WORD_SIZE + elementCount * elementWords * WORD_SIZE;

    // Write list pointer
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const listTargetOffset = tagOffset;
    const offsetWords = (listTargetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    // Composite list: element_size=7 (composite), count=totalWords (words after tag)
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((elementCount * elementWords << 3) | 7) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    // Now write each element's pointer (pointing to text data)
    for (let i = 0; i < values.length; i++) {
      const elementPtrOffset = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      // Write text data after all elements
      const encoded = encoder.encode(values[i]);
      const byteLen = encoded.length + 1;
      const wordLen = Math.ceil(byteLen / WORD_SIZE);

      this.alignAlloc();
      this.ensureCapacity(wordLen * WORD_SIZE);

      const textOffset = this.allocOffset;
      this.raw.set(encoded, textOffset);
      this.raw[textOffset + encoded.length] = 0;

      const textOffsetWords = (textOffset - elementPtrOffset - WORD_SIZE) / WORD_SIZE;
      const textLo = ((textOffsetWords << 2) | 1) >>> 0;
      const textHi = ((byteLen << 3) | 2) >>> 0;
      this.buf.setUint32(elementPtrOffset, textLo, true);
      this.buf.setUint32(elementPtrOffset + 4, textHi, true);

      this.allocOffset = textOffset + wordLen * WORD_SIZE;
    }
  }

  /**
   * Set a Data list pointer (List(Data)) at the given pointer index.
   * Encodes as a composite list of byte-blob pointers (no NUL terminator).
   */
  setDataList(ptrIndex: number, values: Uint8Array[]): void {
    if (values.length === 0) return;

    this.alignAlloc();

    const tagOffset = this.allocOffset;
    const elementCount = values.length;
    const elementWords = 1; // 0 data + 1 pointer per element
    const totalWords = 1 + elementCount * elementWords;

    this.ensureCapacity(totalWords * WORD_SIZE + values.reduce((a, v) => a + v.length + 8, 0));

    const tagLo = ((elementCount << 2) | 0) >>> 0;
    const tagHi = ((0 << 0) | (1 << 16)) >>> 0;
    this.buf.setUint32(tagOffset, tagLo, true);
    this.buf.setUint32(tagOffset + 4, tagHi, true);

    this.allocOffset = tagOffset + WORD_SIZE + elementCount * elementWords * WORD_SIZE;

    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (tagOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((elementCount * elementWords << 3) | 7) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    for (let i = 0; i < values.length; i++) {
      const elementPtrOffset = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      const byteLen = values[i].length;
      const wordLen = Math.ceil(byteLen / WORD_SIZE);

      this.alignAlloc();
      this.ensureCapacity(wordLen * WORD_SIZE);

      const dataOffset = this.allocOffset;
      this.raw.set(values[i], dataOffset);

      const dataOffsetWords = (dataOffset - elementPtrOffset - WORD_SIZE) / WORD_SIZE;
      const dataLo = ((dataOffsetWords << 2) | 1) >>> 0;
      const dataHi = ((byteLen << 3) | 2) >>> 0;
      this.buf.setUint32(elementPtrOffset, dataLo, true);
      this.buf.setUint32(elementPtrOffset + 4, dataHi, true);

      this.allocOffset = dataOffset + wordLen * WORD_SIZE;
    }
  }

  /**
   * Allocate a fixed-width primitive list (List(Bool)/List(UIntN)/List(IntN)/List(FloatN))
   * pointer at `ptrIndex`. `elemSize` is the capnp list element-size tag
   * (1=bit, 2=1-byte, 3=2-byte, 4=4-byte, 5=8-byte); `byteWidth` is the
   * per-element byte width (ignored for bit-packed bool lists).
   * Returns the byte offset of the first element, or -1 for an empty list.
   */
  /**
   * Same as `allocPrimitiveList`, but takes the absolute byte offset of the
   * pointer word to write (rather than deriving it from `ptrIndex` against
   * the root pointer section). Shared by the root-level list setters and by
   * `List(List(_))` nested-list setters, whose inner-list pointer lives at a
   * computed offset inside the allocated outer pointer list, not at a
   * `ptrIndex` slot.
   */
  private allocPrimitiveListAt(ptrOffset: number, count: number, elemSize: number, byteWidth: number): number {
    if (count === 0) return -1;

    this.alignAlloc();
    const totalBytes = elemSize === 1 ? Math.ceil(count / 8) : count * byteWidth;
    const wordLen = Math.ceil(totalBytes / WORD_SIZE);
    this.ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.allocOffset;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((count << 3) | elemSize) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    this.allocOffset = targetOffset + wordLen * WORD_SIZE;
    return targetOffset;
  }

  private allocPrimitiveList(ptrIndex: number, count: number, elemSize: number, byteWidth: number): number {
    return this.allocPrimitiveListAt(this.rootPtrOffset + ptrIndex * WORD_SIZE, count, elemSize, byteWidth);
  }

  /**
   * Allocate the outer pointer-list structure for a `List(List(<inner>))`
   * field at `ptrIndex`: a plain pointer list (element_size=6) with one
   * pointer-word slot reserved per outer element. Each slot is later filled
   * in by `allocPrimitiveListAt` when the corresponding inner list is
   * written. Returns the byte offset of the first outer-element pointer
   * slot, or -1 for an empty outer list (leaving the field's pointer null).
   */
  private allocNestedListOuter(ptrIndex: number, outerCount: number): number {
    if (outerCount === 0) return -1;

    this.alignAlloc();
    this.ensureCapacity(outerCount * WORD_SIZE);

    const outerBase = this.allocOffset;
    this.allocOffset = outerBase + outerCount * WORD_SIZE;

    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (outerBase - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((outerCount << 3) | 6) >>> 0; // element_size=6: pointer list
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    return outerBase;
  }

  setBoolList(ptrIndex: number, values: boolean[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 1, 0);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) {
      if (values[i]) this.raw[base + (i >> 3)] |= 1 << (i & 7);
    }
  }

  setUint8List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 2, 1);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setUint8(base + i, values[i]);
  }

  setInt8List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 2, 1);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setInt8(base + i, values[i]);
  }

  setUint16List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 3, 2);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setUint16(base + i * 2, values[i], true);
  }

  setInt16List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 3, 2);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setInt16(base + i * 2, values[i], true);
  }

  setUint32List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 4, 4);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setUint32(base + i * 4, values[i], true);
  }

  setInt32List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 4, 4);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setInt32(base + i * 4, values[i], true);
  }

  setFloat32List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 4, 4);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setFloat32(base + i * 4, values[i], true);
  }

  setUint64List(ptrIndex: number, values: bigint[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 5, 8);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setBigUint64(base + i * 8, values[i], true);
  }

  setInt64List(ptrIndex: number, values: bigint[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 5, 8);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setBigInt64(base + i * 8, values[i], true);
  }

  setFloat64List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 5, 8);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.buf.setFloat64(base + i * 8, values[i], true);
  }

  // --- Nested List(List(<primitive>)) setters ---
  //
  // Each outer element is a pointer to an inner primitive list, allocated via
  // `allocNestedListOuter` (outer pointer-list shell) + `allocPrimitiveListAt`
  // (each inner list, written at the outer element's reserved pointer slot).

  setBoolListList(ptrIndex: number, values: boolean[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 1, 0);
      for (let j = 0; j < inner.length; j++) {
        if (inner[j]) this.raw[base + (j >> 3)] |= 1 << (j & 7);
      }
    }
  }

  setUint8ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 2, 1);
      for (let j = 0; j < inner.length; j++) this.buf.setUint8(base + j, inner[j]);
    }
  }

  setInt8ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 2, 1);
      for (let j = 0; j < inner.length; j++) this.buf.setInt8(base + j, inner[j]);
    }
  }

  setUint16ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 3, 2);
      for (let j = 0; j < inner.length; j++) this.buf.setUint16(base + j * 2, inner[j], true);
    }
  }

  setInt16ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 3, 2);
      for (let j = 0; j < inner.length; j++) this.buf.setInt16(base + j * 2, inner[j], true);
    }
  }

  setUint32ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 4, 4);
      for (let j = 0; j < inner.length; j++) this.buf.setUint32(base + j * 4, inner[j], true);
    }
  }

  setInt32ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 4, 4);
      for (let j = 0; j < inner.length; j++) this.buf.setInt32(base + j * 4, inner[j], true);
    }
  }

  setFloat32ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 4, 4);
      for (let j = 0; j < inner.length; j++) this.buf.setFloat32(base + j * 4, inner[j], true);
    }
  }

  setUint64ListList(ptrIndex: number, values: bigint[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 5, 8);
      for (let j = 0; j < inner.length; j++) this.buf.setBigUint64(base + j * 8, inner[j], true);
    }
  }

  setInt64ListList(ptrIndex: number, values: bigint[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 5, 8);
      for (let j = 0; j < inner.length; j++) this.buf.setBigInt64(base + j * 8, inner[j], true);
    }
  }

  setFloat64ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 5, 8);
      for (let j = 0; j < inner.length; j++) this.buf.setFloat64(base + j * 8, inner[j], true);
    }
  }

  /**
   * Initialize a sub-struct at the given pointer index.
   * Returns a StructBuilder for writing fields into the sub-struct.
   */
  initStruct(ptrIndex: number, dataWords: number, ptrWords: number): StructBuilder {
    const structSize = (dataWords + ptrWords) * WORD_SIZE;
    this.alignAlloc();
    this.ensureCapacity(structSize);

    const targetOffset = this.allocOffset;

    // Write struct pointer
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 0) >>> 0;
    const hi = ((dataWords & 0xFFFF) | ((ptrWords & 0xFFFF) << 16)) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    this.allocOffset = targetOffset + structSize;

    return new StructBuilder(this, targetOffset, dataWords, ptrWords);
  }

  /**
   * Initialize a List(Struct) composite list at the given pointer index.
   * Returns a StructBuilder[] for writing fields into each element.
   */
  initStructList(ptrIndex: number, count: number, dataWords: number, ptrWords: number): StructBuilder[] {
    if (count === 0) return [];

    this.alignAlloc();
    const tagOffset = this.allocOffset;
    const elementWords = dataWords + ptrWords;
    const totalBodyWords = count * elementWords;

    this.ensureCapacity((1 + totalBodyWords) * WORD_SIZE);

    // Write tag word (struct pointer describing element shape)
    const tagLo = ((count << 2) | 0) >>> 0;
    const tagHi = ((dataWords & 0xFFFF) | ((ptrWords & 0xFFFF) << 16)) >>> 0;
    this.buf.setUint32(tagOffset, tagLo, true);
    this.buf.setUint32(tagOffset + 4, tagHi, true);

    // Reserve space for all elements (pointer targets will be appended after)
    this.allocOffset = tagOffset + WORD_SIZE + totalBodyWords * WORD_SIZE;

    // Write composite list pointer
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (tagOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((totalBodyWords << 3) | 7) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    // Create StructBuilder for each element slot
    const builders: StructBuilder[] = [];
    for (let i = 0; i < count; i++) {
      const elemStart = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      builders.push(new StructBuilder(this, elemStart, dataWords, ptrWords));
    }
    return builders;
  }

  /** Finalize the message and return the wire-format bytes (view, no copy). */
  finish(): Uint8Array {
    // Write root struct pointer at bytes 8-15.
    // The root struct data starts at byte 16 = 0 words after the end of this pointer word.
    // Struct pointer: lo = (offsetWords << 2) | 0b00, hi = dataWords | (ptrWords << 16)
    this.buf.setUint32(8, 0, true); // lo: offset_words=0, type=struct(0b00)
    this.buf.setUint32(12, (this.dataWords & 0xffff) | ((this.ptrWords & 0xffff) << 16), true);

    // Segment covers bytes 8..allocOffset (everything after the 8-byte segment table).
    const segmentBytes = this.allocOffset - 8;
    const segmentWords = Math.ceil(segmentBytes / WORD_SIZE);

    // Write segment table
    this.buf.setUint32(0, 0, true); // segment count - 1 = 0 (single segment)
    this.buf.setUint32(4, segmentWords, true);

    const view = this.raw.subarray(0, 8 + segmentWords * WORD_SIZE);

    return view;
  }

  /** Access the underlying buffer (for StructBuilder). */
  _getRaw(): Uint8Array { return this.raw; }
  _getBuf(): DataView { return this.buf; }
  _getAllocOffset(): number { return this.allocOffset; }
  _setAllocOffset(off: number): void { this.allocOffset = off; }
  _ensureCapacity(n: number): void { this.ensureCapacity(n); }
  _alignAlloc(): void { this.alignAlloc(); }
}

/**
 * Builder for a sub-struct within a message.
 */
export class StructBuilder {
  private msg: CapnpArena;
  private dataOffset: number;
  private ptrOffset: number;

  constructor(
    msg: CapnpArena,
    structStart: number,
    dataWords: number,
    _ptrWords: number,
  ) {
    this.msg = msg;
    this.dataOffset = structStart;
    this.ptrOffset = structStart + dataWords * WORD_SIZE;
  }

  setBool(byteOffset: number, bitIndex: number, value: boolean): void {
    const off = this.dataOffset + byteOffset;
    const raw = this.msg._getRaw();
    if (value) {
      raw[off] |= 1 << bitIndex;
    } else {
      raw[off] &= ~(1 << bitIndex);
    }
  }

  setUint8(byteOffset: number, value: number): void {
    this.msg._getBuf().setUint8(this.dataOffset + byteOffset, value);
  }

  setUint16(byteOffset: number, value: number): void {
    this.msg._getBuf().setUint16(this.dataOffset + byteOffset, value, true);
  }

  setUint32(byteOffset: number, value: number): void {
    this.msg._getBuf().setUint32(this.dataOffset + byteOffset, value, true);
  }

  setUint64(byteOffset: number, value: bigint): void {
    this.msg._getBuf().setBigUint64(this.dataOffset + byteOffset, value, true);
  }

  setInt8(byteOffset: number, value: number): void {
    this.msg._getBuf().setInt8(this.dataOffset + byteOffset, value);
  }

  setInt16(byteOffset: number, value: number): void {
    this.msg._getBuf().setInt16(this.dataOffset + byteOffset, value, true);
  }

  setInt32(byteOffset: number, value: number): void {
    this.msg._getBuf().setInt32(this.dataOffset + byteOffset, value, true);
  }

  setInt64(byteOffset: number, value: bigint): void {
    this.msg._getBuf().setBigInt64(this.dataOffset + byteOffset, value, true);
  }

  setFloat32(byteOffset: number, value: number): void {
    this.msg._getBuf().setFloat32(this.dataOffset + byteOffset, value, true);
  }

  setFloat64(byteOffset: number, value: number): void {
    this.msg._getBuf().setFloat64(this.dataOffset + byteOffset, value, true);
  }

  setText(ptrIndex: number, value: string): void {
    const encoded = encoder.encode(value);
    const byteLen = encoded.length + 1;
    const wordLen = Math.ceil(byteLen / WORD_SIZE);

    this.msg._alignAlloc();
    this.msg._ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.msg._getAllocOffset();
    const raw = this.msg._getRaw();
    raw.set(encoded, targetOffset);
    raw[targetOffset + encoded.length] = 0;

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((byteLen << 3) | 2) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    this.msg._setAllocOffset(targetOffset + wordLen * WORD_SIZE);
  }

  setData(ptrIndex: number, value: Uint8Array): void {
    if (value.length === 0) return;
    const byteLen = value.length;
    const wordLen = Math.ceil(byteLen / WORD_SIZE);

    this.msg._alignAlloc();
    this.msg._ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.msg._getAllocOffset();
    this.msg._getRaw().set(value, targetOffset);

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((byteLen << 3) | 2) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    this.msg._setAllocOffset(targetOffset + wordLen * WORD_SIZE);
  }

  /**
   * Set a Data list pointer (List(Data)) at the given pointer index within this struct.
   * Encodes as a composite list of byte-blob pointers (no NUL terminator).
   */
  setDataList(ptrIndex: number, values: Uint8Array[]): void {
    if (values.length === 0) return;

    this.msg._alignAlloc();

    const tagOffset = this.msg._getAllocOffset();
    const elementCount = values.length;
    const elementWords = 1;
    const totalWords = 1 + elementCount * elementWords;

    this.msg._ensureCapacity(totalWords * WORD_SIZE + values.reduce((a, v) => a + v.length + 8, 0));

    const tagLo = ((elementCount << 2) | 0) >>> 0;
    const tagHi = ((0 << 0) | (1 << 16)) >>> 0;
    this.msg._getBuf().setUint32(tagOffset, tagLo, true);
    this.msg._getBuf().setUint32(tagOffset + 4, tagHi, true);

    this.msg._setAllocOffset(tagOffset + WORD_SIZE + elementCount * elementWords * WORD_SIZE);

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (tagOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((elementCount * elementWords << 3) | 7) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    for (let i = 0; i < values.length; i++) {
      const elementPtrOffset = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      const byteLen = values[i].length;
      const wordLen = Math.ceil(byteLen / WORD_SIZE);

      this.msg._alignAlloc();
      this.msg._ensureCapacity(wordLen * WORD_SIZE);

      const dataOffset = this.msg._getAllocOffset();
      this.msg._getRaw().set(values[i], dataOffset);

      const dataOffsetWords = (dataOffset - elementPtrOffset - WORD_SIZE) / WORD_SIZE;
      const dataLo = ((dataOffsetWords << 2) | 1) >>> 0;
      const dataHi = ((byteLen << 3) | 2) >>> 0;
      this.msg._getBuf().setUint32(elementPtrOffset, dataLo, true);
      this.msg._getBuf().setUint32(elementPtrOffset + 4, dataHi, true);

      this.msg._setAllocOffset(dataOffset + wordLen * WORD_SIZE);
    }
  }

  /**
   * Allocate a fixed-width primitive list (List(Bool)/List(UIntN)/List(IntN)/List(FloatN))
   * pointer at `ptrIndex` within this struct. `elemSize` is the capnp list
   * element-size tag (1=bit, 2=1-byte, 3=2-byte, 4=4-byte, 5=8-byte);
   * `byteWidth` is the per-element byte width (ignored for bit-packed bool lists).
   * Returns the byte offset of the first element, or -1 for an empty list.
   */
  private allocPrimitiveListAt(ptrOffset: number, count: number, elemSize: number, byteWidth: number): number {
    if (count === 0) return -1;

    this.msg._alignAlloc();
    const totalBytes = elemSize === 1 ? Math.ceil(count / 8) : count * byteWidth;
    const wordLen = Math.ceil(totalBytes / WORD_SIZE);
    this.msg._ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.msg._getAllocOffset();
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((count << 3) | elemSize) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    this.msg._setAllocOffset(targetOffset + wordLen * WORD_SIZE);
    return targetOffset;
  }

  private allocPrimitiveList(ptrIndex: number, count: number, elemSize: number, byteWidth: number): number {
    return this.allocPrimitiveListAt(this.ptrOffset + ptrIndex * WORD_SIZE, count, elemSize, byteWidth);
  }

  /**
   * Allocate the outer pointer-list structure for a `List(List(<inner>))`
   * field at `ptrIndex` within this struct. See `CapnpArena.allocNestedListOuter`
   * for the encoding this mirrors.
   */
  private allocNestedListOuter(ptrIndex: number, outerCount: number): number {
    if (outerCount === 0) return -1;

    this.msg._alignAlloc();
    this.msg._ensureCapacity(outerCount * WORD_SIZE);

    const outerBase = this.msg._getAllocOffset();
    this.msg._setAllocOffset(outerBase + outerCount * WORD_SIZE);

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (outerBase - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((outerCount << 3) | 6) >>> 0; // element_size=6: pointer list
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    return outerBase;
  }

  setBoolList(ptrIndex: number, values: boolean[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 1, 0);
    if (base < 0) return;
    const raw = this.msg._getRaw();
    for (let i = 0; i < values.length; i++) {
      if (values[i]) raw[base + (i >> 3)] |= 1 << (i & 7);
    }
  }

  setUint8List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 2, 1);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setUint8(base + i, values[i]);
  }

  setInt8List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 2, 1);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setInt8(base + i, values[i]);
  }

  setUint16List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 3, 2);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setUint16(base + i * 2, values[i], true);
  }

  setInt16List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 3, 2);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setInt16(base + i * 2, values[i], true);
  }

  setUint32List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 4, 4);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setUint32(base + i * 4, values[i], true);
  }

  setInt32List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 4, 4);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setInt32(base + i * 4, values[i], true);
  }

  setFloat32List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 4, 4);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setFloat32(base + i * 4, values[i], true);
  }

  setUint64List(ptrIndex: number, values: bigint[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 5, 8);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setBigUint64(base + i * 8, values[i], true);
  }

  setInt64List(ptrIndex: number, values: bigint[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 5, 8);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setBigInt64(base + i * 8, values[i], true);
  }

  setFloat64List(ptrIndex: number, values: number[]): void {
    const base = this.allocPrimitiveList(ptrIndex, values.length, 5, 8);
    if (base < 0) return;
    for (let i = 0; i < values.length; i++) this.msg._getBuf().setFloat64(base + i * 8, values[i], true);
  }

  // --- Nested List(List(<primitive>)) setters (see CapnpArena's for docs) ---

  setBoolListList(ptrIndex: number, values: boolean[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    const raw = this.msg._getRaw();
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 1, 0);
      for (let j = 0; j < inner.length; j++) {
        if (inner[j]) raw[base + (j >> 3)] |= 1 << (j & 7);
      }
    }
  }

  setUint8ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 2, 1);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setUint8(base + j, inner[j]);
    }
  }

  setInt8ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 2, 1);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setInt8(base + j, inner[j]);
    }
  }

  setUint16ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 3, 2);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setUint16(base + j * 2, inner[j], true);
    }
  }

  setInt16ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 3, 2);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setInt16(base + j * 2, inner[j], true);
    }
  }

  setUint32ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 4, 4);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setUint32(base + j * 4, inner[j], true);
    }
  }

  setInt32ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 4, 4);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setInt32(base + j * 4, inner[j], true);
    }
  }

  setFloat32ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 4, 4);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setFloat32(base + j * 4, inner[j], true);
    }
  }

  setUint64ListList(ptrIndex: number, values: bigint[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 5, 8);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setBigUint64(base + j * 8, inner[j], true);
    }
  }

  setInt64ListList(ptrIndex: number, values: bigint[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 5, 8);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setBigInt64(base + j * 8, inner[j], true);
    }
  }

  setFloat64ListList(ptrIndex: number, values: number[][]): void {
    const outerBase = this.allocNestedListOuter(ptrIndex, values.length);
    if (outerBase < 0) return;
    for (let i = 0; i < values.length; i++) {
      const inner = values[i];
      if (inner.length === 0) continue;
      const base = this.allocPrimitiveListAt(outerBase + i * WORD_SIZE, inner.length, 5, 8);
      for (let j = 0; j < inner.length; j++) this.msg._getBuf().setFloat64(base + j * 8, inner[j], true);
    }
  }

  /**
   * Initialize a sub-struct at the given pointer index within this struct.
   * Returns a StructBuilder for writing fields into the nested struct.
   */
  initStruct(ptrIndex: number, dataWords: number, ptrWords: number): StructBuilder {
    const structSize = (dataWords + ptrWords) * WORD_SIZE;
    this.msg._alignAlloc();
    this.msg._ensureCapacity(structSize);

    const targetOffset = this.msg._getAllocOffset();

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 0) >>> 0;
    const hi = ((dataWords & 0xFFFF) | ((ptrWords & 0xFFFF) << 16)) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    this.msg._setAllocOffset(targetOffset + structSize);

    return new StructBuilder(this.msg, targetOffset, dataWords, ptrWords);
  }

  /**
   * Set a Text list pointer at the given pointer index within this struct.
   */
  setTextList(ptrIndex: number, values: string[]): void {
    if (values.length === 0) return;

    this.msg._alignAlloc();
    const tagOffset = this.msg._getAllocOffset();
    const elementCount = values.length;
    const elementWords = 1;
    const totalWords = 1 + elementCount * elementWords;

    this.msg._ensureCapacity(totalWords * WORD_SIZE + values.reduce((a, v) => a + v.length + 9, 0));

    const tagLo = ((elementCount << 2) | 0) >>> 0;
    const tagHi = ((0 << 0) | (1 << 16)) >>> 0;
    this.msg._getBuf().setUint32(tagOffset, tagLo, true);
    this.msg._getBuf().setUint32(tagOffset + 4, tagHi, true);

    this.msg._setAllocOffset(tagOffset + WORD_SIZE + elementCount * elementWords * WORD_SIZE);

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const listTargetOffset = tagOffset;
    const offsetWords = (listTargetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((elementCount * elementWords << 3) | 7) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    for (let i = 0; i < values.length; i++) {
      const elementPtrOffset = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      const encoded = encoder.encode(values[i]);
      const byteLen = encoded.length + 1;
      const wordLen = Math.ceil(byteLen / WORD_SIZE);

      this.msg._alignAlloc();
      this.msg._ensureCapacity(wordLen * WORD_SIZE);

      const textOffset = this.msg._getAllocOffset();
      this.msg._getRaw().set(encoded, textOffset);
      this.msg._getRaw()[textOffset + encoded.length] = 0;

      const textOffsetWords = (textOffset - elementPtrOffset - WORD_SIZE) / WORD_SIZE;
      const textLo = ((textOffsetWords << 2) | 1) >>> 0;
      const textHi = ((byteLen << 3) | 2) >>> 0;
      this.msg._getBuf().setUint32(elementPtrOffset, textLo, true);
      this.msg._getBuf().setUint32(elementPtrOffset + 4, textHi, true);

      this.msg._setAllocOffset(textOffset + wordLen * WORD_SIZE);
    }
  }

  initStructList(ptrIndex: number, count: number, dataWords: number, ptrWords: number): StructBuilder[] {
    if (count === 0) return [];

    this.msg._alignAlloc();
    const tagOffset = this.msg._getAllocOffset();
    const elementWords = dataWords + ptrWords;
    const totalBodyWords = count * elementWords;

    this.msg._ensureCapacity((1 + totalBodyWords) * WORD_SIZE);

    const tagLo = ((count << 2) | 0) >>> 0;
    const tagHi = ((dataWords & 0xFFFF) | ((ptrWords & 0xFFFF) << 16)) >>> 0;
    this.msg._getBuf().setUint32(tagOffset, tagLo, true);
    this.msg._getBuf().setUint32(tagOffset + 4, tagHi, true);

    this.msg._setAllocOffset(tagOffset + WORD_SIZE + totalBodyWords * WORD_SIZE);

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (tagOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((totalBodyWords << 3) | 7) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    const builders: StructBuilder[] = [];
    for (let i = 0; i < count; i++) {
      const elemStart = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      builders.push(new StructBuilder(this.msg, elemStart, dataWords, ptrWords));
    }
    return builders;
  }
}

/**
 * Cap'n Proto message reader with multi-segment + far pointer support.
 *
 * Reads struct fields at known offsets from a wire-format message.
 * Handles both single-segment and multi-segment messages, resolving
 * far pointers (type=2) that reference data in other segments.
 */
export class CapnpReader {
  private buf: DataView;
  private raw: Uint8Array;
  /** Byte offset where the root struct's data section starts */
  private readonly rootDataOffset: number;
  /** Byte offset where the root struct's pointer section starts */
  private readonly rootPtrOffset: number;
  private readonly dataWords: number;
  /** Byte offsets of each segment start (for far pointer resolution) */
  private readonly segmentOffsets: number[];

  /**
   * Parse a Cap'n Proto message from wire-format bytes.
   * @param bytes Wire-format message bytes
   * @param dataWords Expected data word count of the root struct
   * @param ptrWords Expected pointer count of the root struct
   */
  constructor(bytes: Uint8Array, dataWords: number, _ptrWords: number) {
    this.raw = bytes;
    this.buf = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    this.dataWords = dataWords;
    this.segmentOffsets = [];

    // Standard Cap'n Proto format:
    //   Segment table: [num_segments-1 (u32), seg0_size (u32), seg1_size (u32), ...]
    //   Padded to 8-byte boundary, then segment data follows.
    //   Root struct pointer is the first word of segment 0.
    let rootDataOffset = 8; // fallback for malformed messages
    if (bytes.length >= 8) {
      const numSegments = (this.buf.getUint32(0, true)) + 1;
      const tableBytes = 4 + numSegments * 4;
      const segDataStart = Math.ceil(tableBytes / 8) * 8;

      // Build segment offset table for far pointer resolution
      let offset = segDataStart;
      for (let i = 0; i < numSegments; i++) {
        this.segmentOffsets.push(offset);
        const segWords = this.buf.getUint32(4 + i * 4, true);
        offset += segWords * WORD_SIZE;
      }

      // Root struct pointer is at segDataStart (first word of segment 0)
      if (bytes.length >= segDataStart + 8) {
        const rootPtrLo = this.buf.getUint32(segDataStart, true);
        if ((rootPtrLo & 3) === 0) {
          const offsetWords = rootPtrLo >> 2;
          rootDataOffset = segDataStart + 8 + offsetWords * 8;
        } else {
          rootDataOffset = segDataStart;
        }
      }
    }
    this.rootDataOffset = rootDataOffset;
    this.rootPtrOffset = rootDataOffset + dataWords * WORD_SIZE;
  }

  /**
   * Resolve a pointer, following far pointers (type=2) to the target segment.
   * Returns the resolved pointer words and their byte offset, or null if null pointer.
   */
  private resolvePtr(ptrOffset: number): { lo: number; hi: number; offset: number } | null {
    let lo = this.buf.getUint32(ptrOffset, true);
    let hi = this.buf.getUint32(ptrOffset + 4, true);
    if (lo === 0 && hi === 0) return null;
    if ((lo & 3) === 2) {
      // Far pointer: follow to target segment
      const farOffsetWords = lo >>> 3;
      const segmentId = hi;
      if (segmentId >= this.segmentOffsets.length) return null;
      const targetOffset = this.segmentOffsets[segmentId] + farOffsetWords * WORD_SIZE;
      if ((lo >> 2) & 1) return null; // double-far not supported
      lo = this.buf.getUint32(targetOffset, true);
      hi = this.buf.getUint32(targetOffset + 4, true);
      return { lo, hi, offset: targetOffset };
    }
    return { lo, hi, offset: ptrOffset };
  }

  // --- Data section getters ---

  getBool(byteOffset: number, bitIndex: number): boolean {
    return (this.raw[this.rootDataOffset + byteOffset] & (1 << bitIndex)) !== 0;
  }

  getUint8(byteOffset: number): number {
    return this.buf.getUint8(this.rootDataOffset + byteOffset);
  }

  getUint16(byteOffset: number): number {
    return this.buf.getUint16(this.rootDataOffset + byteOffset, true);
  }

  getUint32(byteOffset: number): number {
    return this.buf.getUint32(this.rootDataOffset + byteOffset, true);
  }

  getUint64(byteOffset: number): bigint {
    return this.buf.getBigUint64(this.rootDataOffset + byteOffset, true);
  }

  getInt8(byteOffset: number): number {
    return this.buf.getInt8(this.rootDataOffset + byteOffset);
  }

  getInt16(byteOffset: number): number {
    return this.buf.getInt16(this.rootDataOffset + byteOffset, true);
  }

  getInt32(byteOffset: number): number {
    return this.buf.getInt32(this.rootDataOffset + byteOffset, true);
  }

  getInt64(byteOffset: number): bigint {
    return this.buf.getBigInt64(this.rootDataOffset + byteOffset, true);
  }

  getFloat32(byteOffset: number): number {
    return this.buf.getFloat32(this.rootDataOffset + byteOffset, true);
  }

  getFloat64(byteOffset: number): number {
    return this.buf.getFloat64(this.rootDataOffset + byteOffset, true);
  }

  // --- Pointer section getters ---

  /** Read a Text pointer at the given pointer index. Returns empty string if null. */
  getText(ptrIndex: number): string {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return '';
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return '';
    const offsetWords = (lo >> 2) | 0;
    const byteCount = hi >>> 3;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    const strLen = byteCount > 0 ? byteCount - 1 : 0;
    return decoder.decode(this.raw.subarray(targetOffset, targetOffset + strLen));
  }

  /** Read a Data pointer at the given pointer index. Returns empty array if null. */
  getData(ptrIndex: number): Uint8Array {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return new Uint8Array(0);
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return new Uint8Array(0);
    const offsetWords = (lo >> 2) | 0;
    const byteCount = hi >>> 3;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    return this.raw.subarray(targetOffset, targetOffset + byteCount);
  }

  /** Read a struct pointer and return a StructReader. Returns null if pointer is null. */
  getStruct(ptrIndex: number, dataWords: number, ptrWords: number): StructReader | null {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return null;
    const { lo, offset } = resolved;
    if ((lo & 3) !== 0) return null;
    const offsetWords = (lo >> 2) | 0;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    return new StructReader(this.raw, this.buf, targetOffset, dataWords, ptrWords, this.segmentOffsets);
  }

  /** Read a List(Text) pointer (supports both pointer-list and composite encodings). */
  getTextList(ptrIndex: number): string[] {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize === 6) {
      // Pointer list: each element is a pointer to a text blob
      const elementCount = hi >>> 3;
      const results: string[] = [];
      for (let i = 0; i < elementCount; i++) {
        const elemOffset = targetOffset + i * WORD_SIZE;
        const elemLo = this.buf.getUint32(elemOffset, true);
        const elemHi = this.buf.getUint32(elemOffset + 4, true);
        if (elemLo === 0 && elemHi === 0) { results.push(''); continue; }
        const elemOffsetWords = (elemLo >> 2) | 0;
        const byteCount = elemHi >>> 3;
        const textOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
        const strLen = byteCount > 0 ? byteCount - 1 : 0;
        results.push(decoder.decode(this.raw.subarray(textOffset, textOffset + strLen)));
      }
      return results;
    }

    if (elementSize !== 7) return []; // unsupported element size

    // Composite list: tag word + elements
    const tagLo = this.buf.getUint32(targetOffset, true);
    const elementCount = (tagLo >> 2) | 0;

    const results: string[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemOffset = targetOffset + WORD_SIZE + i * WORD_SIZE;
      const elemLo = this.buf.getUint32(elemOffset, true);
      const elemHi = this.buf.getUint32(elemOffset + 4, true);

      if (elemLo === 0 && elemHi === 0) {
        results.push('');
        continue;
      }

      const elemOffsetWords = (elemLo >> 2) | 0;
      const byteCount = elemHi >>> 3;
      const textOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
      const strLen = byteCount > 0 ? byteCount - 1 : 0;
      results.push(decoder.decode(this.raw.subarray(textOffset, textOffset + strLen)));
    }

    return results;
  }

  /** Read a List(Data) pointer (supports both pointer-list and composite encodings). */
  getDataList(ptrIndex: number): Uint8Array[] {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    // Pointer list (element_size=6, the canonical List(Data) encoding — what
    // the Rust side emits) or composite list (element_size=7): both carry one
    // pointer per element, differing only in where the count lives and where
    // the elements start.
    let elementCount: number;
    let elemBase: number;
    if (elementSize === 6) {
      elementCount = hi >>> 3;
      elemBase = targetOffset;
    } else if (elementSize === 7) {
      const tagLo = this.buf.getUint32(targetOffset, true);
      elementCount = (tagLo >> 2) | 0;
      elemBase = targetOffset + WORD_SIZE;
    } else {
      return [];
    }

    const results: Uint8Array[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemOffset = elemBase + i * WORD_SIZE;
      const elemLo = this.buf.getUint32(elemOffset, true);
      const elemHi = this.buf.getUint32(elemOffset + 4, true);

      if (elemLo === 0 && elemHi === 0) {
        results.push(new Uint8Array(0));
        continue;
      }

      const elemOffsetWords = (elemLo >> 2) | 0;
      const byteCount = elemHi >>> 3;
      const dataOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
      results.push(this.raw.subarray(dataOffset, dataOffset + byteCount));
    }

    return results;
  }

  /**
   * Read a fixed-width primitive list (List(Bool)/List(UIntN)/List(IntN)/List(FloatN)).
   * `expectedElemSize` is the capnp list element-size tag this getter accepts
   * (1=bit, 2=1-byte, 3=2-byte, 4=4-byte, 5=8-byte); `byteWidth` is the
   * per-element byte width (ignored for bit-packed bool lists). Returns `[]`
   * if the pointer is null or was encoded with a different element size.
   */
  private readPrimitiveList<T>(
    ptrIndex: number,
    expectedElemSize: number,
    byteWidth: number,
    read: (byteOffset: number, bitIndex: number) => T,
  ): T[] {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    if (elementSize !== expectedElemSize) return [];
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    const count = hi >>> 3;

    const results: T[] = [];
    for (let i = 0; i < count; i++) {
      results.push(
        byteWidth === 0
          ? read(targetOffset + (i >> 3), i & 7)
          : read(targetOffset + i * byteWidth, 0),
      );
    }
    return results;
  }

  getBoolList(ptrIndex: number): boolean[] {
    return this.readPrimitiveList(ptrIndex, 1, 0, (byteOffset, bitIndex) => (this.raw[byteOffset] & (1 << bitIndex)) !== 0);
  }

  getUint8List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 2, 1, (o) => this.buf.getUint8(o));
  }

  getInt8List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 2, 1, (o) => this.buf.getInt8(o));
  }

  getUint16List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 3, 2, (o) => this.buf.getUint16(o, true));
  }

  getInt16List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 3, 2, (o) => this.buf.getInt16(o, true));
  }

  getUint32List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getUint32(o, true));
  }

  getInt32List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getInt32(o, true));
  }

  getFloat32List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getFloat32(o, true));
  }

  getUint64List(ptrIndex: number): bigint[] {
    return this.readPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getBigUint64(o, true));
  }

  getInt64List(ptrIndex: number): bigint[] {
    return this.readPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getBigInt64(o, true));
  }

  getFloat64List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getFloat64(o, true));
  }

  /**
   * Read a `List(List(<inner>))` field: a pointer list whose elements are
   * themselves primitive lists (List(Bool)/List(UIntN)/List(IntN)/List(FloatN)).
   * Mirrors `readPrimitiveList`, resolving one extra level of pointer
   * indirection per outer element. Supports both the canonical pointer-list
   * outer encoding (element_size=6) and composite (element_size=7, used when
   * the outer list happens to be optimized as a single-pointer struct list).
   * An outer element whose inner pointer is null, or whose encoded element
   * size doesn't match `innerElemSize`, reads as `[]` for that element.
   */
  private readNestedPrimitiveList<T>(
    ptrIndex: number,
    innerElemSize: number,
    innerByteWidth: number,
    readInner: (byteOffset: number, bitIndex: number) => T,
  ): T[][] {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const outerElementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    let outerCount: number;
    let outerBase: number;
    if (outerElementSize === 6) {
      outerCount = hi >>> 3;
      outerBase = targetOffset;
    } else if (outerElementSize === 7) {
      const tagLo = this.buf.getUint32(targetOffset, true);
      outerCount = (tagLo >> 2) | 0;
      outerBase = targetOffset + WORD_SIZE;
    } else {
      return [];
    }

    const results: T[][] = [];
    for (let i = 0; i < outerCount; i++) {
      const elemPtrOffset = outerBase + i * WORD_SIZE;
      const elemResolved = this.resolvePtr(elemPtrOffset);
      if (!elemResolved) { results.push([]); continue; }
      const { lo: iLo, hi: iHi, offset: iOffset } = elemResolved;
      if ((iLo & 3) !== 1 || (iHi & 7) !== innerElemSize) { results.push([]); continue; }
      const iOffsetWords = (iLo >> 2) | 0;
      const innerTarget = iOffset + WORD_SIZE + iOffsetWords * WORD_SIZE;
      const innerCount = iHi >>> 3;
      const inner: T[] = [];
      for (let j = 0; j < innerCount; j++) {
        inner.push(
          innerByteWidth === 0
            ? readInner(innerTarget + (j >> 3), j & 7)
            : readInner(innerTarget + j * innerByteWidth, 0),
        );
      }
      results.push(inner);
    }
    return results;
  }

  getBoolListList(ptrIndex: number): boolean[][] {
    return this.readNestedPrimitiveList(ptrIndex, 1, 0, (byteOffset, bitIndex) => (this.raw[byteOffset] & (1 << bitIndex)) !== 0);
  }

  getUint8ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 2, 1, (o) => this.buf.getUint8(o));
  }

  getInt8ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 2, 1, (o) => this.buf.getInt8(o));
  }

  getUint16ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 3, 2, (o) => this.buf.getUint16(o, true));
  }

  getInt16ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 3, 2, (o) => this.buf.getInt16(o, true));
  }

  getUint32ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getUint32(o, true));
  }

  getInt32ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getInt32(o, true));
  }

  getFloat32ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getFloat32(o, true));
  }

  getUint64ListList(ptrIndex: number): bigint[][] {
    return this.readNestedPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getBigUint64(o, true));
  }

  getInt64ListList(ptrIndex: number): bigint[][] {
    return this.readNestedPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getBigInt64(o, true));
  }

  getFloat64ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getFloat64(o, true));
  }

  /** Read a List(Struct) composite list pointer. Returns StructReader[] using wire-format shape from tag word. */
  getStructList(ptrIndex: number, _dataWords: number, _ptrWords: number): StructReader[] {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize !== 7) return []; // not composite

    // Read tag word — struct pointer encoding element shape
    const tagLo = this.buf.getUint32(targetOffset, true);
    const tagHi = this.buf.getUint32(targetOffset + 4, true);
    const elementCount = (tagLo >> 2) | 0;
    const tagDataWords = tagHi & 0xFFFF;
    const tagPtrWords = (tagHi >> 16) & 0xFFFF;
    const elementWords = tagDataWords + tagPtrWords;

    const results: StructReader[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemDataOffset = targetOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      results.push(new StructReader(this.raw, this.buf, elemDataOffset, tagDataWords, tagPtrWords, this.segmentOffsets));
    }
    return results;
  }
}

/**
 * Reader for a sub-struct within a message.
 * Supports far pointer resolution for multi-segment messages.
 */
export class StructReader {
  constructor(
    private raw: Uint8Array,
    private buf: DataView,
    private dataOffset: number,
    private dataWords: number,
    private ptrWords: number,
    private segmentOffsets: readonly number[] = [],
  ) {}

  /** Resolve a pointer, following far pointers (type=2) to the target segment. */
  private resolvePtr(ptrOffset: number): { lo: number; hi: number; offset: number } | null {
    let lo = this.buf.getUint32(ptrOffset, true);
    let hi = this.buf.getUint32(ptrOffset + 4, true);
    if (lo === 0 && hi === 0) return null;
    if ((lo & 3) === 2) {
      const farOffsetWords = lo >>> 3;
      const segmentId = hi;
      if (segmentId >= this.segmentOffsets.length) return null;
      const targetOffset = this.segmentOffsets[segmentId] + farOffsetWords * WORD_SIZE;
      if ((lo >> 2) & 1) return null; // double-far not supported
      lo = this.buf.getUint32(targetOffset, true);
      hi = this.buf.getUint32(targetOffset + 4, true);
      return { lo, hi, offset: targetOffset };
    }
    return { lo, hi, offset: ptrOffset };
  }

  getBool(byteOffset: number, bitIndex: number): boolean {
    return (this.raw[this.dataOffset + byteOffset] & (1 << bitIndex)) !== 0;
  }

  getUint8(byteOffset: number): number {
    return this.buf.getUint8(this.dataOffset + byteOffset);
  }

  getUint16(byteOffset: number): number {
    return this.buf.getUint16(this.dataOffset + byteOffset, true);
  }

  getUint32(byteOffset: number): number {
    return this.buf.getUint32(this.dataOffset + byteOffset, true);
  }

  getUint64(byteOffset: number): bigint {
    return this.buf.getBigUint64(this.dataOffset + byteOffset, true);
  }

  getInt8(byteOffset: number): number {
    return this.buf.getInt8(this.dataOffset + byteOffset);
  }

  getInt16(byteOffset: number): number {
    return this.buf.getInt16(this.dataOffset + byteOffset, true);
  }

  getInt32(byteOffset: number): number {
    return this.buf.getInt32(this.dataOffset + byteOffset, true);
  }

  getInt64(byteOffset: number): bigint {
    return this.buf.getBigInt64(this.dataOffset + byteOffset, true);
  }

  getFloat32(byteOffset: number): number {
    return this.buf.getFloat32(this.dataOffset + byteOffset, true);
  }

  getFloat64(byteOffset: number): number {
    return this.buf.getFloat64(this.dataOffset + byteOffset, true);
  }

  getText(ptrIndex: number): string {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return '';
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return '';
    const offsetWords = (lo >> 2) | 0;
    const byteCount = hi >>> 3;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    const strLen = byteCount > 0 ? byteCount - 1 : 0;
    return decoder.decode(this.raw.subarray(targetOffset, targetOffset + strLen));
  }

  getData(ptrIndex: number): Uint8Array {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return new Uint8Array(0);
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return new Uint8Array(0);
    const offsetWords = (lo >> 2) | 0;
    const byteCount = hi >>> 3;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    return this.raw.subarray(targetOffset, targetOffset + byteCount);
  }

  getStruct(ptrIndex: number, dataWords: number, ptrWords: number): StructReader | null {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return null;
    const { lo, offset } = resolved;
    if ((lo & 3) !== 0) return null;
    const offsetWords = (lo >> 2) | 0;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    return new StructReader(this.raw, this.buf, targetOffset, dataWords, ptrWords, this.segmentOffsets);
  }

  getTextList(ptrIndex: number): string[] {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize === 6) {
      const elementCount = hi >>> 3;
      const results: string[] = [];
      for (let i = 0; i < elementCount; i++) {
        const elemOffset = targetOffset + i * WORD_SIZE;
        const elemLo = this.buf.getUint32(elemOffset, true);
        const elemHi = this.buf.getUint32(elemOffset + 4, true);
        if (elemLo === 0 && elemHi === 0) { results.push(''); continue; }
        const elemOffsetWords = (elemLo >> 2) | 0;
        const byteCount = elemHi >>> 3;
        const textOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
        const strLen = byteCount > 0 ? byteCount - 1 : 0;
        results.push(decoder.decode(this.raw.subarray(textOffset, textOffset + strLen)));
      }
      return results;
    }

    if (elementSize !== 7) return [];

    const tagLo = this.buf.getUint32(targetOffset, true);
    const elementCount = (tagLo >> 2) | 0;

    const results: string[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemOffset = targetOffset + WORD_SIZE + i * WORD_SIZE;
      const elemLo = this.buf.getUint32(elemOffset, true);
      const elemHi = this.buf.getUint32(elemOffset + 4, true);
      if (elemLo === 0 && elemHi === 0) { results.push(''); continue; }
      const elemOffsetWords = (elemLo >> 2) | 0;
      const byteCount = elemHi >>> 3;
      const textOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
      const strLen = byteCount > 0 ? byteCount - 1 : 0;
      results.push(decoder.decode(this.raw.subarray(textOffset, textOffset + strLen)));
    }
    return results;
  }

  getDataList(ptrIndex: number): Uint8Array[] {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize !== 7) return [];
    const tagLo = this.buf.getUint32(targetOffset, true);
    const elementCount = (tagLo >> 2) | 0;

    const results: Uint8Array[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemOffset = targetOffset + WORD_SIZE + i * WORD_SIZE;
      const elemLo = this.buf.getUint32(elemOffset, true);
      const elemHi = this.buf.getUint32(elemOffset + 4, true);
      if (elemLo === 0 && elemHi === 0) { results.push(new Uint8Array(0)); continue; }
      const elemOffsetWords = (elemLo >> 2) | 0;
      const byteCount = elemHi >>> 3;
      const dataOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
      results.push(this.raw.subarray(dataOffset, dataOffset + byteCount));
    }
    return results;
  }

  /**
   * Read a fixed-width primitive list (List(Bool)/List(UIntN)/List(IntN)/List(FloatN))
   * within this struct. See `CapnpReader.readPrimitiveList` for the element-size
   * encoding this mirrors.
   */
  private readPrimitiveList<T>(
    ptrIndex: number,
    expectedElemSize: number,
    byteWidth: number,
    read: (byteOffset: number, bitIndex: number) => T,
  ): T[] {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    if (elementSize !== expectedElemSize) return [];
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    const count = hi >>> 3;

    const results: T[] = [];
    for (let i = 0; i < count; i++) {
      results.push(
        byteWidth === 0
          ? read(targetOffset + (i >> 3), i & 7)
          : read(targetOffset + i * byteWidth, 0),
      );
    }
    return results;
  }

  getBoolList(ptrIndex: number): boolean[] {
    return this.readPrimitiveList(ptrIndex, 1, 0, (byteOffset, bitIndex) => (this.raw[byteOffset] & (1 << bitIndex)) !== 0);
  }

  getUint8List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 2, 1, (o) => this.buf.getUint8(o));
  }

  getInt8List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 2, 1, (o) => this.buf.getInt8(o));
  }

  getUint16List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 3, 2, (o) => this.buf.getUint16(o, true));
  }

  getInt16List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 3, 2, (o) => this.buf.getInt16(o, true));
  }

  getUint32List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getUint32(o, true));
  }

  getInt32List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getInt32(o, true));
  }

  getFloat32List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getFloat32(o, true));
  }

  getUint64List(ptrIndex: number): bigint[] {
    return this.readPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getBigUint64(o, true));
  }

  getInt64List(ptrIndex: number): bigint[] {
    return this.readPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getBigInt64(o, true));
  }

  getFloat64List(ptrIndex: number): number[] {
    return this.readPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getFloat64(o, true));
  }

  /**
   * Read a `List(List(<inner>))` field within this struct. See
   * `CapnpReader.readNestedPrimitiveList` for the encoding this mirrors.
   */
  private readNestedPrimitiveList<T>(
    ptrIndex: number,
    innerElemSize: number,
    innerByteWidth: number,
    readInner: (byteOffset: number, bitIndex: number) => T,
  ): T[][] {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const outerElementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    let outerCount: number;
    let outerBase: number;
    if (outerElementSize === 6) {
      outerCount = hi >>> 3;
      outerBase = targetOffset;
    } else if (outerElementSize === 7) {
      const tagLo = this.buf.getUint32(targetOffset, true);
      outerCount = (tagLo >> 2) | 0;
      outerBase = targetOffset + WORD_SIZE;
    } else {
      return [];
    }

    const results: T[][] = [];
    for (let i = 0; i < outerCount; i++) {
      const elemPtrOffset = outerBase + i * WORD_SIZE;
      const elemResolved = this.resolvePtr(elemPtrOffset);
      if (!elemResolved) { results.push([]); continue; }
      const { lo: iLo, hi: iHi, offset: iOffset } = elemResolved;
      if ((iLo & 3) !== 1 || (iHi & 7) !== innerElemSize) { results.push([]); continue; }
      const iOffsetWords = (iLo >> 2) | 0;
      const innerTarget = iOffset + WORD_SIZE + iOffsetWords * WORD_SIZE;
      const innerCount = iHi >>> 3;
      const inner: T[] = [];
      for (let j = 0; j < innerCount; j++) {
        inner.push(
          innerByteWidth === 0
            ? readInner(innerTarget + (j >> 3), j & 7)
            : readInner(innerTarget + j * innerByteWidth, 0),
        );
      }
      results.push(inner);
    }
    return results;
  }

  getBoolListList(ptrIndex: number): boolean[][] {
    return this.readNestedPrimitiveList(ptrIndex, 1, 0, (byteOffset, bitIndex) => (this.raw[byteOffset] & (1 << bitIndex)) !== 0);
  }

  getUint8ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 2, 1, (o) => this.buf.getUint8(o));
  }

  getInt8ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 2, 1, (o) => this.buf.getInt8(o));
  }

  getUint16ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 3, 2, (o) => this.buf.getUint16(o, true));
  }

  getInt16ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 3, 2, (o) => this.buf.getInt16(o, true));
  }

  getUint32ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getUint32(o, true));
  }

  getInt32ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getInt32(o, true));
  }

  getFloat32ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 4, 4, (o) => this.buf.getFloat32(o, true));
  }

  getUint64ListList(ptrIndex: number): bigint[][] {
    return this.readNestedPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getBigUint64(o, true));
  }

  getInt64ListList(ptrIndex: number): bigint[][] {
    return this.readNestedPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getBigInt64(o, true));
  }

  getFloat64ListList(ptrIndex: number): number[][] {
    return this.readNestedPrimitiveList(ptrIndex, 5, 8, (o) => this.buf.getFloat64(o, true));
  }

  getStructList(ptrIndex: number, _dataWords: number, _ptrWords: number): StructReader[] {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize !== 7) return [];
    const tagLo = this.buf.getUint32(targetOffset, true);
    const tagHi = this.buf.getUint32(targetOffset + 4, true);
    const elementCount = (tagLo >> 2) | 0;
    const tagDataWords = tagHi & 0xFFFF;
    const tagPtrWords = (tagHi >> 16) & 0xFFFF;
    const elementWords = tagDataWords + tagPtrWords;

    const results: StructReader[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemDataOffset = targetOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      results.push(new StructReader(this.raw, this.buf, elemDataOffset, tagDataWords, tagPtrWords, this.segmentOffsets));
    }
    return results;
  }
}

/** Backwards-compatible alias — prefer CapnpArena for new code. */
export const CapnpMessageBuilder = CapnpArena;
"##.to_owned()
}
