//! Generates the `capnp.ts` shared runtime.
//!
//! This is a self-contained Cap'n Proto single-segment message builder/reader
//! for TypeScript. No external dependencies required.

/// Generate the capnp.ts runtime file content.
pub fn generate_capnp_runtime() -> String {
    r##"// Generated by hyprstream-ts-codegen — DO NOT EDIT
//
// Cap'n Proto single-segment message builder/reader for TypeScript.
// Implements the Cap'n Proto wire format without external dependencies.
//
// Message frame: [4B: segment_count-1] [4B: segment0_size_words] [segment0_bytes...]
// Struct pointer: [offset_words:30 | 0b00:2] [data_words:16 | ptr_words:16]
// List pointer:   [offset_words:30 | 0b01:2] [element_size:3 | element_count:29]
// Text/Data:      List(UInt8) with NUL terminator for Text

const WORD_SIZE = 8;

// Module-level singletons — avoid per-call allocation
const encoder = new TextEncoder();
const decoder = new TextDecoder();

/**
 * Single-segment Cap'n Proto message builder / arena.
 *
 * JS-heap backed — grows on demand via Uint8Array reallocation.
 */
export class CapnpArena {
  private buf: DataView;
  private raw: Uint8Array;
  /** Total allocated size in bytes */
  private capacity: number;
  /** Next free byte offset (for appending pointer targets) */
  private allocOffset: number;
  /** Byte offset where the root struct's data section starts */
  private readonly rootDataOffset: number;
  /** Byte offset where the root struct's pointer section starts */
  private readonly rootPtrOffset: number;
  private readonly dataWords: number;
  private readonly ptrWords: number;

  constructor(
    dataWords: number,
    ptrWords: number,
  ) {
    this.dataWords = dataWords;
    this.ptrWords = ptrWords;

    const structSize = (dataWords + ptrWords) * WORD_SIZE;
    const HEADER = 16;

    this.capacity = HEADER + structSize + 1024;
    this.raw = new Uint8Array(this.capacity);
    this.buf = new DataView(this.raw.buffer, this.raw.byteOffset, this.raw.byteLength);

    this.rootDataOffset = HEADER;
    this.rootPtrOffset  = HEADER + dataWords * WORD_SIZE;
    this.allocOffset    = HEADER + structSize;
  }

  /** The raw backing buffer (for diagnostics / direct access). */
  backingBuffer(): Uint8Array { return this.raw; }

  /** Ensure capacity for `needed` more bytes, growing if necessary. */
  private ensureCapacity(needed: number): void {
    if (this.allocOffset + needed <= this.capacity) return;
    const newCap = Math.max(this.capacity * 2, this.allocOffset + needed + 256);
    const newBuf = new Uint8Array(newCap);
    newBuf.set(this.raw);
    this.raw = newBuf;
    this.buf = new DataView(this.raw.buffer, this.raw.byteOffset, this.raw.byteLength);
    this.capacity = newCap;
  }

  /** Word-align the allocation offset. */
  private alignAlloc(): void {
    const rem = this.allocOffset % WORD_SIZE;
    if (rem !== 0) {
      this.allocOffset += WORD_SIZE - rem;
    }
  }

  // --- Data section setters ---

  setBool(byteOffset: number, bitIndex: number, value: boolean): void {
    const off = this.rootDataOffset + byteOffset;
    if (value) {
      this.raw[off] |= 1 << bitIndex;
    } else {
      this.raw[off] &= ~(1 << bitIndex);
    }
  }

  setUint8(byteOffset: number, value: number): void {
    this.buf.setUint8(this.rootDataOffset + byteOffset, value);
  }

  setUint16(byteOffset: number, value: number): void {
    this.buf.setUint16(this.rootDataOffset + byteOffset, value, true);
  }

  setUint32(byteOffset: number, value: number): void {
    this.buf.setUint32(this.rootDataOffset + byteOffset, value, true);
  }

  setUint64(byteOffset: number, value: bigint): void {
    this.buf.setBigUint64(this.rootDataOffset + byteOffset, value, true);
  }

  setInt8(byteOffset: number, value: number): void {
    this.buf.setInt8(this.rootDataOffset + byteOffset, value);
  }

  setInt16(byteOffset: number, value: number): void {
    this.buf.setInt16(this.rootDataOffset + byteOffset, value, true);
  }

  setInt32(byteOffset: number, value: number): void {
    this.buf.setInt32(this.rootDataOffset + byteOffset, value, true);
  }

  setInt64(byteOffset: number, value: bigint): void {
    this.buf.setBigInt64(this.rootDataOffset + byteOffset, value, true);
  }

  setFloat32(byteOffset: number, value: number): void {
    this.buf.setFloat32(this.rootDataOffset + byteOffset, value, true);
  }

  setFloat64(byteOffset: number, value: number): void {
    this.buf.setFloat64(this.rootDataOffset + byteOffset, value, true);
  }

  // --- Pointer section setters ---

  /**
   * Set a Text pointer at the given pointer index.
   * Encodes as a list of bytes with NUL terminator.
   */
  setText(ptrIndex: number, value: string): void {
    const encoded = encoder.encode(value);
    const byteLen = encoded.length + 1; // +1 for NUL
    const wordLen = Math.ceil(byteLen / WORD_SIZE);

    this.alignAlloc();
    this.ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.allocOffset;

    // Copy string bytes + NUL
    this.raw.set(encoded, targetOffset);
    this.raw[targetOffset + encoded.length] = 0; // NUL

    // Write list pointer: element_size=2 (byte), count=byteLen
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    // List pointer: B=1, C=offset, D=element_size(2=byte), E=count
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((byteLen << 3) | 2) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    this.allocOffset = targetOffset + wordLen * WORD_SIZE;
  }

  /**
   * Set a Data pointer at the given pointer index.
   * Encodes as a list of bytes (no NUL terminator).
   */
  setData(ptrIndex: number, value: Uint8Array): void {
    const byteLen = value.length;
    const wordLen = Math.ceil(byteLen / WORD_SIZE) || 0;

    if (byteLen === 0) return; // null pointer = zero bytes = already zero

    this.alignAlloc();
    this.ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.allocOffset;
    this.raw.set(value, targetOffset);

    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((byteLen << 3) | 2) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    this.allocOffset = targetOffset + wordLen * WORD_SIZE;
  }

  /**
   * Set a Text list pointer at the given pointer index.
   * Encodes as a composite list of struct pointers.
   */
  setTextList(ptrIndex: number, values: string[]): void {
    if (values.length === 0) return;

    this.alignAlloc();

    // For List(Text), each element is a pointer (1 pointer word per element)
    // Composite list: tag word + N * (0 data + 1 pointer) words
    const tagOffset = this.allocOffset;
    const elementCount = values.length;
    // Each element is a struct with 0 data words and 1 pointer word
    const elementWords = 1; // 0 data + 1 pointer = 1 word per element
    const totalWords = 1 + elementCount * elementWords; // 1 tag + N elements

    this.ensureCapacity(totalWords * WORD_SIZE + values.reduce((a, v) => a + v.length + 9, 0));

    // Write tag word (struct pointer describing element shape)
    // Struct pointer: offset = elementCount, data_words = 0, ptr_words = 1
    const tagLo = ((elementCount << 2) | 0) >>> 0;
    const tagHi = ((0 << 0) | (1 << 16)) >>> 0;
    this.buf.setUint32(tagOffset, tagLo, true);
    this.buf.setUint32(tagOffset + 4, tagHi, true);

    this.allocOffset = tagOffset + WORD_SIZE + elementCount * elementWords * WORD_SIZE;

    // Write list pointer
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const listTargetOffset = tagOffset;
    const offsetWords = (listTargetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    // Composite list: element_size=7 (composite), count=totalWords (words after tag)
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((elementCount * elementWords << 3) | 7) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    // Now write each element's pointer (pointing to text data)
    for (let i = 0; i < values.length; i++) {
      const elementPtrOffset = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      // Write text data after all elements
      const encoded = encoder.encode(values[i]);
      const byteLen = encoded.length + 1;
      const wordLen = Math.ceil(byteLen / WORD_SIZE);

      this.alignAlloc();
      this.ensureCapacity(wordLen * WORD_SIZE);

      const textOffset = this.allocOffset;
      this.raw.set(encoded, textOffset);
      this.raw[textOffset + encoded.length] = 0;

      const textOffsetWords = (textOffset - elementPtrOffset - WORD_SIZE) / WORD_SIZE;
      const textLo = ((textOffsetWords << 2) | 1) >>> 0;
      const textHi = ((byteLen << 3) | 2) >>> 0;
      this.buf.setUint32(elementPtrOffset, textLo, true);
      this.buf.setUint32(elementPtrOffset + 4, textHi, true);

      this.allocOffset = textOffset + wordLen * WORD_SIZE;
    }
  }

  /**
   * Initialize a sub-struct at the given pointer index.
   * Returns a StructBuilder for writing fields into the sub-struct.
   */
  initStruct(ptrIndex: number, dataWords: number, ptrWords: number): StructBuilder {
    const structSize = (dataWords + ptrWords) * WORD_SIZE;
    this.alignAlloc();
    this.ensureCapacity(structSize);

    const targetOffset = this.allocOffset;

    // Write struct pointer
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 0) >>> 0;
    const hi = ((dataWords & 0xFFFF) | ((ptrWords & 0xFFFF) << 16)) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    this.allocOffset = targetOffset + structSize;

    return new StructBuilder(this, targetOffset, dataWords, ptrWords);
  }

  /**
   * Initialize a List(Struct) composite list at the given pointer index.
   * Returns a StructBuilder[] for writing fields into each element.
   */
  initStructList(ptrIndex: number, count: number, dataWords: number, ptrWords: number): StructBuilder[] {
    if (count === 0) return [];

    this.alignAlloc();
    const tagOffset = this.allocOffset;
    const elementWords = dataWords + ptrWords;
    const totalBodyWords = count * elementWords;

    this.ensureCapacity((1 + totalBodyWords) * WORD_SIZE);

    // Write tag word (struct pointer describing element shape)
    const tagLo = ((count << 2) | 0) >>> 0;
    const tagHi = ((dataWords & 0xFFFF) | ((ptrWords & 0xFFFF) << 16)) >>> 0;
    this.buf.setUint32(tagOffset, tagLo, true);
    this.buf.setUint32(tagOffset + 4, tagHi, true);

    // Reserve space for all elements (pointer targets will be appended after)
    this.allocOffset = tagOffset + WORD_SIZE + totalBodyWords * WORD_SIZE;

    // Write composite list pointer
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (tagOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((totalBodyWords << 3) | 7) >>> 0;
    this.buf.setUint32(ptrOffset, lo, true);
    this.buf.setUint32(ptrOffset + 4, hi, true);

    // Create StructBuilder for each element slot
    const builders: StructBuilder[] = [];
    for (let i = 0; i < count; i++) {
      const elemStart = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      builders.push(new StructBuilder(this, elemStart, dataWords, ptrWords));
    }
    return builders;
  }

  /** Finalize the message and return the wire-format bytes (view, no copy). */
  finish(): Uint8Array {
    // Write root struct pointer at bytes 8-15.
    // The root struct data starts at byte 16 = 0 words after the end of this pointer word.
    // Struct pointer: lo = (offsetWords << 2) | 0b00, hi = dataWords | (ptrWords << 16)
    this.buf.setUint32(8, 0, true); // lo: offset_words=0, type=struct(0b00)
    this.buf.setUint32(12, (this.dataWords & 0xffff) | ((this.ptrWords & 0xffff) << 16), true);

    // Segment covers bytes 8..allocOffset (everything after the 8-byte segment table).
    const segmentBytes = this.allocOffset - 8;
    const segmentWords = Math.ceil(segmentBytes / WORD_SIZE);

    // Write segment table
    this.buf.setUint32(0, 0, true); // segment count - 1 = 0 (single segment)
    this.buf.setUint32(4, segmentWords, true);

    const view = this.raw.subarray(0, 8 + segmentWords * WORD_SIZE);

    return view;
  }

  /** Access the underlying buffer (for StructBuilder). */
  _getRaw(): Uint8Array { return this.raw; }
  _getBuf(): DataView { return this.buf; }
  _getAllocOffset(): number { return this.allocOffset; }
  _setAllocOffset(off: number): void { this.allocOffset = off; }
  _ensureCapacity(n: number): void { this.ensureCapacity(n); }
  _alignAlloc(): void { this.alignAlloc(); }
}

/**
 * Builder for a sub-struct within a message.
 */
export class StructBuilder {
  private msg: CapnpArena;
  private dataOffset: number;
  private ptrOffset: number;

  constructor(
    msg: CapnpArena,
    structStart: number,
    dataWords: number,
    _ptrWords: number,
  ) {
    this.msg = msg;
    this.dataOffset = structStart;
    this.ptrOffset = structStart + dataWords * WORD_SIZE;
  }

  setBool(byteOffset: number, bitIndex: number, value: boolean): void {
    const off = this.dataOffset + byteOffset;
    const raw = this.msg._getRaw();
    if (value) {
      raw[off] |= 1 << bitIndex;
    } else {
      raw[off] &= ~(1 << bitIndex);
    }
  }

  setUint8(byteOffset: number, value: number): void {
    this.msg._getBuf().setUint8(this.dataOffset + byteOffset, value);
  }

  setUint16(byteOffset: number, value: number): void {
    this.msg._getBuf().setUint16(this.dataOffset + byteOffset, value, true);
  }

  setUint32(byteOffset: number, value: number): void {
    this.msg._getBuf().setUint32(this.dataOffset + byteOffset, value, true);
  }

  setUint64(byteOffset: number, value: bigint): void {
    this.msg._getBuf().setBigUint64(this.dataOffset + byteOffset, value, true);
  }

  setInt8(byteOffset: number, value: number): void {
    this.msg._getBuf().setInt8(this.dataOffset + byteOffset, value);
  }

  setInt16(byteOffset: number, value: number): void {
    this.msg._getBuf().setInt16(this.dataOffset + byteOffset, value, true);
  }

  setInt32(byteOffset: number, value: number): void {
    this.msg._getBuf().setInt32(this.dataOffset + byteOffset, value, true);
  }

  setInt64(byteOffset: number, value: bigint): void {
    this.msg._getBuf().setBigInt64(this.dataOffset + byteOffset, value, true);
  }

  setFloat32(byteOffset: number, value: number): void {
    this.msg._getBuf().setFloat32(this.dataOffset + byteOffset, value, true);
  }

  setFloat64(byteOffset: number, value: number): void {
    this.msg._getBuf().setFloat64(this.dataOffset + byteOffset, value, true);
  }

  setText(ptrIndex: number, value: string): void {
    const encoded = encoder.encode(value);
    const byteLen = encoded.length + 1;
    const wordLen = Math.ceil(byteLen / WORD_SIZE);

    this.msg._alignAlloc();
    this.msg._ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.msg._getAllocOffset();
    const raw = this.msg._getRaw();
    raw.set(encoded, targetOffset);
    raw[targetOffset + encoded.length] = 0;

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((byteLen << 3) | 2) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    this.msg._setAllocOffset(targetOffset + wordLen * WORD_SIZE);
  }

  setData(ptrIndex: number, value: Uint8Array): void {
    if (value.length === 0) return;
    const byteLen = value.length;
    const wordLen = Math.ceil(byteLen / WORD_SIZE);

    this.msg._alignAlloc();
    this.msg._ensureCapacity(wordLen * WORD_SIZE);

    const targetOffset = this.msg._getAllocOffset();
    this.msg._getRaw().set(value, targetOffset);

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((byteLen << 3) | 2) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    this.msg._setAllocOffset(targetOffset + wordLen * WORD_SIZE);
  }

  /**
   * Initialize a sub-struct at the given pointer index within this struct.
   * Returns a StructBuilder for writing fields into the nested struct.
   */
  initStruct(ptrIndex: number, dataWords: number, ptrWords: number): StructBuilder {
    const structSize = (dataWords + ptrWords) * WORD_SIZE;
    this.msg._alignAlloc();
    this.msg._ensureCapacity(structSize);

    const targetOffset = this.msg._getAllocOffset();

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (targetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 0) >>> 0;
    const hi = ((dataWords & 0xFFFF) | ((ptrWords & 0xFFFF) << 16)) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    this.msg._setAllocOffset(targetOffset + structSize);

    return new StructBuilder(this.msg, targetOffset, dataWords, ptrWords);
  }

  /**
   * Set a Text list pointer at the given pointer index within this struct.
   */
  setTextList(ptrIndex: number, values: string[]): void {
    if (values.length === 0) return;

    this.msg._alignAlloc();
    const tagOffset = this.msg._getAllocOffset();
    const elementCount = values.length;
    const elementWords = 1;
    const totalWords = 1 + elementCount * elementWords;

    this.msg._ensureCapacity(totalWords * WORD_SIZE + values.reduce((a, v) => a + v.length + 9, 0));

    const tagLo = ((elementCount << 2) | 0) >>> 0;
    const tagHi = ((0 << 0) | (1 << 16)) >>> 0;
    this.msg._getBuf().setUint32(tagOffset, tagLo, true);
    this.msg._getBuf().setUint32(tagOffset + 4, tagHi, true);

    this.msg._setAllocOffset(tagOffset + WORD_SIZE + elementCount * elementWords * WORD_SIZE);

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const listTargetOffset = tagOffset;
    const offsetWords = (listTargetOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((elementCount * elementWords << 3) | 7) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    for (let i = 0; i < values.length; i++) {
      const elementPtrOffset = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      const encoded = encoder.encode(values[i]);
      const byteLen = encoded.length + 1;
      const wordLen = Math.ceil(byteLen / WORD_SIZE);

      this.msg._alignAlloc();
      this.msg._ensureCapacity(wordLen * WORD_SIZE);

      const textOffset = this.msg._getAllocOffset();
      this.msg._getRaw().set(encoded, textOffset);
      this.msg._getRaw()[textOffset + encoded.length] = 0;

      const textOffsetWords = (textOffset - elementPtrOffset - WORD_SIZE) / WORD_SIZE;
      const textLo = ((textOffsetWords << 2) | 1) >>> 0;
      const textHi = ((byteLen << 3) | 2) >>> 0;
      this.msg._getBuf().setUint32(elementPtrOffset, textLo, true);
      this.msg._getBuf().setUint32(elementPtrOffset + 4, textHi, true);

      this.msg._setAllocOffset(textOffset + wordLen * WORD_SIZE);
    }
  }

  initStructList(ptrIndex: number, count: number, dataWords: number, ptrWords: number): StructBuilder[] {
    if (count === 0) return [];

    this.msg._alignAlloc();
    const tagOffset = this.msg._getAllocOffset();
    const elementWords = dataWords + ptrWords;
    const totalBodyWords = count * elementWords;

    this.msg._ensureCapacity((1 + totalBodyWords) * WORD_SIZE);

    const tagLo = ((count << 2) | 0) >>> 0;
    const tagHi = ((dataWords & 0xFFFF) | ((ptrWords & 0xFFFF) << 16)) >>> 0;
    this.msg._getBuf().setUint32(tagOffset, tagLo, true);
    this.msg._getBuf().setUint32(tagOffset + 4, tagHi, true);

    this.msg._setAllocOffset(tagOffset + WORD_SIZE + totalBodyWords * WORD_SIZE);

    const ptrOffset = this.ptrOffset + ptrIndex * WORD_SIZE;
    const offsetWords = (tagOffset - ptrOffset - WORD_SIZE) / WORD_SIZE;
    const lo = ((offsetWords << 2) | 1) >>> 0;
    const hi = ((totalBodyWords << 3) | 7) >>> 0;
    this.msg._getBuf().setUint32(ptrOffset, lo, true);
    this.msg._getBuf().setUint32(ptrOffset + 4, hi, true);

    const builders: StructBuilder[] = [];
    for (let i = 0; i < count; i++) {
      const elemStart = tagOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      builders.push(new StructBuilder(this.msg, elemStart, dataWords, ptrWords));
    }
    return builders;
  }
}

/**
 * Cap'n Proto message reader with multi-segment + far pointer support.
 *
 * Reads struct fields at known offsets from a wire-format message.
 * Handles both single-segment and multi-segment messages, resolving
 * far pointers (type=2) that reference data in other segments.
 */
export class CapnpReader {
  private buf: DataView;
  private raw: Uint8Array;
  /** Byte offset where the root struct's data section starts */
  private readonly rootDataOffset: number;
  /** Byte offset where the root struct's pointer section starts */
  private readonly rootPtrOffset: number;
  private readonly dataWords: number;
  /** Byte offsets of each segment start (for far pointer resolution) */
  private readonly segmentOffsets: number[];

  /**
   * Parse a Cap'n Proto message from wire-format bytes.
   * @param bytes Wire-format message bytes
   * @param dataWords Expected data word count of the root struct
   * @param ptrWords Expected pointer count of the root struct
   */
  constructor(bytes: Uint8Array, dataWords: number, _ptrWords: number) {
    this.raw = bytes;
    this.buf = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    this.dataWords = dataWords;
    this.segmentOffsets = [];

    // Standard Cap'n Proto format:
    //   Segment table: [num_segments-1 (u32), seg0_size (u32), seg1_size (u32), ...]
    //   Padded to 8-byte boundary, then segment data follows.
    //   Root struct pointer is the first word of segment 0.
    let rootDataOffset = 8; // fallback for malformed messages
    if (bytes.length >= 8) {
      const numSegments = (this.buf.getUint32(0, true)) + 1;
      const tableBytes = 4 + numSegments * 4;
      const segDataStart = Math.ceil(tableBytes / 8) * 8;

      // Build segment offset table for far pointer resolution
      let offset = segDataStart;
      for (let i = 0; i < numSegments; i++) {
        this.segmentOffsets.push(offset);
        const segWords = this.buf.getUint32(4 + i * 4, true);
        offset += segWords * WORD_SIZE;
      }

      // Root struct pointer is at segDataStart (first word of segment 0)
      if (bytes.length >= segDataStart + 8) {
        const rootPtrLo = this.buf.getUint32(segDataStart, true);
        if ((rootPtrLo & 3) === 0) {
          const offsetWords = rootPtrLo >> 2;
          rootDataOffset = segDataStart + 8 + offsetWords * 8;
        } else {
          rootDataOffset = segDataStart;
        }
      }
    }
    this.rootDataOffset = rootDataOffset;
    this.rootPtrOffset = rootDataOffset + dataWords * WORD_SIZE;
  }

  /**
   * Resolve a pointer, following far pointers (type=2) to the target segment.
   * Returns the resolved pointer words and their byte offset, or null if null pointer.
   */
  private resolvePtr(ptrOffset: number): { lo: number; hi: number; offset: number } | null {
    let lo = this.buf.getUint32(ptrOffset, true);
    let hi = this.buf.getUint32(ptrOffset + 4, true);
    if (lo === 0 && hi === 0) return null;
    if ((lo & 3) === 2) {
      // Far pointer: follow to target segment
      const farOffsetWords = lo >>> 3;
      const segmentId = hi;
      if (segmentId >= this.segmentOffsets.length) return null;
      const targetOffset = this.segmentOffsets[segmentId] + farOffsetWords * WORD_SIZE;
      if ((lo >> 2) & 1) return null; // double-far not supported
      lo = this.buf.getUint32(targetOffset, true);
      hi = this.buf.getUint32(targetOffset + 4, true);
      return { lo, hi, offset: targetOffset };
    }
    return { lo, hi, offset: ptrOffset };
  }

  // --- Data section getters ---

  getBool(byteOffset: number, bitIndex: number): boolean {
    return (this.raw[this.rootDataOffset + byteOffset] & (1 << bitIndex)) !== 0;
  }

  getUint8(byteOffset: number): number {
    return this.buf.getUint8(this.rootDataOffset + byteOffset);
  }

  getUint16(byteOffset: number): number {
    return this.buf.getUint16(this.rootDataOffset + byteOffset, true);
  }

  getUint32(byteOffset: number): number {
    return this.buf.getUint32(this.rootDataOffset + byteOffset, true);
  }

  getUint64(byteOffset: number): bigint {
    return this.buf.getBigUint64(this.rootDataOffset + byteOffset, true);
  }

  getInt8(byteOffset: number): number {
    return this.buf.getInt8(this.rootDataOffset + byteOffset);
  }

  getInt16(byteOffset: number): number {
    return this.buf.getInt16(this.rootDataOffset + byteOffset, true);
  }

  getInt32(byteOffset: number): number {
    return this.buf.getInt32(this.rootDataOffset + byteOffset, true);
  }

  getInt64(byteOffset: number): bigint {
    return this.buf.getBigInt64(this.rootDataOffset + byteOffset, true);
  }

  getFloat32(byteOffset: number): number {
    return this.buf.getFloat32(this.rootDataOffset + byteOffset, true);
  }

  getFloat64(byteOffset: number): number {
    return this.buf.getFloat64(this.rootDataOffset + byteOffset, true);
  }

  // --- Pointer section getters ---

  /** Read a Text pointer at the given pointer index. Returns empty string if null. */
  getText(ptrIndex: number): string {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return '';
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return '';
    const offsetWords = (lo >> 2) | 0;
    const byteCount = hi >>> 3;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    const strLen = byteCount > 0 ? byteCount - 1 : 0;
    return decoder.decode(this.raw.subarray(targetOffset, targetOffset + strLen));
  }

  /** Read a Data pointer at the given pointer index. Returns empty array if null. */
  getData(ptrIndex: number): Uint8Array {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return new Uint8Array(0);
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return new Uint8Array(0);
    const offsetWords = (lo >> 2) | 0;
    const byteCount = hi >>> 3;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    return this.raw.subarray(targetOffset, targetOffset + byteCount);
  }

  /** Read a struct pointer and return a StructReader. Returns null if pointer is null. */
  getStruct(ptrIndex: number, dataWords: number, ptrWords: number): StructReader | null {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return null;
    const { lo, offset } = resolved;
    if ((lo & 3) !== 0) return null;
    const offsetWords = (lo >> 2) | 0;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    return new StructReader(this.raw, this.buf, targetOffset, dataWords, ptrWords, this.segmentOffsets);
  }

  /** Read a List(Text) pointer (supports both pointer-list and composite encodings). */
  getTextList(ptrIndex: number): string[] {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize === 6) {
      // Pointer list: each element is a pointer to a text blob
      const elementCount = hi >>> 3;
      const results: string[] = [];
      for (let i = 0; i < elementCount; i++) {
        const elemOffset = targetOffset + i * WORD_SIZE;
        const elemLo = this.buf.getUint32(elemOffset, true);
        const elemHi = this.buf.getUint32(elemOffset + 4, true);
        if (elemLo === 0 && elemHi === 0) { results.push(''); continue; }
        const elemOffsetWords = (elemLo >> 2) | 0;
        const byteCount = elemHi >>> 3;
        const textOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
        const strLen = byteCount > 0 ? byteCount - 1 : 0;
        results.push(decoder.decode(this.raw.subarray(textOffset, textOffset + strLen)));
      }
      return results;
    }

    if (elementSize !== 7) return []; // unsupported element size

    // Composite list: tag word + elements
    const tagLo = this.buf.getUint32(targetOffset, true);
    const elementCount = (tagLo >> 2) | 0;

    const results: string[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemOffset = targetOffset + WORD_SIZE + i * WORD_SIZE;
      const elemLo = this.buf.getUint32(elemOffset, true);
      const elemHi = this.buf.getUint32(elemOffset + 4, true);

      if (elemLo === 0 && elemHi === 0) {
        results.push('');
        continue;
      }

      const elemOffsetWords = (elemLo >> 2) | 0;
      const byteCount = elemHi >>> 3;
      const textOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
      const strLen = byteCount > 0 ? byteCount - 1 : 0;
      results.push(decoder.decode(this.raw.subarray(textOffset, textOffset + strLen)));
    }

    return results;
  }

  /** Read a List(Data) pointer. */
  getDataList(ptrIndex: number): Uint8Array[] {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize !== 7) return []; // not composite

    const tagLo = this.buf.getUint32(targetOffset, true);
    const elementCount = (tagLo >> 2) | 0;

    const results: Uint8Array[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemOffset = targetOffset + WORD_SIZE + i * WORD_SIZE;
      const elemLo = this.buf.getUint32(elemOffset, true);
      const elemHi = this.buf.getUint32(elemOffset + 4, true);

      if (elemLo === 0 && elemHi === 0) {
        results.push(new Uint8Array(0));
        continue;
      }

      const elemOffsetWords = (elemLo >> 2) | 0;
      const byteCount = elemHi >>> 3;
      const dataOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
      results.push(this.raw.subarray(dataOffset, dataOffset + byteCount));
    }

    return results;
  }

  /** Read a List(Struct) composite list pointer. Returns StructReader[] using wire-format shape from tag word. */
  getStructList(ptrIndex: number, _dataWords: number, _ptrWords: number): StructReader[] {
    const ptrOffset = this.rootPtrOffset + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize !== 7) return []; // not composite

    // Read tag word — struct pointer encoding element shape
    const tagLo = this.buf.getUint32(targetOffset, true);
    const tagHi = this.buf.getUint32(targetOffset + 4, true);
    const elementCount = (tagLo >> 2) | 0;
    const tagDataWords = tagHi & 0xFFFF;
    const tagPtrWords = (tagHi >> 16) & 0xFFFF;
    const elementWords = tagDataWords + tagPtrWords;

    const results: StructReader[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemDataOffset = targetOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      results.push(new StructReader(this.raw, this.buf, elemDataOffset, tagDataWords, tagPtrWords, this.segmentOffsets));
    }
    return results;
  }
}

/**
 * Reader for a sub-struct within a message.
 * Supports far pointer resolution for multi-segment messages.
 */
export class StructReader {
  constructor(
    private raw: Uint8Array,
    private buf: DataView,
    private dataOffset: number,
    private dataWords: number,
    private ptrWords: number,
    private segmentOffsets: readonly number[] = [],
  ) {}

  /** Resolve a pointer, following far pointers (type=2) to the target segment. */
  private resolvePtr(ptrOffset: number): { lo: number; hi: number; offset: number } | null {
    let lo = this.buf.getUint32(ptrOffset, true);
    let hi = this.buf.getUint32(ptrOffset + 4, true);
    if (lo === 0 && hi === 0) return null;
    if ((lo & 3) === 2) {
      const farOffsetWords = lo >>> 3;
      const segmentId = hi;
      if (segmentId >= this.segmentOffsets.length) return null;
      const targetOffset = this.segmentOffsets[segmentId] + farOffsetWords * WORD_SIZE;
      if ((lo >> 2) & 1) return null; // double-far not supported
      lo = this.buf.getUint32(targetOffset, true);
      hi = this.buf.getUint32(targetOffset + 4, true);
      return { lo, hi, offset: targetOffset };
    }
    return { lo, hi, offset: ptrOffset };
  }

  getBool(byteOffset: number, bitIndex: number): boolean {
    return (this.raw[this.dataOffset + byteOffset] & (1 << bitIndex)) !== 0;
  }

  getUint8(byteOffset: number): number {
    return this.buf.getUint8(this.dataOffset + byteOffset);
  }

  getUint16(byteOffset: number): number {
    return this.buf.getUint16(this.dataOffset + byteOffset, true);
  }

  getUint32(byteOffset: number): number {
    return this.buf.getUint32(this.dataOffset + byteOffset, true);
  }

  getUint64(byteOffset: number): bigint {
    return this.buf.getBigUint64(this.dataOffset + byteOffset, true);
  }

  getInt8(byteOffset: number): number {
    return this.buf.getInt8(this.dataOffset + byteOffset);
  }

  getInt16(byteOffset: number): number {
    return this.buf.getInt16(this.dataOffset + byteOffset, true);
  }

  getInt32(byteOffset: number): number {
    return this.buf.getInt32(this.dataOffset + byteOffset, true);
  }

  getInt64(byteOffset: number): bigint {
    return this.buf.getBigInt64(this.dataOffset + byteOffset, true);
  }

  getFloat32(byteOffset: number): number {
    return this.buf.getFloat32(this.dataOffset + byteOffset, true);
  }

  getFloat64(byteOffset: number): number {
    return this.buf.getFloat64(this.dataOffset + byteOffset, true);
  }

  getText(ptrIndex: number): string {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return '';
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return '';
    const offsetWords = (lo >> 2) | 0;
    const byteCount = hi >>> 3;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    const strLen = byteCount > 0 ? byteCount - 1 : 0;
    return decoder.decode(this.raw.subarray(targetOffset, targetOffset + strLen));
  }

  getData(ptrIndex: number): Uint8Array {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return new Uint8Array(0);
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return new Uint8Array(0);
    const offsetWords = (lo >> 2) | 0;
    const byteCount = hi >>> 3;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    return this.raw.subarray(targetOffset, targetOffset + byteCount);
  }

  getStruct(ptrIndex: number, dataWords: number, ptrWords: number): StructReader | null {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return null;
    const { lo, offset } = resolved;
    if ((lo & 3) !== 0) return null;
    const offsetWords = (lo >> 2) | 0;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;
    return new StructReader(this.raw, this.buf, targetOffset, dataWords, ptrWords, this.segmentOffsets);
  }

  getTextList(ptrIndex: number): string[] {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize === 6) {
      const elementCount = hi >>> 3;
      const results: string[] = [];
      for (let i = 0; i < elementCount; i++) {
        const elemOffset = targetOffset + i * WORD_SIZE;
        const elemLo = this.buf.getUint32(elemOffset, true);
        const elemHi = this.buf.getUint32(elemOffset + 4, true);
        if (elemLo === 0 && elemHi === 0) { results.push(''); continue; }
        const elemOffsetWords = (elemLo >> 2) | 0;
        const byteCount = elemHi >>> 3;
        const textOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
        const strLen = byteCount > 0 ? byteCount - 1 : 0;
        results.push(decoder.decode(this.raw.subarray(textOffset, textOffset + strLen)));
      }
      return results;
    }

    if (elementSize !== 7) return [];

    const tagLo = this.buf.getUint32(targetOffset, true);
    const elementCount = (tagLo >> 2) | 0;

    const results: string[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemOffset = targetOffset + WORD_SIZE + i * WORD_SIZE;
      const elemLo = this.buf.getUint32(elemOffset, true);
      const elemHi = this.buf.getUint32(elemOffset + 4, true);
      if (elemLo === 0 && elemHi === 0) { results.push(''); continue; }
      const elemOffsetWords = (elemLo >> 2) | 0;
      const byteCount = elemHi >>> 3;
      const textOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
      const strLen = byteCount > 0 ? byteCount - 1 : 0;
      results.push(decoder.decode(this.raw.subarray(textOffset, textOffset + strLen)));
    }
    return results;
  }

  getDataList(ptrIndex: number): Uint8Array[] {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize !== 7) return [];
    const tagLo = this.buf.getUint32(targetOffset, true);
    const elementCount = (tagLo >> 2) | 0;

    const results: Uint8Array[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemOffset = targetOffset + WORD_SIZE + i * WORD_SIZE;
      const elemLo = this.buf.getUint32(elemOffset, true);
      const elemHi = this.buf.getUint32(elemOffset + 4, true);
      if (elemLo === 0 && elemHi === 0) { results.push(new Uint8Array(0)); continue; }
      const elemOffsetWords = (elemLo >> 2) | 0;
      const byteCount = elemHi >>> 3;
      const dataOffset = elemOffset + WORD_SIZE + elemOffsetWords * WORD_SIZE;
      results.push(this.raw.subarray(dataOffset, dataOffset + byteCount));
    }
    return results;
  }

  getStructList(ptrIndex: number, _dataWords: number, _ptrWords: number): StructReader[] {
    const ptrOffset = this.dataOffset + this.dataWords * WORD_SIZE + ptrIndex * WORD_SIZE;
    const resolved = this.resolvePtr(ptrOffset);
    if (!resolved) return [];
    const { lo, hi, offset } = resolved;
    if ((lo & 3) !== 1) return [];

    const offsetWords = (lo >> 2) | 0;
    const elementSize = hi & 7;
    const targetOffset = offset + WORD_SIZE + offsetWords * WORD_SIZE;

    if (elementSize !== 7) return [];
    const tagLo = this.buf.getUint32(targetOffset, true);
    const tagHi = this.buf.getUint32(targetOffset + 4, true);
    const elementCount = (tagLo >> 2) | 0;
    const tagDataWords = tagHi & 0xFFFF;
    const tagPtrWords = (tagHi >> 16) & 0xFFFF;
    const elementWords = tagDataWords + tagPtrWords;

    const results: StructReader[] = [];
    for (let i = 0; i < elementCount; i++) {
      const elemDataOffset = targetOffset + WORD_SIZE + i * elementWords * WORD_SIZE;
      results.push(new StructReader(this.raw, this.buf, elemDataOffset, tagDataWords, tagPtrWords, this.segmentOffsets));
    }
    return results;
  }
}

/** Backwards-compatible alias — prefer CapnpArena for new code. */
export const CapnpMessageBuilder = CapnpArena;
"##.to_owned()
}
