//! TypeScript code generation from parsed Cap'n Proto schemas.
//!
//! Generates:
//! - `capnp.ts`         — Wire format runtime (CapnpMessageBuilder + CapnpReader)
//! - `{service}.ts`     — Per-service interfaces, builders, parsers, clients
//! - `index.ts`         — Re-exports

mod builders;
mod client;
mod interfaces;
mod message;
mod parsers;

use std::path::Path;

use hyprstream_rpc_build::backend::CodegenBackend;
use hyprstream_rpc_build::schema::types::{
    ArmPayload, EnumDef, FieldDef, FieldSection, ParsedSchema, StructDef,
};
use hyprstream_rpc_build::util::{to_camel_case, to_pascal_case};

/// Generate all output files from parsed schemas using the given backend.
#[allow(clippy::print_stdout)]
pub fn generate_all<B: CodegenBackend>(
    backend: &B,
    schemas: &[(String, ParsedSchema)],
    output_dir: &Path,
) {
    // 1. Runtime file (e.g. capnp.ts)
    let (runtime_name, runtime_content) = backend.runtime_file();
    let runtime_path = output_dir.join(&runtime_name);
    std::fs::write(&runtime_path, runtime_content).expect("Failed to write runtime file");
    println!("  Generated {runtime_name}");

    // 2. Per-schema service files
    let mut all_names = Vec::new();
    let mut client_names = Vec::new();
    let mut module_contents = Vec::new();
    for (name, schema) in schemas {
        let content = backend.generate_service_file(name, schema);
        let filename = format!("{name}.{}", backend.file_extension());
        let path = output_dir.join(&filename);
        std::fs::write(&path, &content).expect("Failed to write service file");
        println!("  Generated {filename}");
        all_names.push(name.clone());
        if schema.request_struct.is_some() {
            client_names.push(name.clone());
        }
        module_contents.push((name.clone(), content));
    }

    // 3. Optional index/manifest file
    if let Some((index_name, index_content)) =
        backend.index_file(&all_names, &client_names, &module_contents)
    {
        let index_path = output_dir.join(&index_name);
        std::fs::write(&index_path, index_content).expect("Failed to write index file");
        println!("  Generated {index_name}");
    }
}

/// Generate a single TypeScript file for a schema.
///
/// For service schemas (with request/response structs): generates interfaces,
/// service builders/parsers, client class, plus standalone struct builders/parsers.
/// For data-only schemas: generates interfaces and standalone struct builders/parsers only.
fn generate_service_file(service_name: &str, schema: &ParsedSchema) -> String {
    let mut out = String::with_capacity(8192);

    let is_service = schema.request_struct.is_some();

    // Header
    out.push_str(&format!(
        "// Generated by hyprstream-ts-codegen — DO NOT EDIT\n\
         // {label}: {service_name}\n\n\
         import {{ CapnpArena, CapnpReader }} from './capnp';\n",
        label = if is_service { "Service" } else { "Schema" }
    ));

    // Inline StreamHandle interface (only for service schemas with streaming methods)
    if is_service && client::has_streaming_methods(schema) {
        out.push_str(
            "/** Verified stream handle (duck-type compatible with WASM StreamHandle). */\n\
             export interface StreamHandle {\n\
             \x20 nextPayload(): Promise<Uint8Array | null>;\n\
             \x20 cancel(): Promise<void>;\n\
             \x20 streamId(): string;\n\
             \x20 isCompleted(): boolean;\n\
             \x20 free(): void;\n\
             \x20 [Symbol.dispose](): void;\n\
             }\n\n",
        );
    }
    out.push('\n');

    // Interfaces
    interfaces::generate_interfaces(&mut out, schema);

    // Service builders/parsers (request/response union serialization)
    builders::generate_builders(&mut out, service_name, schema);
    parsers::generate_parsers(&mut out, service_name, schema);

    // Standalone struct builders/parsers (for all union-bearing structs in schema.structs)
    builders::generate_struct_builders(&mut out, schema);
    parsers::generate_struct_parsers(&mut out, schema);

    // Client class (only for service schemas)
    if is_service {
        client::generate_client(&mut out, service_name, schema);
    }

    out
}

// ---------------------------------------------------------------------------
// Shared helpers used by submodules
// ---------------------------------------------------------------------------

/// Map a Cap'n Proto type name to a TypeScript type.
fn capnp_to_ts_type(type_name: &str) -> String {
    match type_name {
        "Void" => "undefined".into(),
        "Bool" => "boolean".into(),
        "UInt8" | "UInt16" | "UInt32" | "Int8" | "Int16" | "Int32" | "Float32" | "Float64" => {
            "number".into()
        }
        "UInt64" | "Int64" => "bigint".into(),
        "Text" => "string".into(),
        "Data" => "Uint8Array".into(),
        _ if type_name.starts_with("List(") => {
            let inner = &type_name[5..type_name.len() - 1];
            format!("{}[]", capnp_to_ts_type(inner))
        }
        _ if type_name.starts_with("Option") => {
            // Option<T> wrapper struct — map to `T | undefined`.
            // Struct names use "Option" + capnp-case suffix (e.g. "OptionUint32", "OptionFloat32").
            // Normalize to the canonical capnp type name before mapping.
            let suffix = &type_name["Option".len()..];
            let normalized = match suffix {
                "Uint8" => "UInt8",
                "Uint16" => "UInt16",
                "Uint32" => "UInt32",
                "Uint64" => "UInt64",
                "Int8" => "Int8",
                "Int16" => "Int16",
                "Int32" => "Int32",
                "Int64" => "Int64",
                other => other,
            };
            format!("{} | undefined", capnp_to_ts_type(normalized))
        }
        _ => type_name.to_owned(),
    }
}

/// Compute the byte offset for a data-section field based on its type and slot_offset.
///
/// Cap'n Proto slot_offset is in units of the type size:
/// - Bool: 1-bit units (byteOff = offset/8, bitIdx = offset%8)
/// - UInt8/Int8: byte units
/// - UInt16/Int16: 2-byte units
/// - UInt32/Int32/Float32: 4-byte units
/// - UInt64/Int64/Float64: 8-byte units
fn data_byte_offset(field: &FieldDef) -> u32 {
    match field.type_name.as_str() {
        "Bool" => field.slot_offset / 8,
        "UInt8" | "Int8" => field.slot_offset,
        "UInt16" | "Int16" => field.slot_offset * 2,
        "UInt32" | "Int32" | "Float32" => field.slot_offset * 4,
        "UInt64" | "Int64" | "Float64" => field.slot_offset * 8,
        _ => {
            // Enum types in data section are stored as UInt16
            if field.section == FieldSection::Data {
                field.slot_offset * 2
            } else {
                field.slot_offset
            }
        }
    }
}

/// Return the bit index for a Bool field.
fn bool_bit_index(field: &FieldDef) -> u32 {
    field.slot_offset % 8
}

/// Return the TypeScript setter method name on `CapnpMessageBuilder` / `StructBuilder`.
///
/// Returns `None` for types that the runtime doesn't support yet (e.g., struct lists).
fn setter_method(type_name: &str) -> Option<&str> {
    Some(match type_name {
        "Bool" => "setBool",
        "UInt8" => "setUint8",
        "UInt16" => "setUint16",
        "UInt32" => "setUint32",
        "UInt64" => "setUint64",
        "Int8" => "setInt8",
        "Int16" => "setInt16",
        "Int32" => "setInt32",
        "Int64" => "setInt64",
        "Float32" => "setFloat32",
        "Float64" => "setFloat64",
        "Text" => "setText",
        "Data" => "setData",
        _ => return None, // List(_), struct pointers, etc. — handled by list_setter_method / struct codegen
    })
}

/// Return the TypeScript setter method name for a `List(<inner>)` field, given
/// the inner element type name (e.g. `"Int64"`, `"Bool"`, `"Text"`, `"Data"`).
///
/// This is the single source of truth for which list element shapes the
/// `capnp.ts` runtime supports as a flat (non-composite-of-structs) list.
/// `None` means the caller must fall through to struct-list codegen (if
/// `inner` names a known struct) — anything else is an unresolved reference
/// and must be treated as a hard generator error, never a silent comment.
pub(crate) fn list_setter_method(inner: &str) -> Option<&str> {
    Some(match inner {
        "Text" => "setTextList",
        "Data" => "setDataList",
        "Bool" => "setBoolList",
        "UInt8" => "setUint8List",
        "Int8" => "setInt8List",
        "UInt16" => "setUint16List",
        "Int16" => "setInt16List",
        "UInt32" => "setUint32List",
        "Int32" => "setInt32List",
        "UInt64" => "setUint64List",
        "Int64" => "setInt64List",
        "Float32" => "setFloat32List",
        "Float64" => "setFloat64List",
        _ => return None,
    })
}

/// Return the TypeScript getter method name for a `List(<inner>)` field.
/// Mirrors [`list_setter_method`] — see its docs.
pub(crate) fn list_getter_method(inner: &str) -> Option<&str> {
    Some(match inner {
        "Text" => "getTextList",
        "Data" => "getDataList",
        "Bool" => "getBoolList",
        "UInt8" => "getUint8List",
        "Int8" => "getInt8List",
        "UInt16" => "getUint16List",
        "Int16" => "getInt16List",
        "UInt32" => "getUint32List",
        "Int32" => "getInt32List",
        "UInt64" => "getUint64List",
        "Int64" => "getInt64List",
        "Float32" => "getFloat32List",
        "Float64" => "getFloat64List",
        _ => return None,
    })
}

/// Return the default TS expression for a Cap'n Proto type (used for optional field coalescing).
fn default_value_expr(type_name: &str) -> &str {
    match type_name {
        "Bool" => "false",
        "UInt8" | "UInt16" | "UInt32" | "Int8" | "Int16" | "Int32" | "Float32" | "Float64" => "0",
        "UInt64" | "Int64" => "0n",
        "Text" => "''",
        "Data" => "new Uint8Array(0)",
        _ if type_name.starts_with("List(") => "[]",
        _ => "undefined",
    }
}

/// Return the TypeScript getter method name on `CapnpReader` / `StructReader`.
fn getter_method(type_name: &str) -> &str {
    match type_name {
        "Bool" => "getBool",
        "UInt8" => "getUint8",
        "UInt16" => "getUint16",
        "UInt32" => "getUint32",
        "UInt64" => "getUint64",
        "Int8" => "getInt8",
        "Int16" => "getInt16",
        "Int32" => "getInt32",
        "Int64" => "getInt64",
        "Float32" => "getFloat32",
        "Float64" => "getFloat64",
        "Text" => "getText",
        "Data" => "getData",
        // Callers only ever reach this function for `is_data_scalar`-narrowed
        // types or a literal Text/Data check — List(_) always resolves through
        // `list_getter_method` at the call site instead. Anything else getting
        // here is a generator bug: fail loudly rather than silently guessing
        // `getText` (the old behavior masked exactly this class of bug — #725).
        other => panic!(
            "ts_codegen: getter_method called with unsupported type `{other}` — this \
             indicates a generator bug in the call site (missing a scalar/Text/Data \
             guard), never silently degrade to a guessed getter (#725)."
        ),
    }
}

/// Check if a capnp type is a simple scalar (data section, not pointer).
pub(crate) fn is_data_scalar(type_name: &str) -> bool {
    matches!(
        type_name,
        "Bool"
            | "UInt8"
            | "UInt16"
            | "UInt32"
            | "UInt64"
            | "Int8"
            | "Int16"
            | "Int32"
            | "Int64"
            | "Float32"
            | "Float64"
    )
}

/// Extract the inner type name from a `List(Foo)` type string. Returns `None` for non-list types.
fn extract_list_inner_type(type_name: &str) -> Option<&str> {
    if type_name.starts_with("List(") && type_name.ends_with(')') {
        Some(&type_name[5..type_name.len() - 1])
    } else {
        None
    }
}

/// Check if a capnp type name is a primitive (not a struct reference).
///
/// Delegates to `is_primitive_capnp_type` in `schema::types` — the canonical
/// implementation shared with the CGR reader.
pub(crate) fn is_primitive(type_name: &str) -> bool {
    hyprstream_rpc_build::schema::types::is_primitive_capnp_type(type_name)
}

/// Map a union-member field to the TypeScript type carried in the `data` slot.
///
/// Mirrors the per-variant `data` expression produced by the parser emitters:
/// - `Void`              → `undefined`
/// - scalars / `Bool`    → the TS scalar (`number` / `bigint` / `boolean`)
/// - `Text`              → `string`
/// - `Data`              → `Uint8Array`
/// - `List(Text)`        → `string[]`
/// - `List(Struct)`      → `Inner[]` (elements are parsed into objects)
/// - `Option*` wrapper   → `T | undefined` (absence is `undefined`, never `null`)
/// - struct              → `TypeName | null` (the parser returns `null` on a null pointer)
///
/// Keeping this aligned with the parser guarantees the typed discriminated union
/// is sound against the runtime values callers actually receive. Shared by both
/// the interface emitter (`interfaces.rs`) and the parser-result type aliases
/// (`parsers.rs`).
pub(crate) fn union_variant_data_type(f: &FieldDef) -> String {
    let tn = f.type_name.as_str();
    if tn == "Void" {
        return "undefined".to_owned();
    }
    if tn.starts_with("List(") {
        // capnp_to_ts_type already maps List(T) → T[].
        return capnp_to_ts_type(tn);
    }
    // `is_primitive` already covers Text/Data (and Void/List); no extra checks.
    if is_primitive(tn) {
        return capnp_to_ts_type(tn);
    }
    // Option* wrapper structs encode absence as `undefined`
    // (capnp_to_ts_type maps `OptionUint32` → `number | undefined`); they live in
    // the pointer section but must NOT get the struct-pointer `| null` suffix.
    if tn.starts_with("Option") {
        return capnp_to_ts_type(tn);
    }
    // Struct (or enum) reference. Struct pointers can be null at runtime; enums
    // are data-section and never null, but the only data-section non-scalar union
    // payloads are enums, which `capnp_to_ts_type` maps to their type name.
    if matches!(f.section, FieldSection::Pointer) {
        format!("{} | null", capnp_to_ts_type(tn))
    } else {
        capnp_to_ts_type(tn)
    }
}

/// If union field `uf` of struct `sd` is an inline `group` arm, return its leaf
/// fields (from the structured `union_arms` view). `None` for Void/single-type
/// arms.
///
/// A capnp `group` arm carries an inlined anonymous struct whose leaf fields are
/// allocated their own slots in the ENCLOSING struct's data/pointer sections;
/// each leaf `FieldDef` therefore already carries a correct `slot_offset` +
/// `section` (extracted by the same `field_def_from_slot` path as a normal
/// field), so build/parse can read/write them directly on the enclosing
/// reader/builder.
pub(crate) fn group_arm_leaves<'a>(sd: &'a StructDef, uf: &FieldDef) -> Option<&'a [FieldDef]> {
    if uf.section != FieldSection::Group {
        return None;
    }
    sd.union_arms
        .iter()
        .find(|a| a.name == uf.name)
        .and_then(|a| match &a.payload {
            ArmPayload::Group(leaves) => Some(leaves.as_slice()),
            _ => None,
        })
}

/// Name of the synthesized TypeScript interface for a group arm, e.g. the
/// `dropOldest` arm of `OverflowPolicy` → `OverflowPolicyDropOldest`.
pub(crate) fn group_arm_type_name(struct_name: &str, arm_name: &str) -> String {
    format!("{struct_name}{}", to_pascal_case(arm_name))
}

/// The `data:` TypeScript type for one arm of struct `sd`'s discriminated union.
///
/// Same as [`union_variant_data_type`] for Void/scalar/struct arms, but a group
/// arm resolves to its synthesized interface (`{Struct}{Arm}` | null) instead of
/// the bare, undefined `Group`. Shared by the interface emitter and the parser
/// result-type aliases so type/build/parse agree.
pub(crate) fn union_arm_data_type(sd: &StructDef, f: &FieldDef) -> String {
    if group_arm_leaves(sd, f).is_some() {
        format!("{} | null", group_arm_type_name(&sd.name, &f.name))
    } else {
        union_variant_data_type(f)
    }
}

/// Build a TypeScript array literal from an enum's variants (camelCase names as strings).
///
/// Example output: `['active', 'inactive', 'pending']`
fn enum_ordinal_array(ed: &EnumDef) -> String {
    let variants: Vec<String> = ed
        .variants
        .iter()
        .map(|(name, _)| format!("'{}'", to_camel_case(name)))
        .collect();
    format!("[{}]", variants.join(", "))
}

/// Emit a `setUint16` call that converts a TypeScript string enum to its wire ordinal.
///
/// Generates: `{indent}{builder_var}.setUint16({byte_off}, [...].indexOf({value_expr}));`
pub(crate) fn emit_enum_setter(
    out: &mut String,
    indent: &str,
    builder_var: &str,
    byte_off: u32,
    value_expr: &str,
    ed: &EnumDef,
) {
    out.push_str(&format!(
        "{indent}{builder_var}.setUint16({byte_off}, {}.indexOf({value_expr}));\n",
        enum_ordinal_array(ed)
    ));
}

/// Return a TypeScript expression that reads a UInt16 ordinal and maps it to a string enum.
///
/// Example output: `(['active', 'inactive'][reader.getUint16(4)] ?? 'unknown') as Status`
pub(crate) fn emit_enum_getter_expr(
    reader_var: &str,
    byte_off: u32,
    type_name: &str,
    ed: &EnumDef,
) -> String {
    format!(
        "({}[{reader_var}.getUint16({byte_off})] ?? 'unknown') as {type_name}",
        enum_ordinal_array(ed)
    )
}

// ---------------------------------------------------------------------------
// TypeScript backend
// ---------------------------------------------------------------------------

/// TypeScript code generation backend.
///
/// Wraps the existing TypeScript emitters and implements the language-agnostic
/// `CodegenBackend` trait, enabling `generate_all` to be called generically.
pub struct TypeScriptBackend;

impl CodegenBackend for TypeScriptBackend {
    fn map_type(&self, capnp_type: &str) -> String {
        capnp_to_ts_type(capnp_type)
    }

    fn setter_method(&self, type_name: &str) -> Option<String> {
        setter_method(type_name).map(str::to_owned)
    }

    fn getter_expr(&self, reader_var: &str, field: &FieldDef) -> String {
        // Simplified expression for the trait surface.
        // Full dispatch (enums, structs, lists) is handled by the emitter functions.
        let method = getter_method(&field.type_name);
        format!("{reader_var}.{method}({})", field.slot_offset)
    }

    fn default_value(&self, type_name: &str) -> String {
        default_value_expr(type_name).to_owned()
    }

    fn generate_service_file(&self, service_name: &str, schema: &ParsedSchema) -> String {
        generate_service_file(service_name, schema)
    }

    fn runtime_file(&self) -> (String, String) {
        ("capnp.ts".to_owned(), message::generate_capnp_runtime())
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn index_file(
        &self,
        all_names: &[String],
        client_names: &[String],
        module_contents: &[(String, String)],
    ) -> Option<(String, String)> {
        Some((
            "index.ts".to_owned(),
            generate_index(all_names, client_names, module_contents),
        ))
    }
}

/// Scan the literal top-level exported symbol names out of generated TS source.
///
/// This is the single source of truth for "what does this module export": it
/// reads the text that was actually emitted (`export interface X`, `export type
/// X`, `export function X`) rather than independently re-deriving struct/enum/
/// function naming rules, so it can never drift from what `interfaces.rs` /
/// `builders.rs` / `parsers.rs` actually produce.
fn scan_exported_names(content: &str) -> Vec<String> {
    const PREFIXES: &[&str] = &["export interface ", "export type ", "export function "];
    let mut names = Vec::new();
    for line in content.lines() {
        let line = line.trim_start();
        for prefix in PREFIXES {
            if let Some(rest) = line.strip_prefix(prefix) {
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect();
                if !name.is_empty() {
                    names.push(name);
                }
                break;
            }
        }
    }
    names
}

/// Generate index.ts with re-exports.
///
/// For service schemas: re-exports `{Pascal}Client` class.
/// For data-only schemas: re-exports all exported symbols (standalone builders/parsers).
/// Does not use `export type *` for service schemas since different services
/// may share type names (e.g., ErrorInfo, StreamInfo) which causes TS2308 conflicts.
///
/// Data-only modules are barrel-exported with a plain `export * from './name'`
/// UNLESS one of their exported names also appears in another data-only
/// module — in that case every data-only module sharing the name switches to
/// an explicit `export { ... }` list with the colliding names aliased as
/// `{PascalModuleName}{Name}`, so two modules can never silently shadow one
/// another's export (#725) and a full regen never leaves an ambiguous name
/// for tsc to reject.
fn generate_index(
    all_names: &[String],
    client_names: &[String],
    module_contents: &[(String, String)],
) -> String {
    // Exported names per data-only module (services only ever barrel-export
    // their Client class, so they can't collide with each other here).
    let data_only_exports: Vec<(&String, Vec<String>)> = all_names
        .iter()
        .filter(|name| !client_names.contains(name))
        .map(|name| {
            let content = module_contents
                .iter()
                .find(|(n, _)| n == name)
                .map(|(_, c)| c.as_str())
                .unwrap_or_default();
            (name, scan_exported_names(content))
        })
        .collect();

    // name -> number of data-only modules that export it
    let mut occurrence_count: std::collections::HashMap<&str, usize> =
        std::collections::HashMap::new();
    for (_, names) in &data_only_exports {
        for n in names {
            *occurrence_count.entry(n.as_str()).or_insert(0) += 1;
        }
    }

    let mut out = String::from("// Generated by hyprstream-ts-codegen — DO NOT EDIT\n\n");
    out.push_str("export { CapnpArena, CapnpReader } from './capnp';\n");
    for name in all_names {
        if client_names.contains(name) {
            let pascal = to_pascal_case(name);
            out.push_str(&format!("export {{ {pascal}Client }} from './{name}';\n"));
            continue;
        }

        let exported = data_only_exports
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, names)| names.as_slice())
            .unwrap_or_default();
        let has_collision = exported
            .iter()
            .any(|n| occurrence_count.get(n.as_str()).copied().unwrap_or(0) > 1);

        if !has_collision {
            // No cross-module name collision — a plain wildcard re-export is safe.
            out.push_str(&format!("export * from './{name}';\n"));
            continue;
        }

        // At least one export from this module collides with another
        // data-only module's export — enumerate every export explicitly,
        // aliasing only the colliding ones, so tsc never sees an ambiguous
        // wildcard re-export.
        let module_prefix = to_pascal_case(name);
        let items: Vec<String> = exported
            .iter()
            .map(|n| {
                if occurrence_count.get(n.as_str()).copied().unwrap_or(0) > 1 {
                    format!("{n} as {module_prefix}{n}")
                } else {
                    n.clone()
                }
            })
            .collect();
        if items.is_empty() {
            // Nothing exported from this module (e.g. an empty schema) — no-op.
            continue;
        }
        out.push_str(&format!(
            "export {{ {} }} from './{name}';\n",
            items.join(", ")
        ));
    }
    out
}

#[cfg(test)]
mod barrel_tests {
    #![allow(clippy::expect_used, clippy::unwrap_used)]

    use super::generate_index;

    /// Two data-only modules that don't share any exported name keep the
    /// cheap, plain `export *` re-export.
    #[test]
    fn no_collision_uses_plain_wildcard_export() {
        let all_names = vec!["events".to_owned(), "streaming".to_owned()];
        let client_names: Vec<String> = vec![];
        let module_contents = vec![
            (
                "events".to_owned(),
                "export interface EventEnvelope {\n  id: string;\n}\n".to_owned(),
            ),
            (
                "streaming".to_owned(),
                "export interface StreamInfo {\n  id: string;\n}\n".to_owned(),
            ),
        ];

        let out = generate_index(&all_names, &client_names, &module_contents);

        assert!(out.contains("export * from './events';"), "{out}");
        assert!(out.contains("export * from './streaming';"), "{out}");
    }

    /// Two data-only modules that both export a struct with the same name (the
    /// #725 "QoS" scenario) must never both emit a blind `export *` — every
    /// module owning the colliding name switches to an explicit, aliased
    /// export so tsc can never see an ambiguous re-export.
    #[test]
    fn colliding_export_name_is_aliased_per_module_not_silently_dropped() {
        let all_names = vec!["events".to_owned(), "streaming".to_owned()];
        let client_names: Vec<String> = vec![];
        let module_contents = vec![
            (
                "events".to_owned(),
                "export interface QoS {\n  retries: number;\n}\n\
                 export interface EventEnvelope {\n  id: string;\n}\n"
                    .to_owned(),
            ),
            (
                "streaming".to_owned(),
                "export interface QoS {\n  ackTimeoutMs: number;\n}\n\
                 export interface StreamInfo {\n  id: string;\n}\n"
                    .to_owned(),
            ),
        ];

        let out = generate_index(&all_names, &client_names, &module_contents);

        // Neither module may fall back to a blind wildcard export — that's
        // exactly the silent-collision failure mode #725 reported.
        assert!(!out.contains("export * from './events';"), "{out}");
        assert!(!out.contains("export * from './streaming';"), "{out}");

        // The colliding name is aliased per-module...
        assert!(out.contains("QoS as EventsQoS"), "{out}");
        assert!(out.contains("QoS as StreamingQoS"), "{out}");
        // ...while the non-colliding names from each module are still
        // re-exported (nothing gets dropped just because its sibling collided).
        assert!(out.contains("EventEnvelope"), "{out}");
        assert!(out.contains("StreamInfo"), "{out}");
    }

    /// `scan_exported_names` is the single source of truth the barrel
    /// generator relies on — verify it picks up every emission shape used by
    /// interfaces.rs / builders.rs / parsers.rs.
    #[test]
    fn scan_exported_names_finds_interfaces_types_and_functions() {
        let content = "export interface Foo {\n  a: number;\n}\n\
                        export type Bar =\n  | { variant: 'x'; data: undefined };\n\
                        export function buildFoo(p: Foo): Uint8Array {\n  return new Uint8Array(0);\n}\n";
        let names = super::scan_exported_names(content);
        assert_eq!(names, vec!["Foo", "Bar", "buildFoo"]);
    }
}
