//! TypeScript code generation from parsed Cap'n Proto schemas.
//!
//! Generates:
//! - `capnp.ts`         — Wire format runtime (CapnpMessageBuilder + CapnpReader)
//! - `{service}.ts`     — Per-service interfaces, builders, parsers, clients
//! - `index.ts`         — Re-exports

mod message;
mod interfaces;
mod builders;
mod parsers;
mod client;

use std::path::Path;

use hyprstream_rpc_build::schema::types::{FieldDef, FieldSection, ParsedSchema};
use hyprstream_rpc_build::util::to_pascal_case;

/// Generate all TypeScript files from parsed schemas.
#[allow(clippy::print_stdout)]
pub fn generate_all(schemas: &[(String, ParsedSchema)], output_dir: &Path) {
    // 1. Generate capnp.ts runtime (shared across all services)
    let capnp_ts = message::generate_capnp_runtime();
    let capnp_path = output_dir.join("capnp.ts");
    std::fs::write(&capnp_path, capnp_ts).expect("Failed to write capnp.ts");
    println!("  Generated capnp.ts");

    // 2. Generate per-service files
    let mut service_names = Vec::new();
    for (name, schema) in schemas {
        let ts = generate_service_file(name, schema);
        let filename = format!("{name}.ts");
        let path = output_dir.join(&filename);
        std::fs::write(&path, ts).expect("Failed to write service file");
        println!("  Generated {filename}");
        service_names.push(name.clone());
    }

    // 3. Generate index.ts with re-exports
    let index_ts = generate_index(&service_names);
    let index_path = output_dir.join("index.ts");
    std::fs::write(&index_path, index_ts).expect("Failed to write index.ts");
    println!("  Generated index.ts");
}

/// Generate a single service TypeScript file.
fn generate_service_file(service_name: &str, schema: &ParsedSchema) -> String {
    let mut out = String::with_capacity(8192);

    // Header
    out.push_str(&format!(
        "// Generated by hyprstream-ts-codegen — DO NOT EDIT\n\
         // Service: {service_name}\n\n\
         import {{ CapnpMessageBuilder, CapnpReader }} from './capnp';\n"
    ));

    // Conditional streaming import
    if client::has_streaming_methods(schema) {
        out.push_str(
            "import { type StreamSubscription, createStreamSubscription } from '../stream-client';\n"
        );
    }
    out.push('\n');

    // Interfaces
    interfaces::generate_interfaces(&mut out, schema);

    // Builders (request serialization)
    builders::generate_builders(&mut out, service_name, schema);

    // Parsers (response deserialization)
    parsers::generate_parsers(&mut out, service_name, schema);

    // Client class
    client::generate_client(&mut out, service_name, schema);

    out
}

// ---------------------------------------------------------------------------
// Shared helpers used by submodules
// ---------------------------------------------------------------------------

/// Map a Cap'n Proto type name to a TypeScript type.
fn capnp_to_ts_type(type_name: &str) -> String {
    match type_name {
        "Void" => "undefined".into(),
        "Bool" => "boolean".into(),
        "UInt8" | "UInt16" | "UInt32" | "Int8" | "Int16" | "Int32" | "Float32" | "Float64" => {
            "number".into()
        }
        "UInt64" | "Int64" => "bigint".into(),
        "Text" => "string".into(),
        "Data" => "Uint8Array".into(),
        _ if type_name.starts_with("List(") => {
            let inner = &type_name[5..type_name.len() - 1];
            format!("{}[]", capnp_to_ts_type(inner))
        }
        _ if type_name.starts_with("Option") => {
            // Option<T> wrapper struct — map to `T | undefined`.
            // Struct names use "Option" + capnp-case suffix (e.g. "OptionUint32", "OptionFloat32").
            // Normalize to the canonical capnp type name before mapping.
            let suffix = &type_name["Option".len()..];
            let normalized = match suffix {
                "Uint8"  => "UInt8",  "Uint16" => "UInt16",
                "Uint32" => "UInt32", "Uint64" => "UInt64",
                "Int8"   => "Int8",   "Int16"  => "Int16",
                "Int32"  => "Int32",  "Int64"  => "Int64",
                other    => other,
            };
            format!("{} | undefined", capnp_to_ts_type(normalized))
        }
        _ => type_name.to_owned(),
    }
}

/// Compute the byte offset for a data-section field based on its type and slot_offset.
///
/// Cap'n Proto slot_offset is in units of the type size:
/// - Bool: 1-bit units (byteOff = offset/8, bitIdx = offset%8)
/// - UInt8/Int8: byte units
/// - UInt16/Int16: 2-byte units
/// - UInt32/Int32/Float32: 4-byte units
/// - UInt64/Int64/Float64: 8-byte units
fn data_byte_offset(field: &FieldDef) -> u32 {
    match field.type_name.as_str() {
        "Bool" => field.slot_offset / 8,
        "UInt8" | "Int8" => field.slot_offset,
        "UInt16" | "Int16" => field.slot_offset * 2,
        "UInt32" | "Int32" | "Float32" => field.slot_offset * 4,
        "UInt64" | "Int64" | "Float64" => field.slot_offset * 8,
        _ => {
            // Enum types in data section are stored as UInt16
            if field.section == FieldSection::Data {
                field.slot_offset * 2
            } else {
                field.slot_offset
            }
        }
    }
}

/// Return the bit index for a Bool field.
fn bool_bit_index(field: &FieldDef) -> u32 {
    field.slot_offset % 8
}

/// Return the TypeScript setter method name on `CapnpMessageBuilder` / `StructBuilder`.
///
/// Returns `None` for types that the runtime doesn't support yet (e.g., struct lists).
fn setter_method(type_name: &str) -> Option<&str> {
    Some(match type_name {
        "Bool" => "setBool",
        "UInt8" => "setUint8",
        "UInt16" => "setUint16",
        "UInt32" => "setUint32",
        "UInt64" => "setUint64",
        "Int8" => "setInt8",
        "Int16" => "setInt16",
        "Int32" => "setInt32",
        "Int64" => "setInt64",
        "Float32" => "setFloat32",
        "Float64" => "setFloat64",
        "Text" => "setText",
        "Data" => "setData",
        _ if type_name.starts_with("List(Text") => "setTextList",
        _ => return None, // struct lists, nested structs, etc. not supported yet
    })
}

/// Return the default TS expression for a Cap'n Proto type (used for optional field coalescing).
fn default_value_expr(type_name: &str) -> &str {
    match type_name {
        "Bool" => "false",
        "UInt8" | "UInt16" | "UInt32" | "Int8" | "Int16" | "Int32" | "Float32" | "Float64" => "0",
        "UInt64" | "Int64" => "0n",
        "Text" => "''",
        "Data" => "new Uint8Array(0)",
        _ if type_name.starts_with("List(") => "[]",
        _ => "undefined",
    }
}

/// Return the TypeScript getter method name on `CapnpReader` / `StructReader`.
fn getter_method(type_name: &str) -> &str {
    match type_name {
        "Bool" => "getBool",
        "UInt8" => "getUint8",
        "UInt16" => "getUint16",
        "UInt32" => "getUint32",
        "UInt64" => "getUint64",
        "Int8" => "getInt8",
        "Int16" => "getInt16",
        "Int32" => "getInt32",
        "Int64" => "getInt64",
        "Float32" => "getFloat32",
        "Float64" => "getFloat64",
        "Text" => "getText",
        "Data" => "getData",
        _ if type_name.starts_with("List(Text") => "getTextList",
        _ if type_name.starts_with("List(Data") => "getDataList",
        _ => "getText",
    }
}

/// Check if a capnp type is a simple scalar (data section, not pointer).
pub(crate) fn is_data_scalar(type_name: &str) -> bool {
    matches!(
        type_name,
        "Bool"
            | "UInt8"
            | "UInt16"
            | "UInt32"
            | "UInt64"
            | "Int8"
            | "Int16"
            | "Int32"
            | "Int64"
            | "Float32"
            | "Float64"
    )
}

/// Extract the inner type name from a `List(Foo)` type string. Returns `None` for non-list types.
fn extract_list_inner_type(type_name: &str) -> Option<&str> {
    if type_name.starts_with("List(") && type_name.ends_with(')') {
        Some(&type_name[5..type_name.len() - 1])
    } else {
        None
    }
}

/// Check if a capnp type name is a primitive (not a struct reference).
fn is_primitive(type_name: &str) -> bool {
    matches!(
        type_name,
        "Void"
            | "Bool"
            | "Text"
            | "Data"
            | "UInt8"
            | "UInt16"
            | "UInt32"
            | "UInt64"
            | "Int8"
            | "Int16"
            | "Int32"
            | "Int64"
            | "Float32"
            | "Float64"
    ) || type_name.starts_with("List(")
}

/// Generate index.ts with re-exports.
///
/// Only re-exports client classes — not `export type *` since different services
/// may share type names (e.g., ErrorInfo, StreamInfo) which causes TS2308 conflicts.
/// Consumers should import types directly from the service modules.
fn generate_index(service_names: &[String]) -> String {
    let mut out = String::from("// Generated by hyprstream-ts-codegen — DO NOT EDIT\n\n");
    out.push_str("export { CapnpMessageBuilder, CapnpReader } from './capnp';\n");
    for name in service_names {
        let pascal = to_pascal_case(name);
        out.push_str(&format!(
            "export {{ {pascal}Client }} from './{name}';\n"
        ));
    }
    out
}
