#!/usr/bin/env python3
"""Generate the canonical proof-v1 test vectors for the Hyprstream v16 COSE
request-proof profile.

This generator is the reproducible source of `../vectors/*.json`. It is a
specification artifact, not production code: it implements only the subset of
RFC 8949 core deterministic encoding and RFC 9052 structures that the profile
uses, so that the checked-in vectors can be regenerated byte-for-byte and
diffed during review.

Requirements:
  * Python 3.11+ with `cryptography` (Ed25519 signing).
  * OpenSSL 3.5+ on PATH with ML-DSA-65 support, seeded key generation
    (`-pkeyopt hexseed:`) and deterministic signing (`-pkeyopt deterministic:1`).

Every key in this file is derived from a published constant seed. These are
test keys. They MUST NOT be enrolled, trusted, or used for any purpose other
than checking a verifier against these vectors.

Usage:  python3 gen_proof_vectors.py [output_dir]
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

# --------------------------------------------------------------------------
# Deterministic CBOR (RFC 8949 §4.2.1 core deterministic encoding)
# --------------------------------------------------------------------------


class Raw:
    """Pre-encoded CBOR bytes, spliced in verbatim (used by negative vectors
    that deliberately violate deterministic encoding)."""

    def __init__(self, data: bytes):
        self.data = data


def _head(major: int, value: int) -> bytes:
    if value < 24:
        return bytes([(major << 5) | value])
    if value < 0x100:
        return bytes([(major << 5) | 24, value])
    if value < 0x10000:
        return bytes([(major << 5) | 25]) + value.to_bytes(2, "big")
    if value < 0x100000000:
        return bytes([(major << 5) | 26]) + value.to_bytes(4, "big")
    if value < 0x10000000000000000:
        return bytes([(major << 5) | 27]) + value.to_bytes(8, "big")
    raise ValueError("integer out of CBOR range")


def enc(obj) -> bytes:
    if isinstance(obj, Raw):
        return obj.data
    if obj is None:
        return b"\xf6"
    if obj is True:
        return b"\xf5"
    if obj is False:
        return b"\xf4"
    if isinstance(obj, int):
        if obj >= 0:
            return _head(0, obj)
        return _head(1, -1 - obj)
    if isinstance(obj, bytes):
        return _head(2, len(obj)) + obj
    if isinstance(obj, str):
        b = obj.encode("utf-8")
        return _head(3, len(b)) + b
    if isinstance(obj, list):
        out = _head(4, len(obj))
        for item in obj:
            out += enc(item)
        return out
    if isinstance(obj, dict):
        items = [(enc(k), enc(v)) for k, v in obj.items()]
        # Core deterministic encoding: map keys sorted bytewise-lexicographic
        # on their encoded form.
        items.sort(key=lambda kv: kv[0])
        out = _head(5, len(items))
        for k, v in items:
            out += k + v
        return out
    raise TypeError(f"unsupported type for deterministic CBOR: {type(obj)!r}")


def enc_unsorted(d: dict) -> bytes:
    """Encode a map in caller-declared order (deterministic-encoding
    violation used by a negative vector)."""
    out = _head(5, len(d))
    for k, v in d.items():
        out += enc(k) + enc(v)
    return out


def enc_indefinite_map(d: dict) -> bytes:
    out = b"\xbf"
    for k, v in d.items():
        out += enc(k) + enc(v)
    return out + b"\xff"


# --------------------------------------------------------------------------
# Profile constants (see ../hyprstream-proof-cwt.cddl)
# --------------------------------------------------------------------------

TYP_REQUEST = "application/vnd.hyprstream.proof+cwt"
TYP_RESPONSE = "application/vnd.hyprstream.response-proof+cwt"
DOMAIN_REQUEST = "hs-rpc-request-proof-v1"
DOMAIN_RESPONSE = "hs-rpc-response-proof-v1"

SUITE_CLASSICAL = "hs-cose-sign-ed25519-v1"
SUITE_HYBRID = "hs-cose-sign-ed25519-mldsa65-wns-v1"

ALG_ED25519 = -19
ALG_EDDSA_DEPRECATED = -8
ALG_ML_DSA_65 = -49
# Project-private ML-KEM-768 identifier hs-kem-ml-kem-768-v1 (Gate-2 §19 #5).
ALG_HS_KEM_ML_KEM_768 = -70200

# Orthogonal response-binding axes (Gate-2 §19 #4).
KIND_UNARY, KIND_STREAM_SETUP = 1, 2
PROTECTION_CLEARTEXT, PROTECTION_ENCRYPTED = 1, 2

# A deliberately-unallocated private-use CWT claim key, used only by the
# unknown-claim-key negative. It is in no allocated block (see the registry).
UNKNOWN_CLAIM_KEY = -70050

H_ALG, H_CRIT, H_KID, H_TYP = 1, 2, 4, 16
H_DOMAIN, H_PLAN, H_GROUP, H_KEYSET = -70100, -70101, -70102, -70103

C_AUD, C_EXP, C_IAT, C_CTI, C_NONCE = 3, 4, 6, 7, 10
C_CREDENTIAL_HASH, C_SCHEMA_ID, C_BODY_BYTES, C_RESPONSE_BINDING = (
    -70001,
    -70002,
    -70003,
    -70004,
)

CRIT_SIGN_BODY_AUTH = [H_PLAN, H_DOMAIN]
CRIT_SIGN_BODY_UNATTRIBUTED = [H_KEYSET, H_PLAN, H_DOMAIN]
CRIT_SIGN_SIGNATURE = [H_GROUP]
CRIT_SIGN1_AUTH = [H_GROUP, H_PLAN, H_DOMAIN]
CRIT_SIGN1_UNATTRIBUTED = [H_KEYSET, H_GROUP, H_PLAN, H_DOMAIN]

EXTERNAL_AAD = b""

# Non-normative fixture values.
SERVICE_DOMAIN = "registry.svc.hyprstream.test"
SCHEMA_ID_REQUEST = 0xD4D0F2A1B3C58E67
SCHEMA_ID_RESPONSE = 0x91B7C0E5A2F3D48A
IAT = 1786000000
EXP = 1786000030
REQUEST_ID = bytes.fromhex("3f1c9a04b7d2416e8c05a9137b6e2d80")
CHALLENGE = bytes.fromhex("8ad3011f4c76b25e90c4713f5a26ee08")
CAPNP_REQUEST_BYTES = bytes.fromhex(
    "0000000000000000010000001700000001000500000000000000"
)
CAPNP_RESPONSE_BYTES = bytes.fromhex(
    "0000000000000000010000000f000000020003000000000000"
)
# F2: the authenticated positives hash a REAL, deterministic, profile-valid
# at+jwt access token signed by the seeded credential-issuer Ed25519 key. The
# tokens are built inside main() (they need the seeded keys); CREDENTIAL_HASH
# (classical primary) and CREDENTIAL_HASH_HYBRID are bound there. No placeholder.
# F1: dispositions are evaluated at this exact instant, injected by a conformance
# runner instead of wall clock. iat=1786000000 <= verifier_now < exp=1786000030.
VERIFIER_NOW = 1786000015
ISSUER_ISS = "https://issuer.hyprstream.test"
# RFC 9068 §2.2.1 requires `client_id` in an at+jwt access token: the OAuth client
# the token was issued to. JWT-only (the CWT credential N-1 is not an RFC 9068 JWT).
CREDENTIAL_CLIENT_ID = "hyprstream-oauth-client-1"
CREDENTIAL_SUBJECT = "user-1"
CREDENTIAL_TENANT = "tenant-alpha"           # JWT text name for the -70005 tenant claim
# K1: an OIDC user session (§3.2). The authoritative session expiry lives in the
# authority's session state keyed by (iss, sid) — NOT on the credential wire. It is
# EARLIER than the credential expiry (1786000030) but still after verifier_now
# (1786000015), so the session is active yet a longer-lived proof outlives it.
SESSION_ID = "sess-6b1e0a7c9d2f4a08"
SESSION_EXP = 1786000020
CREDENTIAL_CLEARANCE = [2, [5, 7]]           # [level, compartments]; -70006 (JWT text: clearance)
ML_KEM_768_RECIPIENT = bytes(range(256)) * 4 + bytes(range(160))  # 1184 bytes


def b64u(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode("ascii")


def signer_suite_thumbprint(suite_id: str, pubkeys: list) -> bytes:
    """The cnf-resolved signer-suite record (credential-profile §5): SHA-256 over
    the RFC 8949 deterministic encoding of [suite_id, [ordered raw component
    public keys]]. Uniformly covers a classical (1-key) and a hybrid (2-key)
    primary group. Distinct from the C1 replay thumbprint (no domain separator,
    no enrollment epoch): this binds key material, replay binds the enrollment."""
    return hashlib.sha256(enc([suite_id, list(pubkeys)])).digest()


# --------------------------------------------------------------------------
# Test keys (all seeded from published constants)
# --------------------------------------------------------------------------


def ed25519_key(seed_byte: int):
    seed = bytes((seed_byte + i) & 0xFF for i in range(32))
    sk = Ed25519PrivateKey.from_private_bytes(seed)
    return seed, sk


class MlDsaKey:
    def __init__(self, seed: bytes, workdir: Path, name: str):
        self.seed = seed
        self.path = workdir / f"{name}.pem"
        subprocess.run(
            [
                "openssl",
                "genpkey",
                "-algorithm",
                "ML-DSA-65",
                "-pkeyopt",
                f"hexseed:{seed.hex()}",
                "-out",
                str(self.path),
            ],
            check=True,
            capture_output=True,
        )
        der = subprocess.run(
            ["openssl", "pkey", "-in", str(self.path), "-pubout", "-outform", "DER"],
            check=True,
            capture_output=True,
        ).stdout
        self.public = der[-1952:]

    def sign(self, message: bytes) -> bytes:
        with tempfile.NamedTemporaryFile(delete=False) as f:
            f.write(message)
            msg_path = f.name
        try:
            return subprocess.run(
                [
                    "openssl",
                    "pkeyutl",
                    "-sign",
                    "-inkey",
                    str(self.path),
                    "-rawin",
                    "-in",
                    msg_path,
                    "-pkeyopt",
                    "deterministic:1",
                ],
                check=True,
                capture_output=True,
            ).stdout
        finally:
            os.unlink(msg_path)


KID_CLIENT_ED = b"client-ed25519-1"
KID_CLIENT_ML = b"client-mldsa65-1"
KID_APPROVER_ED = b"approver-ed25519-1"
KID_SERVICE_ED = b"service-ed25519-1"
KID_UNATTRIBUTED_ED = b"unattributed-ed25519-1"
KID_UNATTRIBUTED_ML = b"unattributed-mldsa65-1"
KID_ISSUER_ED = b"issuer-ed25519-1"  # credential issuer (type-confusion vectors)


# --------------------------------------------------------------------------
# Structure builders
# --------------------------------------------------------------------------


def component(alg: int, kid: bytes) -> dict:
    return {1: alg, 2: kid}


def group(group_id: int, suite: str, components: list) -> dict:
    return {1: group_id, 2: suite, 3: components}


def cose_key_okp_ed25519(kid: bytes, public: bytes) -> dict:
    # kty=OKP(1), kid(2), alg=Ed25519(-19), crv=Ed25519(6), x=public
    return {1: 1, 2: kid, 3: ALG_ED25519, -1: 6, -2: public}


def cose_key_akp_mldsa65(kid: bytes, public: bytes) -> dict:
    # kty=AKP(7), kid(2), alg=ML-DSA-65(-49), pub(-1)
    return {1: 7, 2: kid, 3: ALG_ML_DSA_65, -1: public}


def request_claims(
    *,
    credential_hash,
    nonce=None,
    response_binding=None,
    aud=SERVICE_DOMAIN,
    cti=REQUEST_ID,
    schema_id=SCHEMA_ID_REQUEST,
    body=CAPNP_REQUEST_BYTES,
    extra=None,
) -> dict:
    claims = {
        C_AUD: aud,
        C_EXP: EXP,
        C_IAT: IAT,
        C_CTI: cti,
        C_CREDENTIAL_HASH: credential_hash,
        C_SCHEMA_ID: schema_id,
        C_BODY_BYTES: body,
        C_RESPONSE_BINDING: response_binding,
    }
    if nonce is not None:
        claims[C_NONCE] = nonce
    if extra:
        claims.update(extra)
    return claims


def response_binding(kind: int, protection: int, kem=None) -> dict:
    # Frozen 4-key closed map (Gate-2 §19 #3/#4): root type id, orthogonal
    # response_kind and protection_mode axes, and the KEM recipient (non-null
    # iff protection_mode is encrypted).
    return {1: SCHEMA_ID_RESPONSE, 2: kind, 3: protection, 4: kem}


def kem_recipient() -> dict:
    # The alg slot carries the profile's frozen project-private ML-KEM-768
    # identifier -70200 (Gate-2 §19 #5). The exact value is REQUIRED.
    return {1: ALG_HS_KEM_ML_KEM_768, 2: ML_KEM_768_RECIPIENT, 3: b"service-mlkem768-1"}


def sig_structure_sign1(body_protected: bytes, payload: bytes) -> bytes:
    return enc(["Signature1", body_protected, EXTERNAL_AAD, payload])


def sig_structure_sign(
    body_protected: bytes, signer_protected: bytes, payload: bytes
) -> bytes:
    return enc(
        ["Signature", body_protected, signer_protected, EXTERNAL_AAD, payload]
    )


# --------------------------------------------------------------------------
# Vector assembly
# --------------------------------------------------------------------------


def main() -> None:
    out_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "vectors"
    out_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        seed_c_ed, sk_c_ed = ed25519_key(0x00)
        seed_a_ed, sk_a_ed = ed25519_key(0x40)
        seed_s_ed, sk_s_ed = ed25519_key(0x60)
        seed_u_ed, sk_u_ed = ed25519_key(0x80)
        seed_i_ed, sk_i_ed = ed25519_key(0xC0)  # credential issuer
        ml_client = MlDsaKey(bytes((0x20 + i) & 0xFF for i in range(32)), work, "client")
        ml_unattributed = MlDsaKey(
            bytes((0xA0 + i) & 0xFF for i in range(32)), work, "unattributed"
        )

        # ---- F2: deterministic profile-valid at+jwt credential context --------
        issuer_pub = sk_i_ed.public_key().public_bytes_raw()
        client_ed_pub = sk_c_ed.public_key().public_bytes_raw()
        # cnf-resolved signer-suite records for the authenticated positives'
        # PRIMARY groups: classical = [client Ed25519]; hybrid = [client Ed25519,
        # client ML-DSA-65] (approver groups bind their own enrollment, never cnf).
        cnf_classical = signer_suite_thumbprint(SUITE_CLASSICAL, [client_ed_pub])
        cnf_hybrid = signer_suite_thumbprint(SUITE_HYBRID, [client_ed_pub, ml_client.public])

        def build_at_jwt(jti: str, cnf_thumbprint: bytes, *, sid: str = None):
            """A compact JWS (RFC 7519/8725) access token: exact at+jwt header,
            EdDSA over the seeded issuer key, and every required v16
            authenticated-dispatch claim. Ed25519 + canonical JSON => byte-stable.
            A user-session credential also carries the OIDC `sid` (§3.2)."""
            header = {"alg": "EdDSA", "kid": KID_ISSUER_ED.decode(), "typ": "at+jwt"}
            claims = {
                "iss": ISSUER_ISS,
                "sub": CREDENTIAL_SUBJECT,
                "aud": SERVICE_DOMAIN,
                "iat": IAT,
                "exp": EXP,
                "jti": jti,
                "client_id": CREDENTIAL_CLIENT_ID,
                "tenant": CREDENTIAL_TENANT,
                "clearance": CREDENTIAL_CLEARANCE,
                "cnf": {"hs_signer_suite": b64u(cnf_thumbprint)},
            }
            if sid is not None:
                claims["sid"] = sid
            hp = b64u(json.dumps(header, separators=(",", ":"), sort_keys=True).encode())
            pp = b64u(json.dumps(claims, separators=(",", ":"), sort_keys=True).encode())
            signing_input = f"{hp}.{pp}".encode("ascii")
            sig = sk_i_ed.sign(signing_input)
            token = f"{hp}.{pp}.{b64u(sig)}"
            return token, header, claims

        cred_classical, hdr_classical, claims_classical = build_at_jwt("cred-classical-1", cnf_classical)
        cred_hybrid, hdr_hybrid, claims_hybrid = build_at_jwt("cred-hybrid-1", cnf_hybrid)
        # K1: a user-session at+jwt credential carrying OIDC `sid`; its authoritative
        # session record (below) has an EARLIER expiry than the credential, so a proof
        # can be within the credential bound yet outlive the session.
        cred_session, hdr_session, claims_session = build_at_jwt(
            "cred-session-1", cnf_classical, sid=SESSION_ID)
        CREDENTIAL_HASH = hashlib.sha256(cred_classical.encode("ascii")).digest()
        CREDENTIAL_HASH_HYBRID = hashlib.sha256(cred_hybrid.encode("ascii")).digest()
        CREDENTIAL_HASH_SESSION = hashlib.sha256(cred_session.encode("ascii")).digest()

        keys_doc = {
            "warning": (
                "TEST KEYS ONLY. Every key below is derived from a published "
                "constant seed and MUST NOT be enrolled or trusted."
            ),
            "ed25519": [
                {
                    "role": "authenticated primary signer (credential cnf-bound)",
                    "kid_hex": KID_CLIENT_ED.hex(),
                    "kid_ascii": KID_CLIENT_ED.decode(),
                    "seed_hex": seed_c_ed.hex(),
                    "public_hex": sk_c_ed.public_key().public_bytes_raw().hex(),
                },
                {
                    "role": "approver signer group 2",
                    "kid_hex": KID_APPROVER_ED.hex(),
                    "kid_ascii": KID_APPROVER_ED.decode(),
                    "seed_hex": seed_a_ed.hex(),
                    "public_hex": sk_a_ed.public_key().public_bytes_raw().hex(),
                },
                {
                    "role": "enrolled service response signer",
                    "kid_hex": KID_SERVICE_ED.hex(),
                    "kid_ascii": KID_SERVICE_ED.decode(),
                    "seed_hex": seed_s_ed.hex(),
                    "public_hex": sk_s_ed.public_key().public_bytes_raw().hex(),
                },
                {
                    "role": "unattributed self-asserted signer",
                    "kid_hex": KID_UNATTRIBUTED_ED.hex(),
                    "kid_ascii": KID_UNATTRIBUTED_ED.decode(),
                    "seed_hex": seed_u_ed.hex(),
                    "public_hex": sk_u_ed.public_key().public_bytes_raw().hex(),
                },
                {
                    "role": "credential issuer (type-confusion vectors N-1/N-2)",
                    "kid_hex": KID_ISSUER_ED.hex(),
                    "kid_ascii": KID_ISSUER_ED.decode(),
                    "seed_hex": seed_i_ed.hex(),
                    "public_hex": sk_i_ed.public_key().public_bytes_raw().hex(),
                },
            ],
            "ml_dsa_65": [
                {
                    "role": "authenticated primary signer PQ component",
                    "kid_hex": KID_CLIENT_ML.hex(),
                    "kid_ascii": KID_CLIENT_ML.decode(),
                    "seed_hex": ml_client.seed.hex(),
                    "public_hex": ml_client.public.hex(),
                },
                {
                    "role": "unattributed self-asserted PQ component",
                    "kid_hex": KID_UNATTRIBUTED_ML.hex(),
                    "kid_ascii": KID_UNATTRIBUTED_ML.decode(),
                    "seed_hex": ml_unattributed.seed.hex(),
                    "public_hex": ml_unattributed.public.hex(),
                },
            ],
            "generation": {
                "ed25519": "RFC 8032 deterministic signatures over the Sig_structure",
                "ml_dsa_65": (
                    "openssl genpkey -algorithm ML-DSA-65 -pkeyopt hexseed:<seed>; "
                    "openssl pkeyutl -sign -rawin -pkeyopt deterministic:1"
                ),
            },
            "fixtures": {
                "service_domain": SERVICE_DOMAIN,
                "request_id_hex": REQUEST_ID.hex(),
                "challenge_hex": CHALLENGE.hex(),
                "iat": IAT,
                "exp": EXP,
                "capnp_schema_id_request": SCHEMA_ID_REQUEST,
                "capnp_schema_id_response": SCHEMA_ID_RESPONSE,
                "capnp_request_bytes_hex": CAPNP_REQUEST_BYTES.hex(),
                "capnp_response_bytes_hex": CAPNP_RESPONSE_BYTES.hex(),
                "verifier_now": VERIFIER_NOW,
                "credential_hash_classical_hex": CREDENTIAL_HASH.hex(),
                "credential_hash_hybrid_hex": CREDENTIAL_HASH_HYBRID.hex(),
                "external_aad": "zero-length",
            },
        }

        positives = []
        negatives = []

        def sign1(
            protected_map,
            claims,
            signer,
            *,
            protected_bytes=None,
            payload_bytes=None,
        ):
            prot = protected_bytes if protected_bytes is not None else enc(protected_map)
            payload = payload_bytes if payload_bytes is not None else enc(claims)
            tbs = sig_structure_sign1(prot, payload)
            sig = (
                signer.sign(tbs)
                if isinstance(signer, MlDsaKey)
                else signer.sign(tbs)
            )
            return enc([prot, {}, payload, sig]), prot, payload

        def sign_multi(body_protected_map, claims, entries, *, payload_bytes=None):
            body = enc(body_protected_map)
            payload = payload_bytes if payload_bytes is not None else enc(claims)
            sigs = []
            for prot_map, signer in entries:
                prot = enc(prot_map)
                tbs = sig_structure_sign(body, prot, payload)
                sigs.append([prot, {}, signer.sign(tbs)])
            return enc([body, {}, payload, sigs]), body, payload

        def record(target, ident, title, expect, structure, cbor, **extra):
            entry = {
                "id": ident,
                "title": title,
                "expect": expect,
                "structure": structure,
                "size_bytes": len(cbor),
                "sha256": hashlib.sha256(cbor).hexdigest(),
                "cbor_hex": cbor.hex(),
            }
            entry.update(extra)
            target.append(entry)
            return entry

        # ---------------- P-1: unattributed COSE_Sign1, classical -----------
        plan_unattributed = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, KID_UNATTRIBUTED_ED)])
        ]
        keyset_unattributed = [
            cose_key_okp_ed25519(
                KID_UNATTRIBUTED_ED, sk_u_ed.public_key().public_bytes_raw()
            )
        ]
        p1_protected = {
            H_ALG: ALG_ED25519,
            H_CRIT: CRIT_SIGN1_UNATTRIBUTED,
            H_KID: KID_UNATTRIBUTED_ED,
            H_TYP: TYP_REQUEST,
            H_DOMAIN: DOMAIN_REQUEST,
            H_PLAN: plan_unattributed,
            H_GROUP: 1,
            H_KEYSET: keyset_unattributed,
        }
        p1_claims = request_claims(credential_hash=None, nonce=CHALLENGE)
        p1, p1_prot, p1_payload = sign1(p1_protected, p1_claims, sk_u_ed)
        record(
            positives,
            "P-1",
            "Unattributed COSE_Sign1, classical suite, server challenge present",
            "accept",
            "COSE_Sign1",
            p1,
            protected_hex=p1_prot.hex(),
            payload_hex=p1_payload.hex(),
            notes=(
                "credential_hash null; Nonce REQUIRED for unattributed proofs; "
                "hs_unattributed_key_set carries exactly the plan's one component key."
            ),
        )

        # ---------------- P-2: authenticated hybrid COSE_Sign ---------------
        plan_hybrid = [
            group(
                1,
                SUITE_HYBRID,
                [
                    component(ALG_ED25519, KID_CLIENT_ED),
                    component(ALG_ML_DSA_65, KID_CLIENT_ML),
                ],
            )
        ]
        p2_body = {
            H_CRIT: CRIT_SIGN_BODY_AUTH,
            H_TYP: TYP_REQUEST,
            H_DOMAIN: DOMAIN_REQUEST,
            H_PLAN: plan_hybrid,
        }
        p2_claims = request_claims(credential_hash=CREDENTIAL_HASH_HYBRID)
        p2_entries = [
            (
                {
                    H_ALG: ALG_ED25519,
                    H_CRIT: CRIT_SIGN_SIGNATURE,
                    H_KID: KID_CLIENT_ED,
                    H_GROUP: 1,
                },
                sk_c_ed,
            ),
            (
                {
                    H_ALG: ALG_ML_DSA_65,
                    H_CRIT: CRIT_SIGN_SIGNATURE,
                    H_KID: KID_CLIENT_ML,
                    H_GROUP: 1,
                },
                ml_client,
            ),
        ]
        p2, p2_body_prot, p2_payload = sign_multi(p2_body, p2_claims, p2_entries)
        record(
            positives,
            "P-2",
            "Authenticated hybrid COSE_Sign, one logical signer group, two components",
            "accept",
            "COSE_Sign",
            p2,
            protected_hex=p2_body_prot.hex(),
            payload_hex=p2_payload.hex(),
            notes=(
                "Both components share hs_logical_signer_group 1 and count as one "
                "logical signer. credential_hash binds the presented credential."
            ),
        )

        # ---------------- P-3: response proof -------------------------------
        plan_response = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, KID_SERVICE_ED)])
        ]
        p3_protected = {
            H_ALG: ALG_ED25519,
            H_CRIT: CRIT_SIGN1_AUTH,
            H_KID: KID_SERVICE_ED,
            H_TYP: TYP_RESPONSE,
            H_DOMAIN: DOMAIN_RESPONSE,
            H_PLAN: plan_response,
            H_GROUP: 1,
        }
        p3_claims = request_claims(
            credential_hash=None,
            schema_id=SCHEMA_ID_RESPONSE,
            body=CAPNP_RESPONSE_BYTES,
        )
        p3, p3_prot, p3_payload = sign1(p3_protected, p3_claims, sk_s_ed)
        record(
            positives,
            "P-3",
            "Response proof COSE_Sign1 signed by the enrolled service key",
            "accept",
            "COSE_Sign1",
            p3,
            protected_hex=p3_prot.hex(),
            payload_hex=p3_payload.hex(),
            notes=(
                "cti echoes the request_id; capnp_schema_id/body carry the response "
                "root type and exact response bytes; hs_unattributed_key_set is "
                "forbidden in this profile."
            ),
        )

        # ---------------- P-4: authenticated classical with response binding -
        plan_classical_client = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, KID_CLIENT_ED)])
        ]
        p4_protected = {
            H_ALG: ALG_ED25519,
            H_CRIT: CRIT_SIGN1_AUTH,
            H_KID: KID_CLIENT_ED,
            H_TYP: TYP_REQUEST,
            H_DOMAIN: DOMAIN_REQUEST,
            H_PLAN: plan_classical_client,
            H_GROUP: 1,
        }
        # The originating request's response_binding (reused by the bound
        # response proof P-7 and the mismatch negative N-32 for field-for-field
        # equality testing).
        p4_response_binding = response_binding(
            KIND_UNARY, PROTECTION_ENCRYPTED, kem_recipient()
        )
        p4_claims = request_claims(
            credential_hash=CREDENTIAL_HASH,
            response_binding=p4_response_binding,
        )
        p4, p4_prot, p4_payload = sign1(p4_protected, p4_claims, sk_c_ed)
        record(
            positives,
            "P-4",
            "Authenticated COSE_Sign1 with an encrypted response_binding (unary, ML-KEM-768)",
            "accept",
            "COSE_Sign1",
            p4,
            protected_hex=p4_prot.hex(),
            payload_hex=p4_payload.hex(),
            notes=(
                "response_binding: root type id, response_kind=unary, "
                "protection_mode=encrypted, and the ML-KEM-768 recipient (alg -70200)."
            ),
        )

        # ---------------- P-6: cleartext stream-setup response binding ------
        # Exercises the orthogonal axes (Gate-2 §19 #4): response_kind=stream_setup
        # combined with protection_mode=cleartext and a null recipient.
        p6_protected = dict(p4_protected)
        p6_claims = request_claims(
            credential_hash=CREDENTIAL_HASH,
            response_binding=response_binding(
                KIND_STREAM_SETUP, PROTECTION_CLEARTEXT, None
            ),
        )
        p6, p6_prot, p6_payload = sign1(p6_protected, p6_claims, sk_c_ed)
        record(
            positives,
            "P-6",
            "Authenticated COSE_Sign1 with a cleartext stream-setup response_binding",
            "accept",
            "COSE_Sign1",
            p6,
            protected_hex=p6_prot.hex(),
            payload_hex=p6_payload.hex(),
            notes=(
                "response_kind=stream_setup and protection_mode=cleartext are "
                "orthogonal; a cleartext binding carries a null KEM recipient."
            ),
        )

        # ---------------- P-5: multi-party authorization --------------------
        plan_multi = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, KID_CLIENT_ED)]),
            group(2, SUITE_CLASSICAL, [component(ALG_ED25519, KID_APPROVER_ED)]),
        ]
        p5_body = {
            H_CRIT: CRIT_SIGN_BODY_AUTH,
            H_TYP: TYP_REQUEST,
            H_DOMAIN: DOMAIN_REQUEST,
            H_PLAN: plan_multi,
        }
        p5_entries = [
            (
                {
                    H_ALG: ALG_ED25519,
                    H_CRIT: CRIT_SIGN_SIGNATURE,
                    H_KID: KID_CLIENT_ED,
                    H_GROUP: 1,
                },
                sk_c_ed,
            ),
            (
                {
                    H_ALG: ALG_ED25519,
                    H_CRIT: CRIT_SIGN_SIGNATURE,
                    H_KID: KID_APPROVER_ED,
                    H_GROUP: 2,
                },
                sk_a_ed,
            ),
        ]
        p5, p5_body_prot, p5_payload = sign_multi(
            p5_body, request_claims(credential_hash=CREDENTIAL_HASH), p5_entries
        )
        record(
            positives,
            "P-5",
            "TokenBoundAndApproved: two distinct logical signer groups",
            "accept",
            "COSE_Sign",
            p5,
            protected_hex=p5_body_prot.hex(),
            payload_hex=p5_payload.hex(),
            notes="Two groups, two principals, one approval each; not a countersignature.",
        )

        # ---------------- P-7: BOUND response proof -------------------------
        # A response proof whose realized response_binding equals the originating
        # request's (P-4) field-for-field. This exercises §4's rule that the
        # response proof's binding MUST equal the request's map where both are
        # present — not merely local map shape.
        p7_protected = dict(p3_protected)  # response typ/domain, service key, classical plan
        p7_claims = request_claims(
            credential_hash=None,
            schema_id=SCHEMA_ID_RESPONSE,
            body=CAPNP_RESPONSE_BYTES,
            response_binding=p4_response_binding,   # identical to the request's binding
        )
        p7, p7_prot, p7_payload = sign1(p7_protected, p7_claims, sk_s_ed)
        record(
            positives,
            "P-7",
            "Bound response proof whose response_binding equals the originating request (P-4)",
            "accept",
            "COSE_Sign1",
            p7,
            protected_hex=p7_prot.hex(),
            payload_hex=p7_payload.hex(),
            originating_request="P-4",
            notes=(
                "Realized response binding equals P-4's request binding "
                "field-for-field; cti echoes the request_id."
            ),
        )

        # ---------------- P-8: hybrid UNATTRIBUTED COSE_Sign ----------------
        # A hybrid unattributed proof: one logical signer group, two components
        # (Ed25519 + ML-DSA-65). Its self-asserted key set carries both public
        # keys in the plan's component order; each signature is verified against
        # its EMBEDDED key, so this exercises multi-key keyset correspondence.
        plan_unatt_hybrid = [
            group(1, SUITE_HYBRID, [
                component(ALG_ED25519, KID_UNATTRIBUTED_ED),
                component(ALG_ML_DSA_65, KID_UNATTRIBUTED_ML),
            ])
        ]
        keyset_unatt_hybrid = [
            cose_key_okp_ed25519(KID_UNATTRIBUTED_ED, sk_u_ed.public_key().public_bytes_raw()),
            cose_key_akp_mldsa65(KID_UNATTRIBUTED_ML, ml_unattributed.public),
        ]
        p8_body = {
            H_CRIT: CRIT_SIGN_BODY_UNATTRIBUTED,
            H_TYP: TYP_REQUEST,
            H_DOMAIN: DOMAIN_REQUEST,
            H_PLAN: plan_unatt_hybrid,
            H_KEYSET: keyset_unatt_hybrid,
        }
        p8_entries = [
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: KID_UNATTRIBUTED_ED, H_GROUP: 1}, sk_u_ed),
            ({H_ALG: ALG_ML_DSA_65, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: KID_UNATTRIBUTED_ML, H_GROUP: 1}, ml_unattributed),
        ]
        p8, p8_body_prot, p8_payload = sign_multi(
            p8_body, request_claims(credential_hash=None, nonce=CHALLENGE), p8_entries
        )
        record(
            positives,
            "P-8",
            "Hybrid unattributed COSE_Sign; two embedded keys in plan order, verified 1:1",
            "accept",
            "COSE_Sign",
            p8,
            protected_hex=p8_body_prot.hex(),
            payload_hex=p8_payload.hex(),
            notes=(
                "hs_unattributed_key_set carries the Ed25519 then ML-DSA-65 public "
                "keys in the plan's component order; each signature verifies against "
                "its embedded key."
            ),
        )

        # ---------------- P-9: session-bound classical proof (K1) -----------
        # An authenticated classical proof bound to the user-session credential.
        # Its exp equals the authoritative session expiry (1786000020) — within BOTH
        # the credential exp (1786000030) and the session exp — so it accepts. It is
        # the boundary-accept counterpart to N-51 (which outlives the session).
        p9_claims = request_claims(credential_hash=CREDENTIAL_HASH_SESSION, extra={C_EXP: SESSION_EXP})
        p9, p9_prot, p9_payload = sign1(p4_protected, p9_claims, sk_c_ed)
        record(
            positives, "P-9",
            "Session-bound classical proof whose exp equals the authoritative session expiry",
            "accept", "COSE_Sign1", p9,
            protected_hex=p9_prot.hex(),
            payload_hex=p9_payload.hex(),
            notes=(
                "Bound to the user-session credential (sid); proof exp 1786000020 <= "
                "session exp 1786000020 <= credential exp 1786000030, valid at "
                "verifier_now 1786000015."
            ),
        )

        # =================== NEGATIVE VECTORS ===============================

        # N-1: a genuinely VALID CWT credential presented in the proof slot.
        # This is a real issuer-signed CWT access token (COSE_Sign1, typ
        # application/cwt per RFC 8392, signed by the ISSUER key over registered
        # claims) — not a proof-shaped object signed with a request-proof key.
        # Only its presentation context is wrong: presented in the proof slot it
        # denies because its typ is not the proof typ and it is issuer-signed
        # rather than cnf-bound, so the vector exercises credential-in-proof-slot
        # rejection of a well-formed credential (not merely a malformed token).
        n1_protected = {
            H_ALG: ALG_ED25519,
            H_KID: KID_ISSUER_ED,
            H_TYP: "application/cwt",
        }
        # A PROFILE-VALID v16 credential: registered claims plus the frozen
        # amendment-10 credential claims. cnf (8) is a valid RFC 8747 PoP binding
        # (a COSE_Key confirmation to the client's Ed25519 key); -70005 tenant and
        # -70006 clearance ([level, compartments]; value 11) are the frozen
        # credential keys. v16 credentials are Reusable-only, so there is no
        # use-profile field at all; only its presentation slot is wrong.
        n1_claims = {
            1: "https://issuer.hyprstream.test",  # iss
            2: "user-1",                          # sub
            C_AUD: SERVICE_DOMAIN,                # aud
            C_EXP: EXP,
            C_IAT: IAT,
            C_CTI: bytes.fromhex("a1b2c3d4e5f60718293a4b5c6d7e8f90"),  # cti
            8: {1: cose_key_okp_ed25519(          # cnf: RFC 8747 COSE_Key PoP binding
                KID_CLIENT_ED, sk_c_ed.public_key().public_bytes_raw()
            )},
            -70005: "tenant-alpha",               # tenant (amendment 10)
            -70006: [2, [5, 7]],                  # clearance [level, compartments]; assurance absent
        }
        n1, _, _ = sign1(n1_protected, n1_claims, sk_i_ed)
        record(
            negatives,
            "N-1",
            "Profile-valid issuer-signed CWT credential (cnf/tenant/clearance) presented in the proof slot",
            "deny",
            "COSE_Sign1",
            n1,
            deny_class="type-confusion",
            deny_rule=(
                "a valid credential (typ application/cwt, issuer-signed, with cnf, "
                "tenant, and clearance) is not a request proof: its typ is not "
                "application/vnd.hyprstream.proof+cwt and it is not signed by a "
                "cnf-bound proof key"
            ),
            notes=(
                "A profile-valid v16 (Reusable) credential: registered claims, "
                "RFC 8747 cnf PoP binding, tenant -70005, clearance -70006, and no "
                "use-profile field. Only its presentation slot is wrong."
            ),
        )

        # N-2: the proof CWT (the two-entry COSE_Sign P-2) presented in the
        # credential/authorization slot. Labelled COSE_Sign to match its bytes.
        record(
            negatives,
            "N-2",
            "Proof CWT (COSE_Sign) presented in the credential/authorization slot",
            "deny",
            "COSE_Sign",
            p2,
            deny_class="type-confusion",
            deny_rule=(
                "credential verification requires the credential typ "
                "(application/cwt or at+jwt) and an issuer key; the proof carries "
                "the proof typ and is signed by a cnf-bound request-proof key"
            ),
            notes="Same bytes as P-2 (a COSE_Sign), presented in the wrong slot.",
        )

        # N-3: missing typ.
        n3_protected = dict(p4_protected)
        del n3_protected[H_TYP]
        n3, _, _ = sign1(n3_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-3",
            "Protected typ (label 16) absent",
            "deny",
            "COSE_Sign1",
            n3,
            deny_class="missing-typ",
            deny_rule="RFC 9596 typ is REQUIRED in the body protected headers",
        )

        # N-4: wrong hs_domain.
        n4_protected = dict(p4_protected)
        n4_protected[H_DOMAIN] = DOMAIN_RESPONSE
        n4, _, _ = sign1(n4_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-4",
            "Correct typ with response-proof hs_domain",
            "deny",
            "COSE_Sign1",
            n4,
            deny_class="domain-separation",
            deny_rule="typ and hs_domain must both match the request-proof profile",
        )

        # N-5: stripped ML-DSA component.
        n5_body = enc(p2_body)
        n5_first_prot = enc(
            {
                H_ALG: ALG_ED25519,
                H_CRIT: CRIT_SIGN_SIGNATURE,
                H_KID: KID_CLIENT_ED,
                H_GROUP: 1,
            }
        )
        n5_tbs = sig_structure_sign(n5_body, n5_first_prot, p2_payload)
        n5 = enc(
            [n5_body, {}, p2_payload, [[n5_first_prot, {}, sk_c_ed.sign(n5_tbs)]]]
        )
        record(
            negatives,
            "N-5",
            "Hybrid proof with the ML-DSA-65 signature entry stripped",
            "deny",
            "COSE_Sign",
            n5,
            deny_class="component-stripping",
            deny_rule=(
                "the retained Ed25519 entry's Sig_structure still covers the hybrid "
                "signature_plan, so it cannot verify under the standalone classical "
                "suite; the missing plan component denies independently"
            ),
            notes="The surviving Ed25519 signature is cryptographically valid over the mutated object.",
        )

        # N-6: ninth signer group.
        plan_nine = [
            group(i, SUITE_CLASSICAL, [component(ALG_ED25519, KID_CLIENT_ED + bytes([0x30 + i]))])
            for i in range(1, 10)
        ]
        n6_protected = dict(p4_protected)
        n6_protected[H_PLAN] = plan_nine
        n6, _, _ = sign1(n6_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-6",
            "signature_plan with nine signer groups",
            "deny",
            "COSE_Sign1",
            n6,
            deny_class="parser-cap",
            deny_rule="proof-v1 cap: 1*8 signer groups",
        )

        # N-7: third component in one group.
        plan_three = [
            group(
                1,
                SUITE_HYBRID,
                [
                    component(ALG_ED25519, KID_CLIENT_ED),
                    component(ALG_ML_DSA_65, KID_CLIENT_ML),
                    component(ALG_ED25519, KID_APPROVER_ED),
                ],
            )
        ]
        n7_protected = dict(p4_protected)
        n7_protected[H_PLAN] = plan_three
        n7, _, _ = sign1(n7_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-7",
            "signer group with three components",
            "deny",
            "COSE_Sign1",
            n7,
            deny_class="parser-cap",
            deny_rule="proof-v1 cap: 1*2 components per signer group",
        )

        # N-8: unknown claim key. -70050 is in no allocated block; the proof
        # claims set is closed at -70001..-70004 (credential claim keys
        # -70005..-70007 live in a disjoint claim set and are equally unknown
        # to a proof).
        n8_claims = request_claims(
            credential_hash=CREDENTIAL_HASH, extra={UNKNOWN_CLAIM_KEY: "unregistered"}
        )
        n8, _, _ = sign1(p4_protected, n8_claims, sk_c_ed)
        record(
            negatives,
            "N-8",
            "Unknown private-use claim key -70050 in the claims set",
            "deny",
            "COSE_Sign1",
            n8,
            deny_class="closed-claim-set",
            deny_rule="an unknown claim key denies; CWT has no critical-claims mechanism",
        )

        # N-9a: unsorted map keys in the payload.
        unsorted_claims = {
            C_BODY_BYTES: CAPNP_REQUEST_BYTES,
            C_AUD: SERVICE_DOMAIN,
            C_EXP: EXP,
            C_IAT: IAT,
            C_CTI: REQUEST_ID,
            C_CREDENTIAL_HASH: CREDENTIAL_HASH,
            C_SCHEMA_ID: SCHEMA_ID_REQUEST,
            C_RESPONSE_BINDING: None,
        }
        n9a_payload = enc_unsorted(unsorted_claims)
        n9a, _, _ = sign1(p4_protected, None, sk_c_ed, payload_bytes=n9a_payload)
        record(
            negatives,
            "N-9a",
            "Claims map keys not in deterministic order",
            "deny",
            "COSE_Sign1",
            n9a,
            deny_class="non-deterministic-encoding",
            deny_rule="RFC 8949 core deterministic encoding: map keys sorted bytewise",
        )

        # N-9b: indefinite-length payload map.
        n9b_payload = enc_indefinite_map(
            request_claims(credential_hash=CREDENTIAL_HASH)
        )
        n9b, _, _ = sign1(p4_protected, None, sk_c_ed, payload_bytes=n9b_payload)
        record(
            negatives,
            "N-9b",
            "Indefinite-length claims map",
            "deny",
            "COSE_Sign1",
            n9b,
            deny_class="non-deterministic-encoding",
            deny_rule="definite lengths only",
        )

        # N-9c: floating-point timestamp.
        n9c_claims_bytes = enc(
            {
                C_AUD: SERVICE_DOMAIN,
                C_EXP: Raw(b"\xfb\x41\xda\x9a\x2c\x40\x00\x00\x00"),
                C_IAT: IAT,
                C_CTI: REQUEST_ID,
                C_CREDENTIAL_HASH: CREDENTIAL_HASH,
                C_SCHEMA_ID: SCHEMA_ID_REQUEST,
                C_BODY_BYTES: CAPNP_REQUEST_BYTES,
                C_RESPONSE_BINDING: None,
            }
        )
        n9c, _, _ = sign1(p4_protected, None, sk_c_ed, payload_bytes=n9c_claims_bytes)
        record(
            negatives,
            "N-9c",
            "Floating-point exp timestamp",
            "deny",
            "COSE_Sign1",
            n9c,
            deny_class="non-deterministic-encoding",
            deny_rule="integer Unix seconds only; no floating-point values anywhere",
        )

        # N-9d: duplicate claim key.
        dup = enc(request_claims(credential_hash=CREDENTIAL_HASH))
        # splice a duplicate aud entry and bump the map header count
        dup_entry = enc(C_AUD) + enc("other.svc.hyprstream.test")
        n9d_payload = bytes([dup[0] + 1]) + dup[1:] + dup_entry
        n9d, _, _ = sign1(p4_protected, None, sk_c_ed, payload_bytes=n9d_payload)
        record(
            negatives,
            "N-9d",
            "Duplicate aud claim key",
            "deny",
            "COSE_Sign1",
            n9d,
            deny_class="non-deterministic-encoding",
            deny_rule="no duplicate claim keys",
        )

        # N-10a: crit missing hs_domain.
        n10a_protected = dict(p4_protected)
        n10a_protected[H_CRIT] = [H_GROUP, H_PLAN]
        n10a, _, _ = sign1(n10a_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-10a",
            "crit omits hs_domain",
            "deny",
            "COSE_Sign1",
            n10a,
            deny_class="crit-set",
            deny_rule="crit sets are exact, not minimums",
        )

        # N-10b: crit carries an unknown label.
        n10b_protected = dict(p4_protected)
        n10b_protected[H_CRIT] = [H_GROUP, H_PLAN, H_DOMAIN, -70199]
        n10b, _, _ = sign1(n10b_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-10b",
            "crit carries an unknown extension label",
            "deny",
            "COSE_Sign1",
            n10b,
            deny_class="crit-set",
            deny_rule="an unrecognized critical label denies; the label is also absent from the bucket",
        )

        # N-10c: crit names a label absent from the same bucket.
        n10c_protected = dict(p4_protected)
        del n10c_protected[H_DOMAIN]
        n10c, _, _ = sign1(n10c_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-10c",
            "crit names hs_domain but the parameter is absent from the same protected bucket",
            "deny",
            "COSE_Sign1",
            n10c,
            deny_class="crit-set",
            deny_rule="RFC 9052: every crit label must occur in the same protected bucket",
        )

        # N-10d: duplicate crit entry.
        n10d_protected = dict(p4_protected)
        n10d_protected[H_CRIT] = [H_GROUP, H_PLAN, H_PLAN, H_DOMAIN]
        n10d, _, _ = sign1(n10d_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-10d",
            "Duplicate crit entry",
            "deny",
            "COSE_Sign1",
            n10d,
            deny_class="crit-set",
            deny_rule="crit entries are unique and in ascending numeric-label order",
        )

        # N-10e: crit not in ascending numeric-label order.
        n10e_protected = dict(p4_protected)
        n10e_protected[H_CRIT] = [H_DOMAIN, H_PLAN, H_GROUP]
        n10e, _, _ = sign1(n10e_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-10e",
            "crit entries in descending label order",
            "deny",
            "COSE_Sign1",
            n10e,
            deny_class="crit-set",
            deny_rule="entries use ascending numeric-label order",
        )

        # N-10f: unattributed crit set on an authenticated proof.
        n10f_protected = dict(p4_protected)
        n10f_protected[H_CRIT] = CRIT_SIGN1_UNATTRIBUTED
        n10f_protected[H_KEYSET] = [
            cose_key_okp_ed25519(
                KID_CLIENT_ED, sk_c_ed.public_key().public_bytes_raw()
            )
        ]
        n10f, _, _ = sign1(n10f_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-10f",
            "Credential-bound proof carrying hs_unattributed_key_set",
            "deny",
            "COSE_Sign1",
            n10f,
            deny_class="disposition-confusion",
            deny_rule="the unattributed key set is absent whenever a credential is presented",
        )

        # N-11: deprecated polymorphic EdDSA (-8).
        n11_protected = dict(p4_protected)
        n11_protected[H_ALG] = ALG_EDDSA_DEPRECATED
        n11_protected[H_PLAN] = [
            group(
                1,
                SUITE_CLASSICAL,
                [component(ALG_EDDSA_DEPRECATED, KID_CLIENT_ED)],
            )
        ]
        n11, _, _ = sign1(n11_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-11",
            "Signature entry using deprecated polymorphic EdDSA (-8)",
            "deny",
            "COSE_Sign1",
            n11,
            deny_class="algorithm",
            deny_rule="RFC 9864 fully-specified algorithms: Ed25519 components use -19",
        )

        # N-12: an unknown suite_id (65 bytes of "h") outside the closed suite
        # set. The suite registry is closed, so this denies as an unknown suite;
        # it also exceeds the 64-byte length the cap historically bounded.
        n12_protected = dict(p4_protected)
        n12_protected[H_PLAN] = [
            group(1, "h" * 65, [component(ALG_ED25519, KID_CLIENT_ED)])
        ]
        n12, _, _ = sign1(n12_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-12",
            "Unknown suite_id (65 bytes) outside the closed suite set",
            "deny",
            "COSE_Sign1",
            n12,
            deny_class="suite-plan",
            deny_rule="the suite registry is closed; an unknown suite_id denies (also > 64 bytes)",
        )

        # N-13: kid longer than 64 bytes.
        n13_protected = dict(p4_protected)
        long_kid = b"k" * 65
        n13_protected[H_KID] = long_kid
        n13_protected[H_PLAN] = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, long_kid)])
        ]
        n13, _, _ = sign1(n13_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-13",
            "kid of 65 bytes",
            "deny",
            "COSE_Sign1",
            n13,
            deny_class="parser-cap",
            deny_rule="proof-v1 cap: kid 1..64 bytes",
        )

        # N-14: absent required claim (credential_hash omitted, not null).
        n14_claims = request_claims(credential_hash=CREDENTIAL_HASH)
        del n14_claims[C_CREDENTIAL_HASH]
        n14, _, _ = sign1(p4_protected, n14_claims, sk_c_ed)
        record(
            negatives,
            "N-14",
            "Required claim credential_hash absent rather than null",
            "deny",
            "COSE_Sign1",
            n14,
            deny_class="closed-claim-set",
            deny_rule="every listed claim is always present; inapplicable values encode as null",
        )

        # N-15: token stripping — credential presented, signed hash null.
        n15_claims = request_claims(credential_hash=None)
        n15, _, _ = sign1(p4_protected, n15_claims, sk_c_ed)
        record(
            negatives,
            "N-15",
            "Credential presented with a null signed credential_hash",
            "deny",
            "COSE_Sign1",
            n15,
            deny_class="credential-binding",
            deny_rule="hash absence is permitted only when no credential is presented",
            notes="Presentation context: an at+jwt credential accompanies this proof.",
        )

        # N-16: unattributed proof without the server challenge.
        n16_protected = dict(p1_protected)
        n16_claims = request_claims(credential_hash=None)
        n16, _, _ = sign1(n16_protected, n16_claims, sk_u_ed)
        record(
            negatives,
            "N-16",
            "Unattributed proof with no Nonce (server challenge)",
            "deny",
            "COSE_Sign1",
            n16,
            deny_class="freshness",
            deny_rule="the challenge is REQUIRED for unattributed proofs, before any replay-store insertion",
        )

        # N-17: alg and kid only in the unprotected header.
        n17_protected_map = {
            H_CRIT: CRIT_SIGN1_AUTH,
            H_TYP: TYP_REQUEST,
            H_DOMAIN: DOMAIN_REQUEST,
            H_PLAN: plan_classical_client,
            H_GROUP: 1,
        }
        n17_prot = enc(n17_protected_map)
        n17_tbs = sig_structure_sign1(n17_prot, p4_payload)
        n17 = enc(
            [
                n17_prot,
                {H_ALG: ALG_ED25519, H_KID: KID_CLIENT_ED},
                p4_payload,
                sk_c_ed.sign(n17_tbs),
            ]
        )
        record(
            negatives,
            "N-17",
            "alg and kid carried only in the unprotected header",
            "deny",
            "COSE_Sign1",
            n17,
            deny_class="unprotected-authority",
            deny_rule="algorithm and key identifiers in unprotected headers establish no authority",
        )

        # N-18: unattributed key set with a surplus key.
        n18_protected = dict(p1_protected)
        n18_protected[H_KEYSET] = keyset_unattributed + [
            cose_key_akp_mldsa65(KID_UNATTRIBUTED_ML, ml_unattributed.public)
        ]
        n18, _, _ = sign1(n18_protected, p1_claims, sk_u_ed)
        record(
            negatives,
            "N-18",
            "Unattributed key set carrying a key with no plan component",
            "deny",
            "COSE_Sign1",
            n18,
            deny_class="key-set-strictness",
            deny_rule=(
                "every key-set element must match exactly one plan component; a "
                "surplus element denies the complete proof rather than being ignored"
            ),
        )

        # N-19: response proof carrying an unattributed key set.
        n19_protected = dict(p3_protected)
        n19_protected[H_CRIT] = CRIT_SIGN1_UNATTRIBUTED
        n19_protected[H_KEYSET] = [
            cose_key_okp_ed25519(
                KID_SERVICE_ED, sk_s_ed.public_key().public_bytes_raw()
            )
        ]
        n19, _, _ = sign1(n19_protected, p3_claims, sk_s_ed)
        record(
            negatives,
            "N-19",
            "Response proof carrying hs_unattributed_key_set",
            "deny",
            "COSE_Sign1",
            n19,
            deny_class="disposition-confusion",
            deny_rule="a self-asserted response key is never authoritative",
        )

        # N-20: signature entry assigned to a group outside the plan.
        n20_body = enc(p5_body)
        n20_entries = []
        for prot_map, signer in [
            (
                {
                    H_ALG: ALG_ED25519,
                    H_CRIT: CRIT_SIGN_SIGNATURE,
                    H_KID: KID_CLIENT_ED,
                    H_GROUP: 1,
                },
                sk_c_ed,
            ),
            (
                {
                    H_ALG: ALG_ED25519,
                    H_CRIT: CRIT_SIGN_SIGNATURE,
                    H_KID: KID_APPROVER_ED,
                    H_GROUP: 3,
                },
                sk_a_ed,
            ),
        ]:
            prot = enc(prot_map)
            n20_entries.append(
                [
                    prot,
                    {},
                    signer.sign(sig_structure_sign(n20_body, prot, p5_payload)),
                ]
            )
        n20 = enc([n20_body, {}, p5_payload, n20_entries])
        record(
            negatives,
            "N-20",
            "Signature entry declaring a logical signer group absent from the plan",
            "deny",
            "COSE_Sign",
            n20,
            deny_class="plan-mismatch",
            deny_rule="every signature entry matches exactly one plan component by group, alg, and kid",
        )

        # N-21: CBOR tag on the proof object.
        n21 = b"\xd2" + p4  # tag 18 (COSE_Sign1)
        record(
            negatives,
            "N-21",
            "Tagged COSE_Sign1 (CBOR tag 18)",
            "deny",
            "COSE_Sign1",
            n21,
            deny_class="non-deterministic-encoding",
            deny_rule="this closed profile carries no tags; the typ header performs object typing",
        )

        # N-22 (C5): a response proof whose cti does NOT echo the originating
        # request's request_id. It carries the originating-request id so the
        # suite can assert the contextual cti mismatch (mirroring N-31/N-32),
        # not merely that its bytes differ from a positive. The signature is
        # valid over the mutated cti, so it denies solely on the request binding.
        n22_claims = request_claims(
            credential_hash=None,
            schema_id=SCHEMA_ID_RESPONSE,
            body=CAPNP_RESPONSE_BYTES,
            cti=bytes.fromhex("00112233445566778899aabbccddeeff"),  # != P-4's request_id
        )
        n22, _, _ = sign1(p3_protected, n22_claims, sk_s_ed)
        record(
            negatives,
            "N-22",
            "Response proof whose cti does not echo the originating request's request_id",
            "deny",
            "COSE_Sign1",
            n22,
            deny_class="response-cti-binding",
            deny_rule="a response proof's cti MUST equal the originating request's request_id",
            originating_request="P-4",
            notes="Signature valid over the mutated cti; denies on the contextual request-ID mismatch.",
        )

        # N-23: encrypted response binding with a null KEM recipient.
        n23_claims = request_claims(
            credential_hash=CREDENTIAL_HASH,
            response_binding={
                1: SCHEMA_ID_RESPONSE,
                2: KIND_UNARY,
                3: PROTECTION_ENCRYPTED,
                4: None,
            },
        )
        n23, _, _ = sign1(p4_protected, n23_claims, sk_c_ed)
        record(
            negatives,
            "N-23",
            "Encrypted response_binding (protection_mode 2) with a null KEM recipient",
            "deny",
            "COSE_Sign1",
            n23,
            deny_class="response-binding",
            deny_rule="recipient is non-null iff protection_mode is encrypted",
            notes="Gate-2 §19 #4: the encrypted shape requires a present kem-recipient.",
        )

        # N-24: cleartext response binding carrying a KEM recipient.
        n24_claims = request_claims(
            credential_hash=CREDENTIAL_HASH,
            response_binding={
                1: SCHEMA_ID_RESPONSE,
                2: KIND_UNARY,
                3: PROTECTION_CLEARTEXT,
                4: kem_recipient(),
            },
        )
        n24, _, _ = sign1(p4_protected, n24_claims, sk_c_ed)
        record(
            negatives,
            "N-24",
            "Cleartext response_binding (protection_mode 1) carrying a KEM recipient",
            "deny",
            "COSE_Sign1",
            n24,
            deny_class="response-binding",
            deny_rule="recipient is null iff protection_mode is cleartext",
            notes="Gate-2 §19 #4: the cleartext shape forbids a kem-recipient.",
        )

        # N-25: response_kind outside the closed enum.
        n25_claims = request_claims(
            credential_hash=CREDENTIAL_HASH,
            response_binding={
                1: SCHEMA_ID_RESPONSE,
                2: 3,  # neither unary(1) nor stream_setup(2)
                3: PROTECTION_CLEARTEXT,
                4: None,
            },
        )
        n25, _, _ = sign1(p4_protected, n25_claims, sk_c_ed)
        record(
            negatives,
            "N-25",
            "response_kind value 3 outside the closed enum {1 unary, 2 stream_setup}",
            "deny",
            "COSE_Sign1",
            n25,
            deny_class="response-binding",
            deny_rule="response_kind is a closed enum: 1 unary or 2 stream_setup",
        )

        # N-26: aud exceeding the shared MAX_SERVICE_DOMAIN_BYTES cap of 128.
        n26_claims = request_claims(
            credential_hash=CREDENTIAL_HASH, aud="a" * 129
        )
        n26, _, _ = sign1(p4_protected, n26_claims, sk_c_ed)
        record(
            negatives,
            "N-26",
            "aud of 129 bytes, over the 128-byte MAX_SERVICE_DOMAIN_BYTES cap",
            "deny",
            "COSE_Sign1",
            n26,
            deny_class="parser-cap",
            deny_rule="aud is 1..128 bytes (Gate-2 §19 #7; shared MAX_SERVICE_DOMAIN_BYTES)",
        )

        # N-27: cleartext-unary response_binding carried as a non-null map.
        # response_binding is null exactly when the response is neither encrypted
        # nor streamed; a cleartext unary response is neither, so the map form is
        # forbidden — only stream_setup may be a cleartext (non-null) binding.
        n27_claims = request_claims(
            credential_hash=CREDENTIAL_HASH,
            response_binding={
                1: SCHEMA_ID_RESPONSE,
                2: KIND_UNARY,          # unary
                3: PROTECTION_CLEARTEXT,  # cleartext
                4: None,
            },
        )
        n27, _, _ = sign1(p4_protected, n27_claims, sk_c_ed)
        record(
            negatives,
            "N-27",
            "Cleartext unary response_binding carried as a non-null map",
            "deny",
            "COSE_Sign1",
            n27,
            deny_class="response-binding",
            deny_rule="cleartext unary uses a null response_binding; the map form is stream_setup only",
            notes="Canonical single encoding: cleartext unary is null, never a map.",
        )

        # N-28: hybrid-to-classical downgrade. A COSE_Sign1 plan declares the
        # hybrid suite but supplies only one Ed25519 component (dropping the
        # ML-DSA-65 component). The suite is bound to its exact component plan,
        # so a hybrid group with one component denies — the WNS hybrid cannot be
        # silently downgraded to the standalone classical suite.
        n28_protected = dict(p4_protected)
        n28_protected[H_PLAN] = [
            group(1, SUITE_HYBRID, [component(ALG_ED25519, KID_CLIENT_ED)])
        ]
        n28, _, _ = sign1(n28_protected, p4_claims, sk_c_ed)
        record(
            negatives,
            "N-28",
            "Hybrid suite plan with only one Ed25519 component (hybrid→classical downgrade)",
            "deny",
            "COSE_Sign1",
            n28,
            deny_class="suite-plan",
            deny_rule=(
                "hs-cose-sign-ed25519-mldsa65-wns-v1 requires exactly two ordered "
                "components (Ed25519 then ML-DSA-65); a single-component hybrid group denies"
            ),
            notes="Causal hybrid-to-classical downgrade: the suite is bound to its exact plan.",
        )

        # N-29: aud with an uppercase byte ("Registry.svc"). The canonical
        # service-domain syntax (validate_service_domain) is lowercase-only, so a
        # CDDL/gate-driven verifier must reject it — its audience namespace must
        # not be broader than the transport's.
        n29_claims = request_claims(credential_hash=CREDENTIAL_HASH, aud="Registry.svc")
        n29, _, _ = sign1(p4_protected, n29_claims, sk_c_ed)
        record(
            negatives,
            "N-29",
            "aud with an uppercase byte (Registry.svc), rejected by the service-domain syntax",
            "deny",
            "COSE_Sign1",
            n29,
            deny_class="aud-syntax",
            deny_rule="canonical service domain is lowercase ASCII only (validate_service_domain)",
        )

        # N-30: aud whose first byte is illegal ("-registry.svc"). The first byte
        # MUST be a lowercase ASCII letter or digit.
        n30_claims = request_claims(credential_hash=CREDENTIAL_HASH, aud="-registry.svc")
        n30, _, _ = sign1(p4_protected, n30_claims, sk_c_ed)
        record(
            negatives,
            "N-30",
            "aud with an illegal first byte ('-registry.svc')",
            "deny",
            "COSE_Sign1",
            n30,
            deny_class="aud-syntax",
            deny_rule="the first byte must be a lowercase ASCII letter or digit (validate_service_domain)",
        )

        # N-32: a response proof whose response_binding does NOT match the
        # originating request's (P-4) binding — the root_type_id differs. It is a
        # structurally valid response proof (passes local map-shape checks), so it
        # denies only under field-for-field equality with the request it answers.
        # Carries the originating-request id so the suite can compare the two.
        n32_binding = dict(p4_response_binding)
        n32_binding[1] = SCHEMA_ID_REQUEST  # root_type_id != the request's response schema id
        n32_claims = request_claims(
            credential_hash=None,
            schema_id=SCHEMA_ID_RESPONSE,
            body=CAPNP_RESPONSE_BYTES,
            response_binding=n32_binding,
        )
        n32, _, _ = sign1(p3_protected, n32_claims, sk_s_ed)
        record(
            negatives,
            "N-32",
            "Response proof whose response_binding mismatches the originating request (P-4)",
            "deny",
            "COSE_Sign1",
            n32,
            deny_class="response-binding-equality",
            deny_rule=(
                "a response proof's response_binding MUST equal the originating "
                "request's map field-for-field; a differing root_type_id denies"
            ),
            originating_request="P-4",
            notes="Locally valid map shape; denies only against the request it answers.",
        )

        # N-31 (B1): bound response proof whose -70002 (response root type ID)
        # does NOT equal its realized response_binding[1] (root_type_id). The
        # response_binding map is left EQUAL to P-4's (so the equality gate and a
        # map-shape check still pass); only -70002 is changed, and it is re-signed
        # by the service key (valid signature). It denies solely because a bound
        # response proof's -70002 MUST equal the realized binding's root_type_id.
        n31_claims = request_claims(
            credential_hash=None,
            schema_id=0xDEADBEEF,                 # != response_binding[1]
            body=CAPNP_RESPONSE_BYTES,
            response_binding=p4_response_binding,  # binding still equals P-4's
        )
        n31, _, _ = sign1(p3_protected, n31_claims, sk_s_ed)
        record(
            negatives,
            "N-31",
            "Bound response proof whose -70002 mismatches the realized response_binding root_type_id",
            "deny",
            "COSE_Sign1",
            n31,
            deny_class="response-schema-binding",
            deny_rule=(
                "for a non-null response_binding, claim -70002 MUST equal the "
                "binding's root_type_id (key 1)"
            ),
            originating_request="P-4",
            notes="Only -70002 differs; the binding map still equals P-4's and the signature is valid.",
        )

        # N-33 (B2): a fully signature-valid COSE_Sign whose plan repeats one
        # (alg, kid) in two logical groups. Both entries are signed by the same
        # client key, so a verifier that counts groups could satisfy a
        # multi-party rule (P-5's shape) with a single signer. It denies because
        # (alg, kid) MUST be unique across the whole plan, regardless of group ID.
        n33_plan = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, KID_CLIENT_ED)]),
            group(2, SUITE_CLASSICAL, [component(ALG_ED25519, KID_CLIENT_ED)]),  # duplicate (alg,kid)
        ]
        n33_body = {
            H_CRIT: CRIT_SIGN_BODY_AUTH,
            H_TYP: TYP_REQUEST,
            H_DOMAIN: DOMAIN_REQUEST,
            H_PLAN: n33_plan,
        }
        n33_entries = [
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: KID_CLIENT_ED, H_GROUP: 1}, sk_c_ed),
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: KID_CLIENT_ED, H_GROUP: 2}, sk_c_ed),
        ]
        n33, _, _ = sign_multi(
            n33_body, request_claims(credential_hash=CREDENTIAL_HASH), n33_entries
        )
        record(
            negatives,
            "N-33",
            "COSE_Sign plan repeating one (alg, kid) across two logical groups",
            "deny",
            "COSE_Sign",
            n33,
            deny_class="plan-key-uniqueness",
            deny_rule="every (alg, kid) pair MUST be unique across the whole plan, regardless of group ID",
            notes="Both signatures are valid; a single signer must not satisfy a two-group policy.",
        )

        # N-35 (B4): unattributed proof whose EMBEDDED public key does not match
        # the signing key. The key set element keeps the correct kid/alg/crv but
        # carries a DIFFERENT public key (the approver's); the proof is re-signed
        # with the real unattributed key over the mutated protected bucket. It
        # denies because each unattributed signature MUST verify against its
        # embedded key — not a key resolved out of band.
        n35_protected = dict(p1_protected)
        n35_protected[H_KEYSET] = [
            cose_key_okp_ed25519(
                KID_UNATTRIBUTED_ED, sk_a_ed.public_key().public_bytes_raw()  # wrong key
            )
        ]
        n35, _, _ = sign1(n35_protected, p1_claims, sk_u_ed)  # signed by the REAL key
        record(
            negatives,
            "N-35",
            "Unattributed proof whose embedded key set does not match the signing key",
            "deny",
            "COSE_Sign1",
            n35,
            deny_class="unattributed-keyset",
            deny_rule="each unattributed signature MUST verify against its embedded key set key",
            notes=(
                "Correct kid/alg/crv but a different public key; re-signed with the "
                "real key over the mutated bucket, so it denies at embedded-key "
                "verification, not by a plan-shape or self-signature failure."
            ),
        )

        # N-37 (B4): hybrid unattributed key set whose second element duplicates
        # the first (Ed25519) instead of the ML-DSA-65 key — element 1 does not
        # correspond to the plan's ML-DSA-65 component.
        n37_body = dict(p8_body)
        n37_body[H_KEYSET] = [
            cose_key_okp_ed25519(KID_UNATTRIBUTED_ED, sk_u_ed.public_key().public_bytes_raw()),
            cose_key_okp_ed25519(KID_UNATTRIBUTED_ED, sk_u_ed.public_key().public_bytes_raw()),
        ]
        n37, _, _ = sign_multi(
            n37_body, request_claims(credential_hash=None, nonce=CHALLENGE), p8_entries
        )
        record(
            negatives,
            "N-37",
            "Hybrid unattributed key set duplicating the Ed25519 element (no ML-DSA-65 key)",
            "deny",
            "COSE_Sign",
            n37,
            deny_class="unattributed-keyset",
            deny_rule="key set element i MUST correspond to plan component i by kid/alg/kty",
            notes="Element 1 is Ed25519 where the plan's component 1 is ML-DSA-65.",
        )

        # N-38 (B4): hybrid unattributed key set with the two elements REORDERED
        # (ML-DSA-65 first, Ed25519 second) — out of the plan's component order.
        n38_body = dict(p8_body)
        n38_body[H_KEYSET] = [
            cose_key_akp_mldsa65(KID_UNATTRIBUTED_ML, ml_unattributed.public),
            cose_key_okp_ed25519(KID_UNATTRIBUTED_ED, sk_u_ed.public_key().public_bytes_raw()),
        ]
        n38, _, _ = sign_multi(
            n38_body, request_claims(credential_hash=None, nonce=CHALLENGE), p8_entries
        )
        record(
            negatives,
            "N-38",
            "Hybrid unattributed key set with elements reordered out of plan component order",
            "deny",
            "COSE_Sign",
            n38,
            deny_class="unattributed-keyset",
            deny_rule="key set elements MUST be in the plan's exact component order",
            notes="Element 0 is ML-DSA-65 where component 0 is Ed25519.",
        )

        # N-40 (B6): two logical groups sharing one group_id. Both signatures are
        # valid and the (alg, kid) pairs are distinct (so B2 passes), but the two
        # groups collapse to a single group_id — a single logical group can then
        # masquerade as two for a multi-party policy.
        n40_plan = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, KID_CLIENT_ED)]),
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, KID_APPROVER_ED)]),  # duplicate group_id
        ]
        n40_body = {H_CRIT: CRIT_SIGN_BODY_AUTH, H_TYP: TYP_REQUEST, H_DOMAIN: DOMAIN_REQUEST, H_PLAN: n40_plan}
        n40_entries = [
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: KID_CLIENT_ED, H_GROUP: 1}, sk_c_ed),
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: KID_APPROVER_ED, H_GROUP: 1}, sk_a_ed),
        ]
        n40, _, _ = sign_multi(n40_body, request_claims(credential_hash=CREDENTIAL_HASH), n40_entries)
        record(
            negatives, "N-40",
            "signature_plan with two groups sharing one group_id",
            "deny", "COSE_Sign", n40,
            deny_class="group-id-order",
            deny_rule="group IDs MUST be unique and strictly ascending across the plan",
            notes="Both signatures valid; distinct (alg,kid); denies solely on the duplicate group_id.",
        )

        # N-41 (B6): group IDs out of ascending order (2 then 1).
        n41_plan = [
            group(2, SUITE_CLASSICAL, [component(ALG_ED25519, KID_CLIENT_ED)]),
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, KID_APPROVER_ED)]),  # descending
        ]
        n41_body = {H_CRIT: CRIT_SIGN_BODY_AUTH, H_TYP: TYP_REQUEST, H_DOMAIN: DOMAIN_REQUEST, H_PLAN: n41_plan}
        n41_entries = [
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: KID_CLIENT_ED, H_GROUP: 2}, sk_c_ed),
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: KID_APPROVER_ED, H_GROUP: 1}, sk_a_ed),
        ]
        n41, _, _ = sign_multi(n41_body, request_claims(credential_hash=CREDENTIAL_HASH), n41_entries)
        record(
            negatives, "N-41",
            "signature_plan with group IDs out of ascending order",
            "deny", "COSE_Sign", n41,
            deny_class="group-id-order",
            deny_rule="group IDs MUST be strictly ascending across the plan",
            notes="Both signatures valid; groups are 2 then 1.",
        )

        # N-42 (B8): unattributed key set with three elements, over the frozen
        # 1..2 element ceiling (the pycddl AKP workaround drops the `1*2` bound,
        # so the gate/checker re-impose it). Three classical groups, three
        # embedded OKP keys, all signatures valid.
        n42_plan = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, b"unattributed-ed25519-1")]),
            group(2, SUITE_CLASSICAL, [component(ALG_ED25519, b"unattributed-ed25519-2")]),
            group(3, SUITE_CLASSICAL, [component(ALG_ED25519, b"unattributed-ed25519-3")]),
        ]
        n42_keyset = [
            cose_key_okp_ed25519(b"unattributed-ed25519-1", sk_u_ed.public_key().public_bytes_raw()),
            cose_key_okp_ed25519(b"unattributed-ed25519-2", sk_a_ed.public_key().public_bytes_raw()),
            cose_key_okp_ed25519(b"unattributed-ed25519-3", sk_s_ed.public_key().public_bytes_raw()),
        ]
        n42_body = {
            H_CRIT: CRIT_SIGN_BODY_UNATTRIBUTED, H_TYP: TYP_REQUEST, H_DOMAIN: DOMAIN_REQUEST,
            H_PLAN: n42_plan, H_KEYSET: n42_keyset,
        }
        n42_entries = [
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: b"unattributed-ed25519-1", H_GROUP: 1}, sk_u_ed),
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: b"unattributed-ed25519-2", H_GROUP: 2}, sk_a_ed),
            ({H_ALG: ALG_ED25519, H_CRIT: CRIT_SIGN_SIGNATURE, H_KID: b"unattributed-ed25519-3", H_GROUP: 3}, sk_s_ed),
        ]
        n42, _, _ = sign_multi(n42_body, request_claims(credential_hash=None, nonce=CHALLENGE), n42_entries)
        record(
            negatives, "N-42",
            "Unattributed key set with three elements, over the 1..2 ceiling",
            "deny", "COSE_Sign", n42,
            deny_class="unattributed-keyset",
            deny_rule="the unattributed key set carries 1..2 elements (frozen cap)",
            notes="All signatures valid; denies solely on the over-ceiling key-set size.",
        )

        # N-43 (D2): a response proof issued for a DIFFERENT service domain than
        # the originating request. Everything else (cti, response_binding) still
        # equals P-4's; only aud differs, and the signature is valid — so it
        # denies solely on response-aud contextual binding (aud MUST equal the
        # originating request's aud).
        n43_claims = request_claims(
            credential_hash=None,
            aud="other.svc.hyprstream.test",   # != P-4's aud
            schema_id=SCHEMA_ID_RESPONSE,
            body=CAPNP_RESPONSE_BYTES,
            response_binding=p4_response_binding,   # binding still equals P-4's
        )
        n43, _, _ = sign1(p3_protected, n43_claims, sk_s_ed)
        record(
            negatives, "N-43",
            "Response proof whose aud differs from the originating request's service domain",
            "deny", "COSE_Sign1", n43,
            deny_class="response-aud-binding",
            deny_rule="a response proof's aud MUST equal the originating request's aud",
            originating_request="P-4",
            notes="Only aud differs; cti and response_binding still equal P-4's; signature valid.",
        )

        # ---- E1: byte-range boundary negatives for the stripped .size ranges ----
        # The pinned pycddl 0.3.0 strips every `.size (LO..HI)` control, so each
        # stripped range needs a causal boundary negative that the numeric gate
        # rejects. suite_id/kid/aud uppers are N-12/N-13/N-26; these close the
        # remaining boundaries (body upper, Nonce lower+upper, kid lower).

        # N-44: capnp_body_bytes one byte over the 1 MiB cap (upper boundary of
        # capnp-body-bytes = bstr .size (0..1048576)). The whole object still fits
        # under the 2 MiB object cap, so it denies solely on the body-length rule.
        n44_claims = request_claims(
            credential_hash=CREDENTIAL_HASH, body=b"\x00" * (1048576 + 1)
        )
        n44, _, _ = sign1(p4_protected, n44_claims, sk_c_ed)
        record(
            negatives, "N-44",
            "capnp_body_bytes of 1 MiB + 1, one byte over the 1048576 cap",
            "deny", "COSE_Sign1", n44,
            deny_class="parser-cap",
            deny_rule="capnp-body-bytes is 0..1048576 (1 MiB body cap)",
            notes="Object stays under the 2 MiB cap; denies solely on the body-length rule.",
        )

        # N-45: Nonce (server challenge) of 15 bytes, one under the 16-byte floor
        # (lower boundary of server-challenge = bstr .size (16..64)).
        n45_claims = request_claims(credential_hash=None, nonce=b"\x00" * 15)
        n45, _, _ = sign1(p1_protected, n45_claims, sk_u_ed)
        record(
            negatives, "N-45",
            "Unattributed proof whose Nonce is 15 bytes, under the 16-byte floor",
            "deny", "COSE_Sign1", n45,
            deny_class="nonce-length",
            deny_rule="server-challenge is 16..64 bytes",
            notes="Valid unattributed structure/signature; denies solely on the Nonce lower bound.",
        )

        # N-46: Nonce of 65 bytes, one over the 64-byte ceiling (upper boundary).
        n46_claims = request_claims(credential_hash=None, nonce=b"\x00" * 65)
        n46, _, _ = sign1(p1_protected, n46_claims, sk_u_ed)
        record(
            negatives, "N-46",
            "Unattributed proof whose Nonce is 65 bytes, over the 64-byte ceiling",
            "deny", "COSE_Sign1", n46,
            deny_class="nonce-length",
            deny_rule="server-challenge is 16..64 bytes",
            notes="Valid unattributed structure/signature; denies solely on the Nonce upper bound.",
        )

        # N-47: empty kid, under the 1-byte floor (lower boundary of
        # kid = bstr .size (1..64)); mirrors N-13 (kid upper) with a 0-length kid.
        n47_protected = dict(p4_protected)
        n47_protected[H_KID] = b""
        n47_protected[H_PLAN] = [
            group(1, SUITE_CLASSICAL, [component(ALG_ED25519, b"")])
        ]
        n47, _, _ = sign1(n47_protected, p4_claims, sk_c_ed)
        record(
            negatives, "N-47",
            "kid of 0 bytes, under the 1-byte floor",
            "deny", "COSE_Sign1", n47,
            deny_class="parser-cap",
            deny_rule="proof-v1 cap: kid 1..64 bytes",
            notes="Empty kid violates the kid lower bound independently of the aud .regexp.",
        )

        # N-48 (E2): P-3 with its trailing Ed25519 signature bstr header widened
        # from `58 40` (64 bytes) to `58 41` (65 bytes) with NO byte added — the
        # declared length exceeds the bytes present, so the strict decoder MUST
        # reject the truncation (the reviewer's exact exploit). This is the
        # `58 41` + 64 bytes shape; a lenient slicing decoder would "decode" and
        # even verify the surviving signature.
        assert p3[-66:-64] == b"\x58\x40", "P-3 must end with a 64-byte Ed25519 sig bstr header"
        n48 = p3[:-66] + b"\x58\x41" + p3[-64:]
        record(
            negatives, "N-48",
            "Truncated CBOR: response signature bstr header declares 65 bytes with 64 present",
            "deny", "COSE_Sign1", n48,
            deny_class="cbor-truncation",
            deny_rule="a length-delimited value must have at least the declared number of bytes",
            notes="Header widened 58 40 -> 58 41, no byte added; strict decoder rejects (len(rest) < val).",
        )

        # N-49 (G2): a proof whose claims payload carries a TRUNCATED integer
        # argument — the `iat` value is `19 00` (ai=25 declares a 2-byte argument
        # with only 1 byte present). The outer COSE_Sign1 array decodes, but the
        # payload's integer argument is truncated, so a fail-closed strict decoder
        # rejects it (len(rest) < n); a lenient decoder would read a short/zero
        # value. `a1 06 19 00` = {6: <truncated int>}. The de-fanged exact-length
        # counterpart `a1 06 19 01 00` = {6: 256} decodes cleanly.
        n49_payload = b"\xa1\x06\x19\x00"
        n49 = enc([p4_prot, {}, n49_payload, b"\x00" * 64])
        record(
            negatives, "N-49",
            "Truncated CBOR integer: claims iat argument `19 00` declares 2 bytes with 1 present",
            "deny", "COSE_Sign1", n49,
            deny_class="integer-truncation",
            deny_rule="a CBOR additional-information argument (ai 24/25/26/27) must carry its full 1/2/4/8-byte length",
            notes="Outer array decodes; the payload integer argument is truncated (ai=25, 1 of 2 bytes).",
        )

        # N-50 (H1): a correctly-signed authenticated proof whose own `exp`
        # (1786000060) EXCEEDS its mapped credential's `exp` (1786000030). Both are
        # still valid at verifier_now (1786000015), so a verifier that merely checks
        # each artifact against the clock accepts it; the rule "a proof exp MUST NOT
        # exceed credential/session expiry" (credential-profile §5) denies it. Bound
        # to the classical credential via credential_hash.
        n50_claims = request_claims(credential_hash=CREDENTIAL_HASH, extra={C_EXP: 1786000060})
        n50, _, _ = sign1(p4_protected, n50_claims, sk_c_ed)
        record(
            negatives, "N-50",
            "Authenticated proof whose exp (1786000060) exceeds its mapped credential's exp (1786000030)",
            "deny", "COSE_Sign1", n50,
            deny_class="proof-credential-expiry",
            deny_rule="a proof exp MUST NOT exceed the mapped credential (or session) expiry",
            notes="Both proof and credential are valid at verifier_now; denies solely on the expiry-binding rule.",
        )

        # N-51 (K1): a correctly-signed proof bound to the user-session credential
        # whose exp (1786000025) is WITHIN the credential exp (1786000030) but LATER
        # than the authoritative session exp (1786000020). Proof, credential, and
        # session are all unexpired at verifier_now (1786000015), so it denies solely
        # on the session-expiry bound — the credential bound is satisfied.
        n51_claims = request_claims(credential_hash=CREDENTIAL_HASH_SESSION, extra={C_EXP: 1786000025})
        n51, _, _ = sign1(p4_protected, n51_claims, sk_c_ed)
        record(
            negatives, "N-51",
            "Session-bound proof whose exp (1786000025) exceeds the authoritative session exp (1786000020)",
            "deny", "COSE_Sign1", n51,
            deny_class="proof-session-expiry",
            deny_rule="a proof exp MUST NOT exceed the authoritative session expiry for a sid-bearing credential",
            notes="proof exp <= credential exp but > session exp; the credential bound is satisfied, only the session bound denies.",
        )

    meta = {
        "vector_set_version": 1,
        "profile": "hs-rpc-proof-v1",
        "status": "frozen by the Gate-2 vote (v16 §19, 2026-08-19); not production-closed",
        "encoding": "RFC 8949 core deterministic encoding; untagged COSE structures",
        "external_aad": "zero-length for every Sig_structure in this profile",
        "verifier_now": VERIFIER_NOW,
        "generator": "docs/standards/v16/tools/gen_proof_vectors.py",
    }

    # ---- F1/F2: verifier clock + authenticated credential context ------------
    credentials_doc = {
        **meta,
        "kind": "authenticated-credential-context",
        "verifier_now": VERIFIER_NOW,
        "verifier_now_note": (
            "Accept/reject dispositions are evaluated at this exact integer instant. "
            "A conformance runner MUST inject it as the verifier clock instead of "
            "using wall-clock time; iat <= verifier_now < exp for every advertised "
            "positive and every credential below."
        ),
        "issuer": {
            "kid": KID_ISSUER_ED.decode(),
            "alg": "EdDSA",
            "typ": "at+jwt",
            "public_hex": issuer_pub.hex(),
        },
        "cnf_model": {
            "member": "hs_signer_suite",
            "value": "base64url(SHA-256(RFC 8949 det-CBOR [suite_id, [ordered raw component public keys]]))",
            "note": (
                "A profile-defined RFC 8747 confirmation method resolving to the "
                "credential-profile §5 signer-suite record (suite ID + exact ordered "
                "component keys of the PRIMARY signer group). Approver groups bind "
                "their own enrollment and are never placed in cnf. Distinct from the "
                "C1 replay thumbprint (no domain separator, no enrollment epoch)."
            ),
        },
        "encoding_matrix": {
            "note": (
                "G1 (credential-profile §1.1): a HYBRID (multi-key) primary group has "
                "no v16 CWT confirmation method, so hybrid credentials are at+jwt (JWT) "
                "only via cnf.hs_signer_suite. The CWT cnf is a single RFC 8747 COSE_Key "
                "and binds a CLASSICAL (single-key) primary only (N-1 is that shape). No "
                "multi-key CWT confirmation label/shape is allocated or reserved."
            ),
            "hybrid_encoding": "at+jwt-only",
            "cwt_cnf": "single RFC 8747 COSE_Key; classical (single-key) primary only",
            "cwt_hybrid": "deferred (no v16 method)",
        },
        "credentials": {
            "classical": {
                "encoding": "at+jwt",
                "credential_kind": "rfc8693",
                "token": cred_classical,
                "header": hdr_classical,
                "claims": claims_classical,
                "primary_suite": SUITE_CLASSICAL,
                "cnf_preimage_hex": enc([SUITE_CLASSICAL, [client_ed_pub]]).hex(),
                "cnf_thumbprint_b64": b64u(cnf_classical),
                "token_sha256": CREDENTIAL_HASH.hex(),
            },
            "hybrid": {
                "encoding": "at+jwt",
                "credential_kind": "rfc8693",
                "token": cred_hybrid,
                "header": hdr_hybrid,
                "claims": claims_hybrid,
                "primary_suite": SUITE_HYBRID,
                "cnf_preimage_hex": enc([SUITE_HYBRID, [client_ed_pub, ml_client.public]]).hex(),
                "cnf_thumbprint_b64": b64u(cnf_hybrid),
                "token_sha256": CREDENTIAL_HASH_HYBRID.hex(),
            },
            "session": {
                "encoding": "at+jwt",
                "credential_kind": "user-session",
                "token": cred_session,
                "header": hdr_session,
                "claims": claims_session,
                "primary_suite": SUITE_CLASSICAL,
                "cnf_preimage_hex": enc([SUITE_CLASSICAL, [client_ed_pub]]).hex(),
                "cnf_thumbprint_b64": b64u(cnf_classical),
                "token_sha256": CREDENTIAL_HASH_SESSION.hex(),
                "session_id": SESSION_ID,
            },
        },
        "session_model": {
            "note": (
                "K1: a user-session credential carries the OIDC `sid` (§3.2). The "
                "AUTHORITATIVE session expiry is the authority's session state keyed "
                "by (iss, sid) (§3.4) — NOT a credential/wire claim. A proof's exp MUST "
                "NOT exceed BOTH the credential exp and the session exp; an unknown, "
                "revoked, expired, or (iss/sub/tenant)-mismatched session denies."
            ),
            "credential_kind_note": (
                "sid presence is unambiguous by classification (metadata aligned with "
                "B's IssueTokenProfile enum, NOT a wire claim): a `user-session` "
                "credential is an interactive OIDC session token and MUST carry sid "
                "(session). A `rfc8693` / `rfc7523` credential is a NON-INTERACTIVE "
                "token-exchange / JWT-bearer profile that MUST NOT carry sid (classical, "
                "hybrid — user subject, no interactive session). A `service` credential "
                "(none shipped) has a `service:`-prefixed subject and no sid. §3.2/§3.3."
            ),
        },
        "sessions": [
            {
                "iss": ISSUER_ISS,
                "sid": SESSION_ID,
                "sub": CREDENTIAL_SUBJECT,
                "tenant": CREDENTIAL_TENANT,
                "session_kind": "interactive",
                "created": IAT,
                "expiry": SESSION_EXP,
                "status": "active",
            },
        ],
        "positive_to_credential": {
            "P-2": "hybrid",
            "P-4": "classical",
            "P-5": "classical",
            "P-6": "classical",
            "P-9": "session",
        },
    }

    # ---- C1: frozen replay-namespace thumbprint vectors ----------------------
    # SHA-256 over the RFC 8949 core-deterministic encoding of a CBOR array whose
    # first element is the domain-separator text (see the CDDL §7.1).
    replay_domain_authenticated = "hs-rpc-replay-primary-suite-v1"
    replay_domain_key_set = "hs-rpc-replay-key-set-v1"
    enrollment_epoch = 1
    client_ed_pub = sk_c_ed.public_key().public_bytes_raw()
    # Authenticated example: the hybrid primary group (P-2's suite + ordered
    # public component keys), approver groups excluded.
    auth_preimage = enc([
        replay_domain_authenticated,
        SUITE_HYBRID,
        [client_ed_pub, ml_client.public],
        enrollment_epoch,
    ])
    auth_thumbprint = hashlib.sha256(auth_preimage).digest()
    # Unattributed example: P-1's plan and embedded key set, verbatim.
    keyset_preimage = enc([replay_domain_key_set, plan_unattributed, keyset_unattributed])
    keyset_thumbprint = hashlib.sha256(keyset_preimage).digest()
    thumbprints = {
        **meta,
        "kind": "replay-thumbprints",
        "domain_separators": {
            "authenticated": replay_domain_authenticated,
            "key_set": replay_domain_key_set,
        },
        "sha256_of": "the RFC 8949 core-deterministic encoding of a CBOR array; domain separator is element 0",
        "authenticated": {
            "note": "credential-bound primary signer-suite thumbprint (design §4.5/§4.6); approver groups excluded",
            "suite_id": SUITE_HYBRID,
            "component_public_keys_hex": [client_ed_pub.hex(), ml_client.public.hex()],
            "enrollment_epoch": enrollment_epoch,
            "preimage_hex": auth_preimage.hex(),
            "thumbprint_sha256": auth_thumbprint.hex(),
        },
        "unattributed": {
            "note": "unattributed proof-key-set thumbprint (design §4.7/§7) over (signature_plan, unattributed_key_set)",
            "from_vector": "P-1",
            "preimage_hex": keyset_preimage.hex(),
            "thumbprint_sha256": keyset_thumbprint.hex(),
        },
    }

    (out_dir / "proof-v1-keys.json").write_text(
        json.dumps({**meta, "keys": keys_doc}, indent=2) + "\n"
    )
    (out_dir / "proof-v1-positive.json").write_text(
        json.dumps({**meta, "kind": "positive", "vectors": positives}, indent=2) + "\n"
    )
    (out_dir / "proof-v1-negative.json").write_text(
        json.dumps({**meta, "kind": "negative", "vectors": negatives}, indent=2) + "\n"
    )
    (out_dir / "proof-v1-thumbprints.json").write_text(
        json.dumps(thumbprints, indent=2) + "\n"
    )
    (out_dir / "proof-v1-credentials.json").write_text(
        json.dumps(credentials_doc, indent=2) + "\n"
    )
    print(f"wrote {len(positives)} positive and {len(negatives)} negative vectors to {out_dir}")


if __name__ == "__main__":
    main()
