// CLI module — prints to stdout for user interaction
#![allow(clippy::print_stdout, clippy::print_stderr)]
//! Schema-driven CLI command builder and dispatcher.
//!
//! Builds clap `Command` objects at runtime from `MethodSchema` metadata
//! (generated by hyprstream-rpc-derive from Cap'n Proto schemas) and
//! dispatches invocations to the appropriate service client's `call_method()`.

use anyhow::{bail, Context, Result};
use clap::{Arg, ArgMatches, Command};
use ed25519_dalek::SigningKey;
use hyprstream_service::ScopedClientTreeNode;
use serde_json::Value;

use crate::services::generated::inference_client::InferenceClient;
use crate::services::generated::model_client::ModelClient;
use crate::services::generated::{inference_client, model_client, policy_client, registry_client};
use crate::services::{DiscoveryClient, RegistryClient};
use hyprstream_workers::generated::{worker_client, workflow_client};
use hyprstream_workers::runtime::WorkerClient;

// ─────────────────────────────────────────────────────────────────────────────
// MethodSchemaLike trait — unifies per-module MethodSchema types
// ─────────────────────────────────────────────────────────────────────────────

/// Trait to abstract over the structurally identical but distinct `MethodSchema`
/// types generated by each service's proc macro invocation.
pub trait MethodSchemaLike {
    fn name(&self) -> &str;
    fn params(&self) -> &[impl ParamSchemaLike];
    fn is_scoped(&self) -> bool;
    fn scope_field(&self) -> &str;
    fn description(&self) -> &str;
    fn is_streaming(&self) -> bool;
    fn cli_hidden(&self) -> bool;
}

pub trait ParamSchemaLike {
    fn name(&self) -> &str;
    fn type_name(&self) -> &str;
    fn required(&self) -> bool;
    fn description(&self) -> &str;
}

/// Portable view of a method schema, extracted from any generated MethodSchema.
#[derive(Debug, Clone)]
pub struct MethodView {
    pub name: String,
    pub params: Vec<ParamView>,
    pub is_scoped: bool,
    pub scope_field: String,
    pub description: String,
    pub is_streaming: bool,
    pub cli_hidden: bool,
}

#[derive(Debug, Clone)]
pub struct ParamView {
    pub name: String,
    pub type_name: String,
    pub required: bool,
    pub description: String,
    pub default_value: String,
}

/// Extract a portable MethodView list from any generated module's schema_metadata.
/// Uses a macro since each module's MethodSchema is a distinct type.
macro_rules! extract_methods {
    ($schema_fn:expr) => {{
        let (_service_name, methods) = $schema_fn;
        methods_to_views(methods)
    }};
}

/// Convert a slice of MethodMeta into MethodView values.
fn methods_to_views(methods: &[hyprstream_service::MethodMeta]) -> Vec<MethodView> {
    methods
        .iter()
        .map(|m| MethodView {
            name: m.name.to_owned(),
            params: m
                .params
                .iter()
                .map(|p| ParamView {
                    name: p.name.to_owned(),
                    type_name: p.type_name.to_owned(),
                    required: p.required,
                    description: p.description.to_owned(),
                    default_value: p.default_value.to_owned(),
                })
                .collect(),
            is_scoped: m.is_scoped,
            scope_field: m.scope_field.to_owned(),
            description: m.description.to_owned(),
            is_streaming: m.is_streaming,
            cli_hidden: m.hidden,
        })
        .collect()
}

/// Convert scoped metadata (service, scope, methods) into MethodView values.
fn scoped_methods_to_views(
    metadata_fn: hyprstream_service::ScopedSchemaMetadataFn,
) -> Vec<MethodView> {
    let (_service_name, _scope_name, methods) = metadata_fn();
    methods_to_views(methods)
}

// ─────────────────────────────────────────────────────────────────────────────
// Build clap Commands from schema metadata
// ─────────────────────────────────────────────────────────────────────────────

/// Build a clap `Command` for a service from its methods and scoped client tree.
fn build_service_command(
    service_name: &str,
    methods: &[MethodView],
    tree: &'static [ScopedClientTreeNode],
) -> Command {
    // Leak service_name to get 'static lifetime required by clap
    let name: &'static str = service_name.to_owned().leak();
    let mut cmd = Command::new(name)
        .about(format!("{} service commands", service_name))
        .arg_required_else_help(true);

    // Add top-level methods as subcommands (filtering cli_hidden and streaming)
    for method in methods {
        if method.cli_hidden || method.is_streaming {
            continue;
        }
        cmd = cmd.subcommand(build_method_command(method));
    }

    // Add scoped subcommands from tree (recursive)
    for node in tree {
        cmd = cmd.subcommand(build_scoped_command_from_node(node));
    }

    cmd
}

/// Recursively build a scoped command from a tree node.
fn build_scoped_command_from_node(node: &ScopedClientTreeNode) -> Command {
    let sn: &'static str = node.scope_name;
    let methods = scoped_methods_to_views(node.metadata_fn);

    let mut cmd = Command::new(sn)
        .about(format!("{} scoped commands", node.scope_name))
        .subcommand_required(true)
        .arg_required_else_help(true);

    // Only add scope_id positional arg if there's a scope field
    if !node.scope_field.is_empty() {
        cmd = cmd.arg(
            Arg::new("scope_id")
                .required(true)
                .help("Scope identifier (e.g., model name, repo ID)"),
        );
    }

    for method in &methods {
        if method.cli_hidden || method.is_streaming {
            continue;
        }
        cmd = cmd.subcommand(build_method_command(method));
    }

    // Recursively add nested scoped commands
    for nested in node.nested {
        cmd = cmd.subcommand(build_scoped_command_from_node(nested));
    }

    cmd
}

/// Build a clap `Command` for a single method.
fn build_method_command(method: &MethodView) -> Command {
    // Convert snake_case method name to kebab-case for CLI
    // Leak the string to get a &'static str for clap's Str type
    let cli_name: &'static str = method.name.replace('_', "-").leak();
    let mut cmd = Command::new(cli_name);

    if !method.description.is_empty() {
        let desc: &'static str = method.description.clone().leak();
        cmd = cmd.about(desc);
    }

    for param in &method.params {
        let arg_name: &'static str = param.name.replace('_', "-").leak();
        let param_id: &'static str = param.name.clone().leak();
        let mut arg = Arg::new(param_id).long(arg_name);

        if param.type_name == "Bool" {
            // Bool params are flags: --read (present=true, absent=false)
            arg = arg.action(clap::ArgAction::SetTrue);
        } else {
            arg = arg.required(param.required);
        }

        if !param.description.is_empty() {
            let help: &'static str = param.description.clone().leak();
            arg = arg.help(help);
        }

        cmd = cmd.arg(arg);
    }
    cmd
}

/// Build the `tool` command containing all schema-driven service subcommands.
///
/// Usage: `hyprstream tool <service> [scope <id>] <method> [--param value ...]`
pub fn build_tool_command() -> Command {
    let mut tool =
        Command::new("tool").about("Direct RPC tool access (schema-driven, mirrors MCP tools)");

    // Registry service
    let registry_methods = extract_methods!(registry_client::schema_metadata());
    let registry_tree = registry_client::scoped_client_tree();
    tool = tool.subcommand(build_service_command(
        "registry",
        &registry_methods,
        registry_tree,
    ));

    // Model service
    let model_methods = extract_methods!(model_client::schema_metadata());
    let model_tree = model_client::scoped_client_tree();
    tool = tool.subcommand(build_service_command("model", &model_methods, model_tree));

    // Inference service (standalone, no scoped)
    let inference_methods = extract_methods!(inference_client::schema_metadata());
    let inference_tree = inference_client::scoped_client_tree();
    tool = tool.subcommand(build_service_command(
        "inference",
        &inference_methods,
        inference_tree,
    ));

    // Policy service (standalone, no scoped)
    let policy_methods = extract_methods!(policy_client::schema_metadata());
    let policy_tree = policy_client::scoped_client_tree();
    tool = tool.subcommand(build_service_command(
        "policy",
        &policy_methods,
        policy_tree,
    ));

    // Discovery intentionally exposes only its read-only health check here.
    // The remaining generated methods are service/bootstrap operations and are
    // not part of this diagnostic CLI surface.
    let discovery = Command::new("discovery")
        .about("Discovery health check")
        .subcommand(Command::new("ping").about("Health check"))
        .subcommand_required(true)
        .arg_required_else_help(true);
    tool = tool.subcommand(discovery);

    // Worker service + CRI-aligned scoped resources
    let worker_methods = extract_methods!(worker_client::schema_metadata());
    let worker_tree = worker_client::scoped_client_tree();
    tool = tool.subcommand(build_service_command(
        "worker",
        &worker_methods,
        worker_tree,
    ));

    // Workflow service
    let workflow_methods = extract_methods!(workflow_client::schema_metadata());
    let workflow_tree = workflow_client::scoped_client_tree();
    tool = tool.subcommand(build_service_command(
        "workflow",
        &workflow_methods,
        workflow_tree,
    ));

    tool
}

/// Handle a `tool` subcommand by extracting the service name and delegating.
pub async fn handle_tool_command(matches: &ArgMatches, signing_key: SigningKey) -> Result<()> {
    let (service_name, service_matches) = matches.subcommand().ok_or_else(|| {
        anyhow::anyhow!(
            "No service specified. Use: tool <registry|discovery|model|inference|policy|worker|workflow> ..."
        )
    })?;
    handle_schema_command(service_name, service_matches, signing_key).await
}

// ─────────────────────────────────────────────────────────────────────────────
// Dispatch schema commands
// ─────────────────────────────────────────────────────────────────────────────

/// Get the scoped client tree for a service.
fn get_service_tree(service: &str) -> &'static [ScopedClientTreeNode] {
    match service {
        "registry" => registry_client::scoped_client_tree(),
        "model" => model_client::scoped_client_tree(),
        "inference" => inference_client::scoped_client_tree(),
        "policy" => policy_client::scoped_client_tree(),
        "worker" => worker_client::scoped_client_tree(),
        "workflow" => workflow_client::scoped_client_tree(),
        _ => &[],
    }
}

/// Dispatch a schema-driven CLI command based on matched subcommands.
///
/// Supports recursive scoped commands (e.g., `registry repo <id> worktree <name> <method>`).
pub async fn handle_schema_command(
    service_name: &str,
    matches: &ArgMatches,
    signing_key: SigningKey,
) -> Result<()> {
    // Determine which subcommand was invoked
    let (sub_name, sub_matches) = matches
        .subcommand()
        .ok_or_else(|| anyhow::anyhow!("No subcommand provided for {}", service_name))?;

    let tree = get_service_tree(service_name);

    // Check if this is a scoped command by looking up the sub_name in the tree
    if let Some(node) = tree.iter().find(|n| n.scope_name == sub_name) {
        // Scoped: recursively walk scope chain
        let mut scope_chain: Vec<(&str, &str)> = Vec::new();
        let mut current_node = node;
        let mut current_matches = sub_matches;

        // Collect scope_id if this node has scope fields
        if !current_node.scope_field.is_empty() {
            let scope_id = current_matches
                .get_one::<String>("scope_id")
                .ok_or_else(|| anyhow::anyhow!("Missing scope ID for {}", sub_name))?;
            scope_chain.push((current_node.scope_name, scope_id.as_str()));
        } else {
            scope_chain.push((current_node.scope_name, ""));
        }

        loop {
            let (next_name, next_matches) = current_matches
                .subcommand()
                .ok_or_else(|| anyhow::anyhow!("No method provided"))?;

            // Check if next_name is a nested scope
            if let Some(nested_node) = current_node
                .nested
                .iter()
                .find(|n| n.scope_name == next_name)
            {
                // It's a deeper scope level
                if !nested_node.scope_field.is_empty() {
                    let nested_id = next_matches
                        .get_one::<String>("scope_id")
                        .ok_or_else(|| anyhow::anyhow!("Missing scope ID for {}", next_name))?;
                    scope_chain.push((nested_node.scope_name, nested_id.as_str()));
                } else {
                    scope_chain.push((nested_node.scope_name, ""));
                }
                current_node = nested_node;
                current_matches = next_matches;
            } else {
                // Reached the method — dispatch
                let method_snake = next_name.replace('-', "_");
                let methods = find_methods_in_tree(tree, &scope_chain);
                let args = matches_to_json(next_matches, &methods, &method_snake);

                let result = dispatch_scoped_dynamic(
                    service_name,
                    &scope_chain,
                    &method_snake,
                    &args,
                    signing_key,
                )
                .await?;

                println!("{}", format_response(&result));
                break;
            }
        }
    } else {
        // Top-level: e.g., "registry list"
        let method_snake = sub_name.replace('-', "_");
        let methods = get_top_level_methods(service_name);
        let args = matches_to_json(sub_matches, &methods, &method_snake);

        let result = dispatch_top_level(service_name, &method_snake, &args, signing_key).await?;
        println!("{}", format_response(&result));
    }

    Ok(())
}

/// Dispatch a top-level (non-scoped) method call.
async fn dispatch_top_level(
    service: &str,
    method: &str,
    args: &Value,
    signing_key: SigningKey,
) -> Result<Value> {
    match service {
        "registry" => {
            let client: RegistryClient = RegistryClient::from_resolver(signing_key, None)?;
            client.call_method(method, args).await
        }
        "model" => {
            let client = ModelClient::from_resolver(signing_key, None)?;
            client.call_method(method, args).await
        }
        "inference" => {
            let client = InferenceClient::from_resolver(signing_key, None)?;
            client.call_method(method, args).await
        }
        "policy" => {
            let client = super::policy_handlers::create_policy_client(&signing_key)?;
            client.call_method(method, args).await
        }
        "discovery" => {
            if method != "ping" {
                bail!("Discovery CLI exposes only the ping method")
            }
            let client = create_discovery_client(&signing_key)?;
            client.call_method(method, args).await
        }
        "worker" => {
            bail!("Worker service has no top-level methods. Use: tool worker <runtime|sandbox|container|image> <method>")
        }
        "workflow" => {
            // #989: WorkflowService factory is registered (default-off). The
            // factory still has to be started (`[worker.workflow] enabled = true`)
            // for this dispatch to reach a live service; `from_resolver` dials
            // the registered endpoint and errors clearly if nothing is listening.
            let client = workflow_client::WorkflowClient::from_resolver(signing_key, None)?;
            client.call_method(method, args).await
        }
        _ => bail!("Unknown service: {}", service),
    }
}

/// Construct the Discovery client using the process's already-selected
/// network profile. Required-native never falls back to a local endpoint;
/// Compatibility uses the installed service trust key and deterministic local
/// REP transport, which is the supported standalone CLI bootstrap path.
fn create_discovery_client(signing_key: &SigningKey) -> Result<DiscoveryClient> {
    create_discovery_client_for_profile(signing_key, hyprstream_discovery::native_network_required())
}

fn create_discovery_client_for_profile(
    signing_key: &SigningKey,
    network_required: bool,
) -> Result<DiscoveryClient> {
    if network_required {
        return DiscoveryClient::from_resolver(signing_key.clone(), None);
    }

    let discovery_key = hyprstream_service::global_trust_store()
        .resolve_one("discovery")
        .ok_or_else(|| anyhow::anyhow!("Discovery service trust key is not installed"))?;
    let registry = hyprstream_rpc::registry::try_global()
        .ok_or_else(|| anyhow::anyhow!("EndpointRegistry not initialized"))?;
    let transport = registry
        .try_endpoint("discovery", hyprstream_rpc::registry::SocketKind::Rep)
        .context("resolve local DiscoveryService REP endpoint")?;
    DiscoveryClient::for_local_transport_bootstrap(
        &transport,
        signing_key.clone(),
        discovery_key,
        None,
    )
}

/// Dispatch a scoped method call via `call_scoped_method` through the scope chain.
async fn dispatch_scoped_dynamic(
    service: &str,
    scope_chain: &[(&str, &str)],
    method: &str,
    args: &Value,
    signing_key: SigningKey,
) -> Result<Value> {
    match service {
        "registry" => {
            let client: RegistryClient = RegistryClient::from_resolver(signing_key, None)?;
            client.call_scoped_method(scope_chain, method, args).await
        }
        "model" => {
            let client = ModelClient::from_resolver(signing_key, None)?;
            client.call_scoped_method(scope_chain, method, args).await
        }
        "worker" => {
            let client = WorkerClient::from_resolver(signing_key, None)?;
            client.call_scoped_method(scope_chain, method, args).await
        }
        // "workflow" has no scoped sub-resources (unlike worker's
        // runtime/sandbox/container/image scopes) — its methods (list/dispatch/
        // getRun/…) are all top-level and dispatched via dispatch_dynamic.
        _ => bail!("Service '{}' has no scoped methods", service),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ArgMatches → JSON conversion
// ─────────────────────────────────────────────────────────────────────────────

/// Get the top-level methods for a service (used for type conversion).
fn get_top_level_methods(service: &str) -> Vec<MethodView> {
    match service {
        "registry" => extract_methods!(registry_client::schema_metadata()),
        "model" => extract_methods!(model_client::schema_metadata()),
        "inference" => extract_methods!(inference_client::schema_metadata()),
        "policy" => extract_methods!(policy_client::schema_metadata()),
        "worker" => extract_methods!(worker_client::schema_metadata()),
        "workflow" => extract_methods!(workflow_client::schema_metadata()),
        _ => Vec::new(),
    }
}

/// Find methods for a scope chain by walking the tree.
fn find_methods_in_tree(
    tree: &[ScopedClientTreeNode],
    scope_chain: &[(&str, &str)],
) -> Vec<MethodView> {
    if scope_chain.is_empty() {
        return vec![];
    }
    for node in tree {
        if node.scope_name == scope_chain[0].0 {
            if scope_chain.len() == 1 {
                return scoped_methods_to_views(node.metadata_fn);
            }
            return find_methods_in_tree(node.nested, &scope_chain[1..]);
        }
    }
    vec![]
}

/// Convert clap `ArgMatches` into a JSON object, using MethodView params for type coercion.
fn matches_to_json(matches: &ArgMatches, methods: &[MethodView], method_name: &str) -> Value {
    let method = methods.iter().find(|m| m.name == method_name);
    let mut map = serde_json::Map::new();

    if let Some(method) = method {
        for param in &method.params {
            if param.type_name == "Bool" {
                // Bool flags use get_flag() (ArgAction::SetTrue)
                let val = matches.get_flag(&param.name);
                map.insert(param.name.clone(), Value::Bool(val));
            } else if let Some(val) = matches.get_one::<String>(&param.name) {
                let json_val = coerce_value(val, &param.type_name);
                map.insert(param.name.clone(), json_val);
            }
        }
    } else {
        // Fallback: extract all string args
        for id in matches.ids() {
            if let Some(val) = matches.get_one::<String>(id.as_str()) {
                map.insert(id.to_string(), Value::String(val.clone()));
            }
        }
    }

    Value::Object(map)
}

/// Coerce a string value to the appropriate JSON type based on Cap'n Proto type name.
fn coerce_value(s: &str, type_name: &str) -> Value {
    match type_name {
        "Bool" => Value::Bool(s.parse().unwrap_or(false)),
        "UInt8" | "UInt16" | "UInt32" | "UInt64" => s
            .parse::<u64>()
            .map(Value::from)
            .unwrap_or_else(|_| Value::String(s.to_owned())),
        "Int8" | "Int16" | "Int32" | "Int64" => s
            .parse::<i64>()
            .map(Value::from)
            .unwrap_or_else(|_| Value::String(s.to_owned())),
        "Float32" | "Float64" => s
            .parse::<f64>()
            .map(Value::from)
            .unwrap_or_else(|_| Value::String(s.to_owned())),
        _ if type_name.starts_with("List(") => {
            // Split comma-separated values into a JSON array
            Value::Array(
                s.split(',')
                    .map(|v| Value::String(v.trim().to_owned()))
                    .collect(),
            )
        }
        _ => Value::String(s.to_owned()),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Response formatting
// ─────────────────────────────────────────────────────────────────────────────

/// Format a JSON value as a human-readable string for CLI output.
pub fn format_response(value: &Value) -> String {
    match value {
        Value::Null => "OK".to_owned(),
        Value::String(s) => s.clone(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::Array(arr) if arr.is_empty() => "(empty)".to_owned(),
        Value::Array(arr) => format_array_as_table(arr),
        Value::Object(obj) if obj.is_empty() => "OK".to_owned(),
        Value::Object(obj) => format_object_as_kv(obj),
    }
}

/// Format a JSON array as an aligned table.
fn format_array_as_table(arr: &[Value]) -> String {
    // If array of objects, format as columnar table
    if let Some(Value::Object(first)) = arr.first() {
        let keys: Vec<String> = first.keys().cloned().collect();

        // Calculate column widths
        let mut widths: Vec<usize> = keys.iter().map(std::string::String::len).collect();
        for item in arr {
            if let Value::Object(obj) = item {
                for (i, key) in keys.iter().enumerate() {
                    let val_len = format_cell(obj.get(key)).len();
                    if val_len > widths[i] {
                        widths[i] = val_len;
                    }
                }
            }
        }

        let mut out = String::new();

        // Header
        for (i, key) in keys.iter().enumerate() {
            if i > 0 {
                out.push_str("  ");
            }
            out.push_str(&format!(
                "{:<width$}",
                key.to_uppercase(),
                width = widths[i]
            ));
        }
        out.push('\n');

        // Separator
        for (i, width) in widths.iter().enumerate() {
            if i > 0 {
                out.push_str("  ");
            }
            for _ in 0..*width {
                out.push('-');
            }
        }
        out.push('\n');

        // Rows
        for item in arr {
            if let Value::Object(obj) = item {
                for (i, key) in keys.iter().enumerate() {
                    if i > 0 {
                        out.push_str("  ");
                    }
                    out.push_str(&format!(
                        "{:<width$}",
                        format_cell(obj.get(key)),
                        width = widths[i]
                    ));
                }
                out.push('\n');
            }
        }

        out.trim_end().to_owned()
    } else {
        // Array of primitives
        arr.iter()
            .map(|v| match v {
                Value::String(s) => s.clone(),
                other => other.to_string(),
            })
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Format a JSON object as aligned key-value pairs.
fn format_object_as_kv(obj: &serde_json::Map<String, Value>) -> String {
    if obj.is_empty() {
        return "OK".to_owned();
    }

    let max_key_len = obj.keys().map(std::string::String::len).max().unwrap_or(0);
    let mut out = String::new();

    for (key, value) in obj {
        out.push_str(&format!(
            "{:<width$}  {}\n",
            key,
            format_cell(Some(value)),
            width = max_key_len
        ));
    }

    out.trim_end().to_owned()
}

/// Format a single cell value for table output.
fn format_cell(value: Option<&Value>) -> String {
    match value {
        None | Some(Value::Null) => "-".to_owned(),
        Some(Value::String(s)) => s.clone(),
        Some(Value::Bool(b)) => b.to_string(),
        Some(Value::Number(n)) => n.to_string(),
        Some(Value::Array(arr)) => {
            let items: Vec<String> = arr
                .iter()
                .map(|v| match v {
                    Value::String(s) => s.clone(),
                    other => other.to_string(),
                })
                .collect();
            items.join(", ")
        }
        Some(Value::Object(obj)) => serde_json::to_string(obj).unwrap_or_else(|_| "{}".to_owned()),
    }
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::unwrap_used)]
mod tests {
    use super::*;

    fn test_signing_key() -> SigningKey {
        SigningKey::from_bytes(&[7u8; 32])
    }

    #[test]
    fn discovery_cli_exposes_only_ping() {
        let command = build_tool_command();
        command
            .clone()
            .try_get_matches_from(["tool", "discovery", "ping"])
            .expect("discovery ping must be a valid CLI command");
        command
            .try_get_matches_from(["tool", "discovery", "list-services"])
            .expect_err("Discovery management methods must stay outside this CLI");
        assert!(get_service_tree("discovery").is_empty());
    }

    #[tokio::test]
    async fn compatibility_ping_command_denies_without_trusted_local_service() {
        // Run the assertion in a fresh test process so unrelated tests cannot
        // install a process-global resolver and turn this into a false pass.
        if std::env::var_os("HYPRSTREAM_DISCOVERY_PING_DENIAL_CHILD").is_none() {
            let status = std::process::Command::new(std::env::current_exe().unwrap())
                .args([
                    "--exact",
                    "cli::schema_cli::tests::compatibility_ping_command_denies_without_trusted_local_service",
                    "--nocapture",
                ])
                .env("HYPRSTREAM_DISCOVERY_PING_DENIAL_CHILD", "1")
                .status()
                .unwrap();
            assert!(status.success(), "isolated denial child failed: {status}");
            return;
        }

        let matches = build_tool_command()
            .try_get_matches_from(["tool", "discovery", "ping"])
            .unwrap();
        let (_, service_matches) = matches.subcommand().unwrap();
        let error = handle_schema_command("discovery", service_matches, test_signing_key())
            .await
            .expect_err("ping must fail closed when no resolver is installed");
        let text = error.to_string();
        assert!(text.contains("Discovery service trust key is not installed"), "unexpected compatibility denial: {text}");
    }

    #[tokio::test]
    async fn required_native_ping_denies_without_resolver_and_never_uses_local_fallback() {
        if std::env::var_os("HYPRSTREAM_DISCOVERY_PING_REQUIRED_CHILD").is_none() {
            let status = std::process::Command::new(std::env::current_exe().unwrap())
                .args([
                    "--exact",
                    "cli::schema_cli::tests::required_native_ping_denies_without_resolver_and_never_uses_local_fallback",
                    "--nocapture",
                ])
                .env("HYPRSTREAM_DISCOVERY_PING_REQUIRED_CHILD", "1")
                .status()
                .unwrap();
            assert!(status.success(), "isolated required-mode child failed: {status}");
            return;
        }

        let error = match create_discovery_client_for_profile(&test_signing_key(), true) {
            Ok(_) => panic!("required-native Discovery must require resolver evidence"),
            Err(error) => error,
        };
        let text = error.to_string();
        assert!(
            text.contains("resolver") || text.contains("validated alternative"),
            "unexpected required-native denial: {text}"
        );
    }

    #[tokio::test]
    async fn compatibility_ping_uses_trusted_local_discovery_service() {
        // Keep the process-global registry and trust store isolated from the
        // rest of the test suite while exercising the real command path.
        if std::env::var_os("HYPRSTREAM_DISCOVERY_PING_COMPAT_CHILD").is_none() {
            let status = std::process::Command::new(std::env::current_exe().unwrap())
                .args([
                    "--exact",
                    "cli::schema_cli::tests::compatibility_ping_uses_trusted_local_discovery_service",
                    "--nocapture",
                ])
                .env("HYPRSTREAM_DISCOVERY_PING_COMPAT_CHILD", "1")
                .status()
                .unwrap();
            assert!(status.success(), "isolated compatibility child failed: {status}");
            return;
        }

        use std::collections::HashSet;
        use std::sync::Arc;
        use tokio::sync::{oneshot, Notify};

        crate::mac::install_explicit_test_dispatch_pep();
        let service_key = SigningKey::from_bytes(&[9u8; 32]);
        let caller_key = test_signing_key();
        let caller_pq = hyprstream_rpc::node_identity::derive_mesh_mldsa_key(&caller_key);
        let caller_pq_vk = hyprstream_rpc::crypto::pq::ml_dsa_vk_from_bytes(
            &hyprstream_rpc::crypto::pq::ml_dsa_sk_to_vk_bytes(&caller_pq),
        )
        .unwrap();
        let service_pq = hyprstream_rpc::node_identity::derive_mesh_mldsa_key(&service_key);
        let service_pq_vk = hyprstream_rpc::crypto::pq::ml_dsa_vk_from_bytes(
            &hyprstream_rpc::crypto::pq::ml_dsa_sk_to_vk_bytes(&service_pq),
        )
        .unwrap();
        let mut pq_store = hyprstream_rpc::envelope::KeyedPqTrustStore::new();
        pq_store.bind(caller_key.verifying_key().to_bytes(), &caller_pq_vk);
        pq_store.bind(service_key.verifying_key().to_bytes(), &service_pq_vk);
        let _ = hyprstream_rpc::envelope::install_verify_config(
            hyprstream_rpc::envelope::EnvelopeVerifyConfig {
                policy: hyprstream_rpc::crypto::CryptoPolicy::Hybrid,
                pq_store: Some(Arc::new(pq_store)),
            },
        );
        let mut response_pq_store = hyprstream_rpc::envelope::KeyedPqTrustStore::new();
        response_pq_store.bind(service_key.verifying_key().to_bytes(), &service_pq_vk);
        let _ = hyprstream_rpc::envelope::install_response_verify_config(
            hyprstream_rpc::envelope::ResponseVerifyConfig {
                policy: hyprstream_rpc::crypto::CryptoPolicy::Hybrid,
                pq_store: Some(Arc::new(response_pq_store)),
            },
        );
        let runtime_dir = tempfile::tempdir().unwrap();
        let transport = hyprstream_rpc::transport::TransportConfig::ipc(
            runtime_dir.path().join("discovery.sock"),
        );
        hyprstream_rpc::registry::init(
            hyprstream_rpc::registry::EndpointMode::Ipc,
            Some(runtime_dir.path().to_owned()),
        );
        hyprstream_service::global_trust_store().insert(
            service_key.verifying_key(),
            hyprstream_service::Attestation {
                scopes: HashSet::from(["discovery".to_owned()]),
                subject: None,
                jwt: None,
                expires_at: 0,
                attested_by: None,
            },
        );

        let service = hyprstream_discovery::DiscoveryService::new(
            Arc::new(service_key.clone()),
            service_key.verifying_key(),
            transport.clone(),
        )
        .with_auth_provider(Box::new(CompatAllowAll));
        let bridge = Arc::new(hyprstream_rpc::transport::iroh_rpc::LocalServiceBridge::spawn(
            service,
            Arc::new(hyprstream_rpc::envelope::InMemoryNonceCache::new()),
            0,
        )
        .unwrap());
        let shutdown = Arc::new(Notify::new());
        let (ready_tx, ready_rx) = oneshot::channel();
        let server_shutdown = Arc::clone(&shutdown);
        let server_transport = transport.clone();
        let server_bridge = Arc::clone(&bridge);
        let server = tokio::spawn(async move {
            hyprstream_rpc::service::serve::serve_bridged(
                &server_transport,
                server_bridge,
                service_key,
                server_shutdown,
                Some(ready_tx),
            )
            .await
        });
        ready_rx.await.unwrap();

        let matches = build_tool_command()
            .try_get_matches_from(["tool", "discovery", "ping"])
            .unwrap();
        let (_, service_matches) = matches.subcommand().unwrap();
        handle_schema_command("discovery", service_matches, caller_key.clone())
            .await
            .expect("compatibility ping should reach the local generated service");

        let args = Value::Object(serde_json::Map::new());
        let result = dispatch_top_level("discovery", "ping", &args, caller_key)
            .await
            .expect("generated Discovery ping should return a response");
        assert_eq!(result["status"], "ok");
        assert!(result["serviceCount"].as_u64().is_some());
        assert!(result["uptime"].as_u64().is_some());

        shutdown.notify_waiters();
        server.await.unwrap().unwrap();
        bridge.shutdown().await.unwrap();
    }

    struct CompatAllowAll;

    #[async_trait::async_trait(?Send)]
    impl hyprstream_discovery::AuthorizationProvider for CompatAllowAll {
        async fn check(
            &self,
            _subject: &str,
            _domain: &str,
            _resource: &str,
            _operation: &str,
            _bearer: Option<&str>,
        ) -> Result<bool> {
            Ok(true)
        }
    }
}
