//! Reusable synthetic 9P filesystem for services.
//!
//! Services that expose a synthetic file tree (model status, tool schemas, etc.)
//! construct a `SyntheticTree` at startup, register nodes, and delegate 9P
//! operations to it. The tree handles fid allocation, walk resolution,
//! open/read/write dispatch, and idle fid reaping.
//!
//! This is the synthetic counterpart to the registry's real-filesystem 9P handler.
//! No real files — all content is generated by closures.

use std::collections::{HashMap, VecDeque};
use std::sync::atomic::{AtomicU32, AtomicU64, Ordering::Relaxed};

use dashmap::DashMap;
use parking_lot::Mutex;

use crate::services::types::{DEFAULT_IOUNIT, QTDIR, QTFILE};
use hyprstream_vfs::DirEntry;

// ─────────────────────────────────────────────────────────────────────────────
// Synthetic node types
// ─────────────────────────────────────────────────────────────────────────────

/// A node in the synthetic file tree.
pub enum SyntheticNode {
    /// Static directory with fixed children.
    Dir {
        children: HashMap<String, SyntheticNode>,
    },
    /// Directory whose children are computed dynamically (e.g., model list).
    DynamicDir {
        list: Box<dyn Fn() -> Vec<DirEntry> + Send + Sync>,
        /// Resolve a child name to a subtree (called after walk finds a dynamic entry).
        resolve: Box<dyn Fn(&str) -> Option<SyntheticNode> + Send + Sync>,
    },
    /// Read-only file whose content is generated on read.
    ReadFile(Box<dyn Fn() -> Vec<u8> + Send + Sync>),
    /// Control file: write input, read response. Mutations go here (Plan9 ctl pattern).
    CtlFile {
        handler: Box<dyn Fn(&[u8]) -> Result<Vec<u8>, String> + Send + Sync>,
    },
}

// ─────────────────────────────────────────────────────────────────────────────
// Qid generation for synthetic nodes
// ─────────────────────────────────────────────────────────────────────────────

/// Synthetic Qid: deterministic hash of path as inode, monotonic version.
#[derive(Clone, Debug)]
pub struct SyntheticQid {
    pub qtype: u8,
    pub version: u32,
    pub path: u64,
}

impl SyntheticQid {
    pub fn dir(path_str: &str) -> Self {
        Self { qtype: QTDIR, version: 1, path: hash_path(path_str) }
    }

    pub fn file(path_str: &str) -> Self {
        Self { qtype: QTFILE, version: 1, path: hash_path(path_str) }
    }
}

fn hash_path(path: &str) -> u64 {
    // FNV-1a 64-bit hash — fast, deterministic, no crypto dependency.
    let mut h: u64 = 0xcbf29ce484222325;
    for b in path.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

// ─────────────────────────────────────────────────────────────────────────────
// Fid table
// ─────────────────────────────────────────────────────────────────────────────

/// What a fid's node resolves to (for read/write dispatch).
enum ResolvedNode {
    /// Path into the static tree — resolve at read time via resolve_node.
    Static(Vec<String>),
    /// A dynamically-resolved node cached at walk time.
    Dynamic(SyntheticNode),
}

enum FidState {
    Walked {
        resolved: ResolvedNode,
        qid: SyntheticQid,
    },
    Opened {
        resolved: ResolvedNode,
        qid: SyntheticQid,
        mode: u8,
        /// Buffer for ctl file responses (written by handler, drained by read).
        response_buf: Mutex<VecDeque<u8>>,
    },
}

struct FidEntry {
    state: FidState,
    owner: String,
    last_accessed: AtomicU64,
}

/// Fid table for synthetic filesystem. Per-client fid counts and idle reaping.
pub struct SyntheticFidTable {
    next_fid: AtomicU32,
    fids: DashMap<u32, FidEntry>,
    client_counts: DashMap<String, AtomicU32>,
}

impl Default for SyntheticFidTable {
    fn default() -> Self { Self::new() }
}

impl SyntheticFidTable {
    pub fn new() -> Self {
        Self {
            next_fid: AtomicU32::new(1),
            fids: DashMap::new(),
            client_counts: DashMap::new(),
        }
    }

    fn alloc_fid(&self, owner: &str) -> Result<u32, &'static str> {
        use std::sync::atomic::Ordering::{AcqRel, Acquire};
        let count = self.client_counts
            .entry(owner.to_owned())
            .or_insert_with(|| AtomicU32::new(0));
        // Atomic check-and-increment to prevent exceeding per-client limit on ARM.
        if count.fetch_update(AcqRel, Acquire, |c| {
            if c >= crate::services::types::MAX_FIDS_PER_CLIENT { None } else { Some(c + 1) }
        }).is_err() {
            return Err("too many open fids");
        }
        if self.fids.len() as u32 >= crate::services::types::MAX_FIDS_GLOBAL {
            count.fetch_sub(1, AcqRel);
            return Err("global fid limit reached");
        }
        // Retry on collision using atomic entry() to avoid TOCTOU.
        for _ in 0..1000 {
            let fid = self.next_fid.fetch_add(1, Relaxed);
            if fid == 0 { continue; } // 0 is reserved for root
            if let dashmap::mapref::entry::Entry::Vacant(_) = self.fids.entry(fid) {
                // Fid is available — caller will insert via insert_at().
                return Ok(fid);
            }
        }
        count.fetch_sub(1, AcqRel);
        Err("fid allocation failed after retries")
    }

    fn insert(&self, fid: u32, entry: FidEntry) {
        self.fids.insert(fid, entry);
    }

    fn get_verified(&self, fid: u32, owner: &str) -> Result<dashmap::mapref::one::Ref<'_, u32, FidEntry>, &'static str> {
        let entry = self.fids.get(&fid).ok_or("fid not found")?;
        if entry.owner != owner {
            return Err("fid not owned by caller");
        }
        entry.last_accessed.store(now_secs(), Relaxed);
        Ok(entry)
    }

    fn take(&self, fid: u32, owner: &str) -> Result<FidEntry, &'static str> {
        // Atomic remove-if-owned to avoid TOCTOU between remove and ownership check.
        let removed = self.fids.remove_if(&fid, |_, entry| entry.owner == owner);
        match removed {
            Some((_, entry)) => Ok(entry),
            None => {
                // Either fid doesn't exist or wrong owner.
                if self.fids.contains_key(&fid) {
                    Err("fid not owned by caller")
                } else {
                    Err("fid not found")
                }
            }
        }
    }

    fn remove(&self, fid: u32, owner: &str) {
        if let Some((_, entry)) = self.fids.remove(&fid) {
            if entry.owner == owner {
                if let Some(count) = self.client_counts.get(&entry.owner) {
                    count.fetch_sub(1, Relaxed);
                }
            } else {
                // Wrong owner — put it back.
                self.fids.insert(fid, entry);
            }
        }
    }

    /// Reap fids idle for more than `max_idle_secs`.
    pub fn reap(&self, max_idle_secs: u64) {
        let now = now_secs();
        self.fids.retain(|_fid, entry| {
            let idle = now.saturating_sub(entry.last_accessed.load(Relaxed));
            if idle > max_idle_secs {
                if let Some(count) = self.client_counts.get(&entry.owner) {
                    count.fetch_sub(1, Relaxed);
                }
                false
            } else {
                true
            }
        });
    }
}

fn now_secs() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

// ─────────────────────────────────────────────────────────────────────────────
// SyntheticTree
// ─────────────────────────────────────────────────────────────────────────────

/// A synthetic 9P file tree backed by closures.
///
/// Services construct a tree at startup, then delegate 9P walk/open/read/write
/// operations to it. All state is in the fid table; the tree itself is immutable
/// after construction.
pub struct SyntheticTree {
    root: SyntheticNode,
    fid_table: SyntheticFidTable,
}

impl SyntheticTree {
    pub fn new(root: SyntheticNode) -> Self {
        Self {
            root,
            fid_table: SyntheticFidTable::new(),
        }
    }

    /// Walk path components from root.
    ///
    /// If `newfid` is Some and > 0, uses the client-chosen fid (9P protocol).
    /// If `newfid` is None or 0, auto-allocates a server-side fid.
    pub fn walk(&self, wnames: &[String], owner: &str, newfid: Option<u32>) -> Result<(u32, SyntheticQid), String> {
        let fid = match newfid {
            Some(f) if f > 0 => {
                // Client-chosen fid — check not already in use, count against limits.
                if self.fid_table.fids.contains_key(&f) {
                    return Err("fid already in use".to_owned());
                }
                use std::sync::atomic::Ordering::{AcqRel, Acquire};
                let count = self.fid_table.client_counts
                    .entry(owner.to_owned())
                    .or_insert_with(|| AtomicU32::new(0));
                if count.fetch_update(AcqRel, Acquire, |c| {
                    if c >= crate::services::types::MAX_FIDS_PER_CLIENT { None } else { Some(c + 1) }
                }).is_err() {
                    return Err("too many open fids".to_owned());
                }
                f
            }
            _ => self.fid_table.alloc_fid(owner).map_err(str::to_owned)?,
        };

        let (qid, resolved) = if wnames.is_empty() {
            (SyntheticQid::dir("/"), ResolvedNode::Static(vec![]))
        } else {
            self.resolve_walk(wnames)?
        };

        self.fid_table.insert(fid, FidEntry {
            state: FidState::Walked { resolved, qid: qid.clone() },
            owner: owner.to_owned(),
            last_accessed: AtomicU64::new(now_secs()),
        });

        Ok((fid, qid))
    }

    /// Open a walked fid for I/O.
    pub fn open(&self, fid: u32, mode: u8, owner: &str) -> Result<(SyntheticQid, u32), String> {
        let entry = self.fid_table.take(fid, owner)?;
        match entry.state {
            FidState::Walked { resolved, qid } => {
                let new_entry = FidEntry {
                    state: FidState::Opened {
                        resolved,
                        qid: qid.clone(),
                        mode,
                        response_buf: Mutex::new(VecDeque::new()),
                    },
                    owner: entry.owner,
                    last_accessed: AtomicU64::new(now_secs()),
                };
                self.fid_table.insert(fid, new_entry);
                Ok((qid, DEFAULT_IOUNIT))
            }
            FidState::Opened { .. } => {
                self.fid_table.insert(fid, entry);
                Err("fid already open".to_owned())
            }
        }
    }

    /// Read from an opened fid.
    ///
    /// For Static resolved nodes, the DashMap guard is dropped before calling
    /// the content-generation closure to avoid holding shard locks during I/O.
    /// For Dynamic nodes (captured closures), the guard is held — closures
    /// MUST be non-blocking (in-memory operations only).
    pub fn read(&self, fid: u32, offset: u64, count: u32, owner: &str) -> Result<Vec<u8>, String> {
        // First, check for buffered ctl response data (quick path, minimal lock scope).
        {
            let entry = self.fid_table.get_verified(fid, owner)?;
            if let FidState::Opened { response_buf, .. } = &entry.state {
                let mut buf = response_buf.lock();
                if !buf.is_empty() {
                    let n = std::cmp::min(count as usize, buf.len());
                    let data: Vec<u8> = buf.drain(..n).collect();
                    return Ok(data);
                }
            } else {
                return Err("fid not open".to_owned());
            }
        } // DashMap guard dropped here.

        // For Static paths, extract the path and drop the guard before resolving.
        let entry = self.fid_table.get_verified(fid, owner)?;
        let resolved = match &entry.state {
            FidState::Opened { resolved, .. } => resolved,
            _ => return Err("fid not open".to_owned()),
        };

        match resolved {
            ResolvedNode::Static(path) => {
                let path_clone = path.clone();
                drop(entry); // Release DashMap guard before calling closures.
                let node = self.resolve_node(&path_clone);
                self.read_from_node(node, offset, count)
            }
            ResolvedNode::Dynamic(node) => {
                // Guard held — closures must be non-blocking.
                self.read_from_node(Some(node), offset, count)
            }
        }
    }

    fn read_from_node(&self, node: Option<&SyntheticNode>, offset: u64, count: u32) -> Result<Vec<u8>, String> {
        match node {
            Some(SyntheticNode::ReadFile(gen)) => {
                let content = gen();
                let start = std::cmp::min(offset as usize, content.len());
                let end = std::cmp::min(start + count as usize, content.len());
                Ok(content[start..end].to_vec())
            }
            Some(SyntheticNode::Dir { children }) => {
                if offset > 0 { return Ok(vec![]); }
                Ok(encode_dir_entries(
                    &children.keys().map(|k| DirEntry {
                        name: k.clone(),
                        is_dir: matches!(children.get(k), Some(SyntheticNode::Dir { .. } | SyntheticNode::DynamicDir { .. })),
                        size: 0,
                        stat: None,
                    }).collect::<Vec<_>>(),
                    count,
                ))
            }
            Some(SyntheticNode::DynamicDir { list, .. }) => {
                if offset > 0 { return Ok(vec![]); }
                Ok(encode_dir_entries(&list(), count))
            }
            Some(SyntheticNode::CtlFile { .. }) => Ok(vec![]),
            None => Err("path not found in tree".to_owned()),
        }
    }

    /// Read directory entries as structured data (for Mount bridge).
    pub fn readdir_entries(&self, fid: u32, owner: &str) -> Result<Vec<DirEntry>, String> {
        let entry = self.fid_table.get_verified(fid, owner)?;
        let resolved = match &entry.state {
            FidState::Opened { resolved, .. } => resolved,
            _ => return Err("fid not open".to_owned()),
        };

        match resolved {
            ResolvedNode::Static(path) => {
                let path_clone = path.clone();
                drop(entry);
                let node = self.resolve_node(&path_clone);
                self.readdir_from_node(node)
            }
            ResolvedNode::Dynamic(node) => self.readdir_from_node(Some(node)),
        }
    }

    fn readdir_from_node(&self, node: Option<&SyntheticNode>) -> Result<Vec<DirEntry>, String> {
        match node {
            Some(SyntheticNode::Dir { children }) => {
                Ok(children.keys().map(|k| DirEntry {
                    name: k.clone(),
                    is_dir: matches!(children.get(k), Some(SyntheticNode::Dir { .. } | SyntheticNode::DynamicDir { .. })),
                    size: 0,
                    stat: None,
                }).collect())
            }
            Some(SyntheticNode::DynamicDir { list, .. }) => Ok(list()),
            _ => Err("not a directory".to_owned()),
        }
    }

    /// Maximum ctl response buffer size per fid (256 KB).
    const MAX_RESPONSE_BUF: usize = 256 * 1024;

    /// Write to an opened fid.
    ///
    /// For ctl files, the handler closure is invoked and the response is buffered
    /// for subsequent reads. Response buffer is capped at MAX_RESPONSE_BUF.
    pub fn write(&self, fid: u32, _offset: u64, data: &[u8], owner: &str) -> Result<u32, String> {
        let entry = self.fid_table.get_verified(fid, owner)?;
        match &entry.state {
            FidState::Opened { resolved, mode, response_buf, .. } => {
                let base_mode = *mode & 0x03;
                if base_mode != hyprstream_vfs::OWRITE && base_mode != hyprstream_vfs::ORDWR {
                    return Err("fid not open for writing".to_owned());
                }
                let node = match resolved {
                    ResolvedNode::Static(path) => self.resolve_node(path),
                    ResolvedNode::Dynamic(node) => Some(node),
                };
                match node {
                    Some(SyntheticNode::CtlFile { handler }) => {
                        let result = handler(data)?;
                        let written = data.len() as u32;
                        let mut buf = response_buf.lock();
                        // Clear old response on new write (Plan9 convention: each write is a new command).
                        buf.clear();
                        let cap = Self::MAX_RESPONSE_BUF.min(result.len());
                        buf.extend(&result[..cap]);
                        Ok(written)
                    }
                    _ => Err("path not writable".to_owned()),
                }
            }
            _ => Err("fid not open".to_owned()),
        }
    }

    /// Stat a walked or opened fid.
    pub fn stat(&self, fid: u32, owner: &str) -> Result<(SyntheticQid, String), String> {
        let entry = self.fid_table.get_verified(fid, owner)?;
        let qid = match &entry.state {
            FidState::Walked { qid, .. } | FidState::Opened { qid, .. } => qid.clone(),
        };
        // Extract name from the qid path hash — not ideal, but we don't store the path anymore
        // for dynamic nodes. Return empty name for now; callers that need the name should
        // track it separately.
        Ok((qid, String::new()))
    }

    /// Release a fid.
    pub fn clunk(&self, fid: u32, owner: &str) {
        self.fid_table.remove(fid, owner);
    }

    /// Reap idle fids (call periodically from a background task).
    pub fn reap(&self, max_idle_secs: u64) {
        self.fid_table.reap(max_idle_secs);
    }

    // ── Internal ────────────────────────────────────────────────────────────

    /// Resolve a walk, returning a Qid and a ResolvedNode for the fid.
    /// Static paths get `ResolvedNode::Static` (resolved at read time).
    /// Paths through DynamicDir get `ResolvedNode::Dynamic` (cached subtree).
    fn resolve_walk(&self, components: &[String]) -> Result<(SyntheticQid, ResolvedNode), String> {
        let mut current = &self.root;
        let mut static_path = Vec::new();

        for (i, name) in components.iter().enumerate() {
            match current {
                SyntheticNode::Dir { children } => {
                    if let Some(child) = children.get(name) {
                        static_path.push(name.clone());
                        current = child;
                    } else {
                        return Err(format!("not found: {}", components[..=i].join("/")));
                    }
                }
                SyntheticNode::DynamicDir { list, resolve } => {
                    let entries = list();
                    if !entries.iter().any(|e| e.name == *name) {
                        return Err(format!("not found in dynamic dir: {}", name));
                    }

                    // Resolve the child and walk remaining components through it.
                    let remaining = &components[i + 1..];
                    return self.resolve_dynamic_leaf(resolve.as_ref(), name, remaining);
                }
                _ => {
                    return Err(format!("not a directory: {}", components[..i].join("/")));
                }
            }
        }

        // Walked all static components.
        let full_path = static_path.join("/");
        let qid = match current {
            SyntheticNode::Dir { .. } | SyntheticNode::DynamicDir { .. } => SyntheticQid::dir(&full_path),
            _ => SyntheticQid::file(&full_path),
        };
        Ok((qid, ResolvedNode::Static(static_path)))
    }

    /// Resolve a leaf node through a dynamic dir by walking remaining components
    /// through a freshly-resolved subtree, returning the leaf as an owned Dynamic node.
    fn resolve_dynamic_leaf(
        &self,
        resolve: &dyn Fn(&str) -> Option<SyntheticNode>,
        parent_name: &str,
        remaining: &[String],
    ) -> Result<(SyntheticQid, ResolvedNode), String> {
        let subtree = resolve(parent_name)
            .ok_or("cannot resolve dynamic child")?;

        // Walk remaining components through the subtree.
        let mut current = subtree;
        for (i, name) in remaining.iter().enumerate() {
            match current {
                SyntheticNode::Dir { mut children } => {
                    current = children.remove(name)
                        .ok_or_else(|| format!("not found: {}", name))?;
                }
                _ => return Err(format!("not a directory at: {}", remaining[..i].join("/"))),
            }
        }

        let full_path = remaining.join("/");
        let qid = match &current {
            SyntheticNode::Dir { .. } | SyntheticNode::DynamicDir { .. } => SyntheticQid::dir(&full_path),
            _ => SyntheticQid::file(&full_path),
        };
        Ok((qid, ResolvedNode::Dynamic(current)))
    }

    fn resolve_node<'a>(&'a self, path: &[String]) -> Option<&'a SyntheticNode> {
        let mut current = &self.root;
        for name in path {
            match current {
                SyntheticNode::Dir { children } => {
                    current = children.get(name)?;
                }
                _ => return None,
            }
        }
        Some(current)
    }
}

/// Encode directory entries in the 9P wire format used by the registry.
fn encode_dir_entries(entries: &[DirEntry], max_bytes: u32) -> Vec<u8> {
    let mut wire = Vec::new();
    for entry in entries {
        let name_bytes = entry.name.as_bytes();
        let entry_size = 4 + name_bytes.len() + 1 + 8; // name_len + name + is_dir + size
        if wire.len() + entry_size > max_bytes as usize {
            break;
        }
        wire.extend_from_slice(&(name_bytes.len() as u32).to_le_bytes());
        wire.extend_from_slice(name_bytes);
        wire.push(if entry.is_dir { 1 } else { 0 });
        wire.extend_from_slice(&entry.size.to_le_bytes());
    }
    wire
}

// ─────────────────────────────────────────────────────────────────────────────
// Mount implementation — bridges SyntheticTree to the VFS crate
// ─────────────────────────────────────────────────────────────────────────────

impl hyprstream_vfs::Mount for SyntheticTree {
    fn walk(&self, components: &[&str], caller: &hyprstream_rpc::Subject) -> Result<hyprstream_vfs::Fid, hyprstream_vfs::MountError> {
        let wnames: Vec<String> = components.iter().map(|s| (*s).to_owned()).collect();
        let owner = caller.to_string();
        let (fid, _qid) = self.walk(&wnames, &owner, None).map_err(|e| hyprstream_vfs::MountError::NotFound(e))?;
        Ok(hyprstream_vfs::Fid::new(fid))
    }

    fn open(&self, fid: &mut hyprstream_vfs::Fid, mode: u8, caller: &hyprstream_rpc::Subject) -> Result<(), hyprstream_vfs::MountError> {
        let fid_u32 = *fid.downcast_ref::<u32>().ok_or_else(|| hyprstream_vfs::MountError::InvalidArgument("invalid fid type".into()))?;
        let owner = caller.to_string();
        self.open(fid_u32, mode, &owner).map_err(|e| hyprstream_vfs::MountError::Io(e))?;
        Ok(())
    }

    fn read(&self, fid: &hyprstream_vfs::Fid, offset: u64, count: u32, caller: &hyprstream_rpc::Subject) -> Result<Vec<u8>, hyprstream_vfs::MountError> {
        let fid_u32 = *fid.downcast_ref::<u32>().ok_or_else(|| hyprstream_vfs::MountError::InvalidArgument("invalid fid type".into()))?;
        self.read(fid_u32, offset, count, &caller.to_string()).map_err(|e| hyprstream_vfs::MountError::Io(e))
    }

    fn write(&self, fid: &hyprstream_vfs::Fid, offset: u64, data: &[u8], caller: &hyprstream_rpc::Subject) -> Result<u32, hyprstream_vfs::MountError> {
        let fid_u32 = *fid.downcast_ref::<u32>().ok_or_else(|| hyprstream_vfs::MountError::InvalidArgument("invalid fid type".into()))?;
        self.write(fid_u32, offset, data, &caller.to_string()).map_err(|e| hyprstream_vfs::MountError::Io(e))
    }

    fn readdir(&self, fid: &hyprstream_vfs::Fid, caller: &hyprstream_rpc::Subject) -> Result<Vec<hyprstream_vfs::DirEntry>, hyprstream_vfs::MountError> {
        let fid_u32 = *fid.downcast_ref::<u32>().ok_or_else(|| hyprstream_vfs::MountError::InvalidArgument("invalid fid type".into()))?;
        let entries = self.readdir_entries(fid_u32, &caller.to_string()).map_err(|e| hyprstream_vfs::MountError::Io(e))?;
        Ok(entries)
    }

    fn stat(&self, fid: &hyprstream_vfs::Fid, caller: &hyprstream_rpc::Subject) -> Result<hyprstream_vfs::Stat, hyprstream_vfs::MountError> {
        let fid_u32 = *fid.downcast_ref::<u32>().ok_or_else(|| hyprstream_vfs::MountError::InvalidArgument("invalid fid type".into()))?;
        let (qid, name) = self.stat(fid_u32, &caller.to_string()).map_err(|e| hyprstream_vfs::MountError::Io(e))?;
        Ok(hyprstream_vfs::Stat {
            qtype: qid.qtype,
            size: 0,
            name,
            mtime: 0,
        })
    }

    fn clunk(&self, fid: hyprstream_vfs::Fid, caller: &hyprstream_rpc::Subject) {
        if let Some(fid_u32) = fid.downcast_ref::<u32>() {
            self.clunk(*fid_u32, &caller.to_string());
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use crate::services::types::OREAD;
    use hyprstream_vfs::OWRITE;

    fn make_tree() -> SyntheticTree {
        let mut children = HashMap::new();
        children.insert("status".to_owned(), SyntheticNode::ReadFile(
            Box::new(|| b"loaded\n".to_vec()),
        ));
        children.insert("ctl".to_owned(), SyntheticNode::CtlFile {
            handler: Box::new(|data| {
                let cmd = String::from_utf8_lossy(data);
                Ok(format!("ok: {}", cmd.trim()).into_bytes())
            }),
        });

        let mut root_children = HashMap::new();
        root_children.insert("test-model".to_owned(), SyntheticNode::Dir { children });

        SyntheticTree::new(SyntheticNode::Dir { children: root_children })
    }

    #[test]
    fn walk_and_read_file() {
        let tree = make_tree();
        let (fid, qid) = tree.walk(&["test-model".into(), "status".into()], "alice", None).unwrap();
        assert_eq!(qid.qtype, QTFILE);
        tree.open(fid, OREAD, "alice").unwrap();
        let data = tree.read(fid, 0, 1024, "alice").unwrap();
        assert_eq!(data, b"loaded\n");
        tree.clunk(fid, "alice");
    }

    #[test]
    fn walk_root_and_readdir() {
        let tree = make_tree();
        let (fid, qid) = tree.walk(&[], "alice", None).unwrap();
        assert_eq!(qid.qtype, QTDIR);
        tree.open(fid, OREAD, "alice").unwrap();
        let data = tree.read(fid, 0, 4096, "alice").unwrap();
        assert!(!data.is_empty()); // Should contain "test-model" entry.
        tree.clunk(fid, "alice");
    }

    #[test]
    fn ctl_write_then_read() {
        let tree = make_tree();
        let (fid, _) = tree.walk(&["test-model".into(), "ctl".into()], "alice", None).unwrap();
        tree.open(fid, OWRITE, "alice").unwrap();
        let written = tree.write(fid, 0, b"load", "alice").unwrap();
        assert_eq!(written, 4);
        // Read the response.
        let resp = tree.read(fid, 0, 1024, "alice").unwrap();
        assert_eq!(resp, b"ok: load");
        tree.clunk(fid, "alice");
    }

    #[test]
    fn fid_ownership_enforced() {
        let tree = make_tree();
        let (fid, _) = tree.walk(&["test-model".into(), "status".into()], "alice", None).unwrap();
        assert!(tree.open(fid, OREAD, "bob").is_err());
        tree.clunk(fid, "alice");
    }

    #[test]
    fn walk_not_found() {
        let tree = make_tree();
        assert!(tree.walk(&["nonexistent".into()], "alice", None).is_err());
    }

    #[test]
    fn stat_returns_qid() {
        let tree = make_tree();
        let (fid, _) = tree.walk(&["test-model".into(), "status".into()], "alice", None).unwrap();
        let (qid, _name) = tree.stat(fid, "alice").unwrap();
        assert_eq!(qid.qtype, QTFILE);
        tree.clunk(fid, "alice");
    }

    #[test]
    fn dynamic_dir() {
        let tree = SyntheticTree::new(SyntheticNode::DynamicDir {
            list: Box::new(|| vec![
                DirEntry { name: "model-a".into(), is_dir: true, size: 0, stat: None },
                DirEntry { name: "model-b".into(), is_dir: true, size: 0, stat: None },
            ]),
            resolve: Box::new(|_name| {
                let mut children = HashMap::new();
                children.insert("status".to_owned(), SyntheticNode::ReadFile(
                    Box::new(|| b"loaded\n".to_vec()),
                ));
                Some(SyntheticNode::Dir { children })
            }),
        });

        // Walk into dynamic dir root.
        let (fid, qid) = tree.walk(&[], "alice", None).unwrap();
        assert_eq!(qid.qtype, QTDIR);
        tree.open(fid, OREAD, "alice").unwrap();
        let data = tree.read(fid, 0, 4096, "alice").unwrap();
        assert!(!data.is_empty());
        tree.clunk(fid, "alice");

        // Walk to a dynamic child's file.
        let (fid2, qid2) = tree.walk(&["model-a".into(), "status".into()], "alice", None).unwrap();
        assert_eq!(qid2.qtype, QTFILE);
        tree.open(fid2, OREAD, "alice").unwrap();
        let content = tree.read(fid2, 0, 1024, "alice").unwrap();
        assert_eq!(content, b"loaded\n");
        tree.clunk(fid2, "alice");
    }

    // ── VFS integration tests ───────────────────────────────────────────────

    #[test]
    fn vfs_cat_reads_synthetic_file() {
        use hyprstream_vfs::{Namespace, Subject};
        use std::sync::Arc;

        let tree = make_tree();
        let mut ns = Namespace::new();
        ns.mount("/srv/model", Arc::new(tree)).unwrap();

        let caller = Subject::new("alice");
        let data = ns.cat("/srv/model/test-model/status", &caller).unwrap();
        assert_eq!(data, b"loaded\n");
    }

    #[test]
    fn vfs_ctl_writes_and_reads_response() {
        use hyprstream_vfs::{Namespace, Subject};
        use std::sync::Arc;

        let tree = make_tree();
        let mut ns = Namespace::new();
        ns.mount("/srv/model", Arc::new(tree)).unwrap();

        let caller = Subject::new("alice");

        // ctl: write command + read response in one fid lifecycle.
        let resp = ns.ctl("/srv/model/test-model/ctl", b"load", &caller).unwrap();
        assert_eq!(resp, b"ok: load");
    }

    #[test]
    fn vfs_ls_lists_directory() {
        use hyprstream_vfs::{Namespace, Subject};
        use std::sync::Arc;

        let tree = make_tree();
        let mut ns = Namespace::new();
        ns.mount("/srv/model", Arc::new(tree)).unwrap();

        let caller = Subject::new("alice");
        let entries = ns.ls("/srv/model/test-model", &caller).unwrap();
        let names: Vec<&str> = entries.iter().map(|e| e.name.as_str()).collect();
        assert!(names.contains(&"status"));
        assert!(names.contains(&"ctl"));
    }

    #[test]
    fn vfs_dynamic_dir_with_namespace() {
        use hyprstream_vfs::{Namespace, Subject};
        use std::sync::Arc;

        // Build a dynamic tree (like the model service would).
        let tree = SyntheticTree::new(SyntheticNode::DynamicDir {
            list: Box::new(|| vec![
                DirEntry { name: "qwen3:main".into(), is_dir: true, size: 0, stat: None },
            ]),
            resolve: Box::new(|_name| {
                let mut children = HashMap::new();
                children.insert("status".to_owned(), SyntheticNode::ReadFile(
                    Box::new(|| b"loaded\n".to_vec()),
                ));
                children.insert("defaults".to_owned(), SyntheticNode::ReadFile(
                    Box::new(|| b"{\"temperature\": 0.7}\n".to_vec()),
                ));
                children.insert("ctl".to_owned(), SyntheticNode::CtlFile {
                    handler: Box::new(|data| {
                        let cmd = String::from_utf8_lossy(data);
                        Ok(format!("ctl: {}\n", cmd.trim()).into_bytes())
                    }),
                });
                Some(SyntheticNode::Dir { children })
            }),
        });

        let mut ns = Namespace::new();
        ns.mount("/srv/model", Arc::new(tree)).unwrap();

        let caller = Subject::new("alice");

        // Read model status through the VFS.
        let status = ns.cat("/srv/model/qwen3:main/status", &caller).unwrap();
        assert_eq!(status, b"loaded\n");

        // Read model defaults.
        let defaults = ns.cat("/srv/model/qwen3:main/defaults", &caller).unwrap();
        assert!(defaults.starts_with(b"{\"temperature\""));

        // Write to ctl and read response (single fid lifecycle).
        let resp = ns.ctl("/srv/model/qwen3:main/ctl", b"load", &caller).unwrap();
        assert_eq!(resp, b"ctl: load\n");
    }

    #[test]
    fn vfs_tenant_isolation() {
        use hyprstream_vfs::{Namespace, Subject};
        use std::sync::Arc;

        let tree = make_tree();
        let mut ns = Namespace::new();
        ns.mount("/srv/model", Arc::new(tree)).unwrap();

        let alice = Subject::new("alice");
        let bob = Subject::new("bob");

        // Both tenants can read (cat does walk+open+read+clunk atomically).
        let data_a = ns.cat("/srv/model/test-model/status", &alice).unwrap();
        let data_b = ns.cat("/srv/model/test-model/status", &bob).unwrap();
        assert_eq!(data_a, data_b);
        assert_eq!(data_a, b"loaded\n");
    }

    #[test]
    fn vfs_namespace_fork_isolation() {
        use hyprstream_vfs::{Namespace, Subject};
        use std::sync::Arc;

        let tree = make_tree();
        let mut ns = Namespace::new();
        ns.mount("/srv/model", Arc::new(tree)).unwrap();
        ns.mount("/srv/worker", Arc::new(
            SyntheticTree::new(SyntheticNode::Dir { children: HashMap::new() }),
        )).unwrap();

        let caller = Subject::new("alice");

        // Fork and restrict.
        let mut sandbox = ns.fork();
        sandbox.unmount("/srv/worker");

        // Parent can access both.
        assert!(ns.cat("/srv/model/test-model/status", &caller).is_ok());
        assert!(ns.ls("/srv/worker", &caller).is_ok());

        // Child can access model but not worker.
        assert!(sandbox.cat("/srv/model/test-model/status", &caller).is_ok());
        assert!(sandbox.ls("/srv/worker", &caller).is_err());
    }
}
