//! Auto-generated typed clients from Cap'n Proto schemas.
//!
//! Each module is generated by the `generate_rpc_service!` proc macro
//! from the corresponding `.capnp` schema file. These clients implement
//! `ServiceClient` and provide type-safe async methods for each request variant.

pub mod model_client {
    #![allow(dead_code, unused_imports, unused_variables)]
    #![allow(clippy::all)]
    hyprstream_rpc_derive::generate_rpc_service!("model");
}

pub mod registry_client {
    #![allow(dead_code, unused_imports, unused_variables)]
    #![allow(clippy::all)]
    hyprstream_rpc_derive::generate_rpc_service!("registry");
}

pub mod policy_client {
    #![allow(dead_code, unused_imports, unused_variables)]
    #![allow(clippy::all)]
    hyprstream_rpc_derive::generate_rpc_service!("policy");
}

pub mod inference_client {
    #![allow(dead_code, unused_imports, unused_variables)]
    #![allow(clippy::all)]
    hyprstream_rpc_derive::generate_rpc_service!("inference");
}

pub mod mcp_client_gen {
    #![allow(dead_code, unused_imports, unused_variables)]
    #![allow(clippy::all)]
    hyprstream_rpc_derive::generate_rpc_service!("mcp");
}
