//! Service layer constants and 9P protocol types.

// ─────────────────────────────────────────────────────────────────────────────
// Resource limits
// ─────────────────────────────────────────────────────────────────────────────

/// Default iounit for 9P read/write operations (64 KiB).
/// This is the maximum bytes per single read/write message.
/// Clients must loop to transfer files larger than this.
pub const DEFAULT_IOUNIT: u32 = 64 * 1024;

/// Maximum allowed iounit (16 MiB). Server will never return an iounit
/// larger than this, regardless of what the client requests.
pub const MAX_IOUNIT: u32 = 16 * 1024 * 1024;

/// Maximum open fids per client.
pub const MAX_FIDS_PER_CLIENT: u32 = 64;

/// Maximum open fids globally.
pub const MAX_FIDS_GLOBAL: u32 = 4096;

// Legacy aliases (used in existing code)
pub const MAX_FS_IO_SIZE: u64 = MAX_IOUNIT as u64;
pub const MAX_FDS_PER_CLIENT: u32 = MAX_FIDS_PER_CLIENT;
pub const MAX_FDS_GLOBAL: u32 = MAX_FIDS_GLOBAL;

// ─────────────────────────────────────────────────────────────────────────────
// 9P Qid types (file type bits in Qid.type)
// ─────────────────────────────────────────────────────────────────────────────

/// Directory
pub const QTDIR: u8 = 0x80;
/// Append-only file
#[allow(dead_code)]
pub const QTAPPEND: u8 = 0x40;
/// Exclusive-use file
#[allow(dead_code)]
pub const QTEXCL: u8 = 0x20;
/// Regular file
pub const QTFILE: u8 = 0x00;

// ─────────────────────────────────────────────────────────────────────────────
// 9P open modes (NpOpen.mode / NpCreate.mode)
// ─────────────────────────────────────────────────────────────────────────────

/// Open for reading
pub const OREAD: u8 = 0;
/// Open for writing
pub const OWRITE: u8 = 1;
/// Open for read+write
pub const ORDWR: u8 = 2;
/// Truncate on open (OR'd with above)
pub const OTRUNC: u8 = 0x10;
/// Remove on clunk (OR'd with above)
pub const ORCLOSE: u8 = 0x40;

// ─────────────────────────────────────────────────────────────────────────────
// 9P permission bits (NpCreate.perm)
// ─────────────────────────────────────────────────────────────────────────────

/// Directory flag in perm field
pub const DMDIR: u32 = 0x80000000;

// ─────────────────────────────────────────────────────────────────────────────
// Directory entry info (not generated by codegen — standalone type)
// ─────────────────────────────────────────────────────────────────────────────

/// Directory entry returned by list_dir operations.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct FsDirEntryInfo {
    pub name: String,
    pub is_dir: bool,
    pub size: u64,
}
